/**
 * Products & Services catalog seed.
 *
 * Three levels, always: Product › Subcategory › Item. Items are LEAVES and the
 * only nodes that carry content — a product or a subcategory is navigation.
 *
 * Items do not OWN their content. They reference shared atoms:
 *     knowledgeIds -> `knowledge`   (the same article can be a lesson too)
 *     subformIds   -> `subforms`    (the same intake can hang off two items)
 * That indirection is what lets "Password Reset" appear under Accounts AND under
 * the Storefront without re-authoring anything, and what lets the Learning module
 * build a course out of catalog knowledge. See src/store/schema.js.
 *
 * Northwind Systems runs one catalog for two audiences: five internal products
 * for employees, and Northwind Storefront — the product customers actually buy —
 * for external customers. `audience` is per node, so a subcategory can be shared
 * by both ('both') even when its parent is internal.
 */

import { CAT, KB, SF, USR } from './ids.js';

export const CATALOG = [
  /* ================================================================== *
   * 1 — Accounts & Access
   * ================================================================== */
  {
    id: CAT.P_ACCOUNTS,
    name: 'Accounts & Access',
    type: 'product',
    audience: 'internal',
    ownerId: USR.EMMA,
    description: 'Sign-in, multi-factor, application access and everything that decides who can get into what.',
    children: [
      {
        id: 'cat-s-signin',
        name: 'Sign-in & passwords',
        type: 'subcategory',
        audience: 'internal',
        description: 'The single highest-volume topic on the service desk.',
        children: [
          {
            id: CAT.I_CANNOT_SIGN_IN,
            name: 'Cannot sign in',
            type: 'item',
            audience: 'internal',
            popular: true,
            fulfillment: 'Same day',
            description: 'Password rejected, account locked out, or the sign-in page loops back on itself.',
            knowledgeIds: [KB.RESET_PASSWORD, KB.ACCOUNT_LOCKED],
            subformIds: [SF.REPORT_SIGNIN],
          },
          {
            id: CAT.I_MFA,
            name: 'Multi-factor authentication',
            type: 'item',
            audience: 'internal',
            popular: true,
            fulfillment: '2 hours',
            description: 'Enrol a new phone, replace a lost authenticator, or get a temporary bypass code.',
            knowledgeIds: [KB.MFA_SETUP, KB.ACCOUNT_LOCKED],
            subformIds: [SF.MFA_RESET],
          },
          {
            id: 'cat-i-sso',
            name: 'Single sign-on (SSO)',
            type: 'item',
            audience: 'both',
            description: 'How Northwind SSO works, which apps are behind it, and what to do when an app asks for a separate password.',
            knowledgeIds: [KB.SSO_EXPLAINED, KB.RESET_PASSWORD],
            subformIds: [SF.REPORT_SIGNIN],
          },
          {
            id: 'cat-i-password-policy',
            name: 'Password & passkey policy',
            type: 'item',
            audience: 'internal',
            description: 'Length, rotation, passkey rollout and why the old 90-day expiry was retired.',
            knowledgeIds: [KB.RESET_PASSWORD, KB.SSO_EXPLAINED],
            subformIds: [],
          },
        ],
      },
      {
        id: 'cat-s-app-access',
        name: 'Application access',
        type: 'subcategory',
        audience: 'internal',
        description: 'Requesting, extending and revoking access to internal systems.',
        children: [
          {
            id: 'cat-i-request-app',
            name: 'Request access to an application',
            type: 'item',
            audience: 'internal',
            popular: true,
            fulfillment: '1-2 business days',
            description: 'Salesforce, NetSuite, Looker, the data warehouse — anything that needs a manager approval before provisioning.',
            knowledgeIds: [KB.SSO_EXPLAINED, KB.APPROVAL_THRESHOLDS],
            subformIds: [SF.REQUEST_ACCESS],
          },
          {
            id: 'cat-i-shared-mailbox-access',
            name: 'Shared mailbox or group access',
            type: 'item',
            audience: 'internal',
            fulfillment: '1 business day',
            description: 'Join support@, billing@ or a team distribution list, with or without send-as rights.',
            knowledgeIds: [KB.EMAIL_SIGNATURE],
            subformIds: [SF.REQUEST_ACCESS, SF.DISTRIBUTION_LIST],
          },
          {
            id: 'cat-i-elevated-rights',
            name: 'Elevated or admin rights',
            type: 'item',
            audience: 'internal',
            fulfillment: '2 business days',
            description: 'Local admin, production console access or a break-glass account. Always time-boxed and always approved.',
            knowledgeIds: [KB.APPROVAL_THRESHOLDS, KB.CHANGE_PROCESS],
            subformIds: [SF.REQUEST_ACCESS],
          },
        ],
      },
      {
        id: 'cat-s-identity',
        name: 'Identity & directory',
        type: 'subcategory',
        audience: 'internal',
        description: 'The records everything else resolves against — names, managers, contractors.',
        children: [
          {
            id: 'cat-i-directory-profile',
            name: 'Update my directory profile',
            type: 'item',
            audience: 'internal',
            fulfillment: '1 business day',
            description: 'Legal or preferred name, job title, manager, desk location and pronouns.',
            knowledgeIds: [KB.EMAIL_SIGNATURE, KB.ONBOARDING_CHECKLIST],
            subformIds: [SF.REQUEST_ACCESS],
          },
          {
            id: 'cat-i-contractor-account',
            name: 'Contractor & vendor accounts',
            type: 'item',
            audience: 'internal',
            fulfillment: '3 business days',
            description: 'Time-limited accounts for agencies and implementation partners. Expiry date is mandatory.',
            knowledgeIds: [KB.SSO_EXPLAINED, KB.ONBOARDING_CHECKLIST],
            subformIds: [SF.NEW_HIRE, SF.REQUEST_ACCESS],
          },
          {
            id: 'cat-i-account-locked',
            name: 'Locked or disabled account',
            type: 'item',
            audience: 'internal',
            description: 'Repeated failed sign-ins, an expired contractor account, or a security hold after a phishing report.',
            knowledgeIds: [KB.ACCOUNT_LOCKED, KB.MFA_SETUP],
            subformIds: [SF.REPORT_SIGNIN],
          },
        ],
      },
    ],
  },

  /* ================================================================== *
   * 2 — Email & Calendar
   * ================================================================== */
  {
    id: CAT.P_EMAIL,
    name: 'Email & Calendar',
    type: 'product',
    audience: 'internal',
    ownerId: USR.EMMA,
    description: 'Mail delivery, mobile setup, distribution lists and the meeting-room booking system.',
    children: [
      {
        id: 'cat-s-mail-delivery',
        name: 'Mailbox & delivery',
        type: 'subcategory',
        audience: 'internal',
        description: 'Mail that did not arrive, or arrived where it should not have.',
        children: [
          {
            id: 'cat-i-email-not-working',
            name: 'Email not sending or receiving',
            type: 'item',
            audience: 'internal',
            popular: true,
            fulfillment: 'Same day',
            description: 'Messages stuck in the outbox, bounce-backs from a customer domain, or a mailbox that stopped syncing.',
            knowledgeIds: [KB.SPAM_QUARANTINE, KB.EMAIL_ON_PHONE],
            subformIds: [SF.EMAIL_PROBLEM],
          },
          {
            id: 'cat-i-quarantine',
            name: 'Quarantined or suspected spam',
            type: 'item',
            audience: 'internal',
            description: 'Release a held message, report a phishing attempt, or allow-list a customer domain.',
            knowledgeIds: [KB.SPAM_QUARANTINE],
            subformIds: [SF.EMAIL_PROBLEM],
          },
          {
            id: 'cat-i-mailbox-storage',
            name: 'Mailbox storage & archiving',
            type: 'item',
            audience: 'internal',
            description: 'Over-quota warnings, archive policy and how to recover a message deleted last quarter.',
            knowledgeIds: [KB.SPAM_QUARANTINE, KB.EMAIL_SIGNATURE],
            subformIds: [SF.EMAIL_PROBLEM],
          },
        ],
      },
      {
        id: 'cat-s-mail-clients',
        name: 'Mobile & mail clients',
        type: 'subcategory',
        audience: 'internal',
        description: 'Getting mail onto the device the person actually uses.',
        children: [
          {
            id: 'cat-i-email-on-phone',
            name: 'Set up email on a phone or tablet',
            type: 'item',
            audience: 'internal',
            popular: true,
            description: 'Profile install, MFA prompt, and what the mobile-device policy will and will not do to a personal phone.',
            knowledgeIds: [KB.EMAIL_ON_PHONE, KB.MFA_SETUP],
            subformIds: [SF.EMAIL_PROBLEM],
          },
          {
            id: 'cat-i-email-signature',
            name: 'Email signature',
            type: 'item',
            audience: 'internal',
            description: 'The approved Northwind signature block, including the support-team variant with the SLA line.',
            knowledgeIds: [KB.EMAIL_SIGNATURE],
            subformIds: [SF.EMAIL_PROBLEM],
          },
          {
            id: 'cat-i-desktop-mail-client',
            name: 'Desktop mail client setup',
            type: 'item',
            audience: 'internal',
            description: 'Outlook and Apple Mail profiles, offline caching, and the shared-mailbox add-in.',
            knowledgeIds: [KB.EMAIL_ON_PHONE, KB.INSTALL_SOFTWARE],
            subformIds: [SF.EMAIL_PROBLEM, SF.SOFTWARE_REQUEST],
          },
        ],
      },
      {
        id: 'cat-s-groups-calendars',
        name: 'Groups & calendars',
        type: 'subcategory',
        audience: 'internal',
        description: 'Anything addressed to more than one person.',
        children: [
          {
            id: 'cat-i-distribution-list',
            name: 'Distribution list or shared calendar',
            type: 'item',
            audience: 'internal',
            fulfillment: '1 business day',
            description: 'Create a list, change its owner, or open it up to senders outside Northwind.',
            knowledgeIds: [KB.EMAIL_SIGNATURE, KB.APPROVAL_THRESHOLDS],
            subformIds: [SF.DISTRIBUTION_LIST],
          },
          {
            id: 'cat-i-room-booking',
            name: 'Meeting rooms & resources',
            type: 'item',
            audience: 'internal',
            description: 'Room calendars, video-conference kit in each room, and how to release a room you no longer need.',
            knowledgeIds: [KB.EMAIL_SIGNATURE],
            subformIds: [SF.FACILITIES_ISSUE],
          },
        ],
      },
    ],
  },

  /* ================================================================== *
   * 3 — Devices & Hardware
   * ================================================================== */
  {
    id: CAT.P_DEVICES,
    name: 'Devices & Hardware',
    type: 'product',
    audience: 'internal',
    ownerId: USR.JAMES,
    description: 'Laptops, peripherals, phones and the return/repair loop. Every item here can link to an asset record.',
    children: [
      {
        id: 'cat-s-computers',
        name: 'Laptops & desktops',
        type: 'subcategory',
        audience: 'internal',
        description: 'The primary machine. Refresh cycle is 36 months.',
        children: [
          {
            id: CAT.I_LAPTOP_ISSUE,
            name: 'Laptop problem',
            type: 'item',
            audience: 'internal',
            popular: true,
            fulfillment: 'Same day triage',
            description: 'Will not boot, battery drains in an hour, fans at full tilt, or the screen flickers on wake.',
            knowledgeIds: [KB.SCREEN_FLICKER, KB.LAPTOP_SETUP],
            subformIds: [SF.LAPTOP_REPAIR],
          },
          {
            id: CAT.I_NEW_LAPTOP,
            name: 'New laptop or refresh',
            type: 'item',
            audience: 'internal',
            popular: true,
            fulfillment: '5-7 business days',
            description: 'Standard, engineering and design configurations. Anything above the standard build needs manager approval.',
            knowledgeIds: [KB.LAPTOP_SETUP, KB.APPROVAL_THRESHOLDS],
            subformIds: [SF.NEW_HARDWARE],
          },
          {
            id: 'cat-i-machine-setup',
            name: 'Set up a new machine',
            type: 'item',
            audience: 'internal',
            description: 'First-boot enrolment, disk encryption, VPN profile and the standard software baseline.',
            knowledgeIds: [KB.LAPTOP_SETUP, KB.INSTALL_SOFTWARE, KB.MFA_SETUP],
            subformIds: [SF.NEW_HARDWARE],
          },
        ],
      },
      {
        id: 'cat-s-peripherals',
        name: 'Peripherals & accessories',
        type: 'subcategory',
        audience: 'internal',
        description: 'Everything that plugs into the primary machine.',
        children: [
          {
            id: 'cat-i-monitor',
            name: 'Monitor or docking station',
            type: 'item',
            audience: 'internal',
            fulfillment: '3-5 business days',
            description: 'Second display for the office or home desk, plus the dock that drives two 4K panels.',
            knowledgeIds: [KB.REQUEST_MONITOR, KB.SCREEN_FLICKER],
            subformIds: [SF.NEW_HARDWARE],
          },
          {
            id: 'cat-i-desk-accessories',
            name: 'Headset, keyboard & mouse',
            type: 'item',
            audience: 'internal',
            fulfillment: '3-5 business days',
            description: 'The support-team headset standard, ergonomic keyboards, and replacements for worn kit.',
            knowledgeIds: [KB.REQUEST_MONITOR],
            subformIds: [SF.NEW_HARDWARE],
          },
          {
            id: 'cat-i-printing',
            name: 'Printing & scanning',
            type: 'item',
            audience: 'internal',
            description: 'Add a floor printer, clear a stuck job, or scan to the shared drive.',
            knowledgeIds: [KB.INSTALL_SOFTWARE],
            subformIds: [SF.FACILITIES_ISSUE],
          },
        ],
      },
      {
        id: 'cat-s-mobile',
        name: 'Mobile devices',
        type: 'subcategory',
        audience: 'internal',
        description: 'Company phones and tablets, and the incident path when one goes missing.',
        children: [
          {
            id: 'cat-i-company-phone',
            name: 'Company phone or tablet',
            type: 'item',
            audience: 'internal',
            fulfillment: '5 business days',
            description: 'Eligible roles, plan tiers, and the international-roaming add-on for the field team.',
            knowledgeIds: [KB.EMAIL_ON_PHONE, KB.APPROVAL_THRESHOLDS],
            subformIds: [SF.NEW_HARDWARE],
          },
          {
            id: 'cat-i-lost-device',
            name: 'Lost or stolen device',
            type: 'item',
            audience: 'internal',
            popular: true,
            fulfillment: 'Immediate',
            description: 'Remote wipe, credential rotation and the security report. Raise this before anything else.',
            knowledgeIds: [KB.ACCOUNT_LOCKED, KB.MFA_SETUP, KB.RETURN_EQUIPMENT],
            subformIds: [SF.LAPTOP_REPAIR, SF.REPORT_SIGNIN],
          },
        ],
      },
      {
        id: 'cat-s-returns',
        name: 'Returns & repairs',
        type: 'subcategory',
        audience: 'internal',
        description: 'The other end of the asset lifecycle — the part most catalogs forget.',
        children: [
          {
            id: 'cat-i-return-equipment',
            name: 'Return equipment',
            type: 'item',
            audience: 'internal',
            description: 'Prepaid label, wipe confirmation and the asset record hand-back. Required within 5 days of a leave date.',
            knowledgeIds: [KB.RETURN_EQUIPMENT, KB.ONBOARDING_CHECKLIST],
            subformIds: [SF.RETURN_HARDWARE],
          },
          {
            id: 'cat-i-repair-warranty',
            name: 'Repair or warranty claim',
            type: 'item',
            audience: 'internal',
            fulfillment: '7-10 business days',
            description: 'Depot repair, on-site vendor visit, or an accidental-damage claim against the fleet contract.',
            knowledgeIds: [KB.SCREEN_FLICKER, KB.RETURN_EQUIPMENT],
            subformIds: [SF.LAPTOP_REPAIR, SF.RETURN_HARDWARE],
          },
          {
            id: 'cat-i-loaner',
            name: 'Loaner equipment',
            type: 'item',
            audience: 'internal',
            fulfillment: 'Same day',
            description: 'Short-term laptop or hotspot while a machine is in repair or a new hire waits on stock.',
            knowledgeIds: [KB.LAPTOP_SETUP, KB.RETURN_EQUIPMENT],
            subformIds: [SF.NEW_HARDWARE, SF.RETURN_HARDWARE],
          },
        ],
      },
    ],
  },

  /* ================================================================== *
   * 4 — Software & Licensing
   * ================================================================== */
  {
    id: CAT.P_SOFTWARE,
    name: 'Software & Licensing',
    type: 'product',
    audience: 'internal',
    ownerId: USR.JAMES,
    description: 'Installs, subscriptions, renewals and the spend approvals that hang off them.',
    children: [
      {
        id: 'cat-s-install',
        name: 'Install & updates',
        type: 'subcategory',
        audience: 'internal',
        description: 'Getting approved software onto a machine.',
        children: [
          {
            id: CAT.I_SOFTWARE_REQ,
            name: 'Install software',
            type: 'item',
            audience: 'internal',
            popular: true,
            fulfillment: '1-2 business days',
            description: 'Anything from the self-service catalogue installs immediately; everything else routes for review.',
            knowledgeIds: [KB.INSTALL_SOFTWARE, KB.LICENSE_POLICY],
            subformIds: [SF.SOFTWARE_REQUEST],
          },
          {
            id: 'cat-i-adobe',
            name: 'Adobe Creative Cloud',
            type: 'item',
            audience: 'internal',
            fulfillment: '2 business days',
            description: 'Named-user activation, the shared design pool, and what to do when the app says the licence expired.',
            knowledgeIds: [KB.ADOBE_ACTIVATION, KB.LICENSE_POLICY],
            subformIds: [SF.SOFTWARE_REQUEST, SF.LICENSE_RENEWAL],
          },
          {
            id: 'cat-i-os-updates',
            name: 'Operating system & browser updates',
            type: 'item',
            audience: 'internal',
            description: 'Patch windows, deferral limits and why a major OS upgrade goes through change control.',
            knowledgeIds: [KB.INSTALL_SOFTWARE, KB.CHANGE_PROCESS],
            subformIds: [SF.SOFTWARE_REQUEST],
          },
        ],
      },
      {
        id: 'cat-s-licensing',
        name: 'Licenses & renewals',
        type: 'subcategory',
        audience: 'internal',
        description: 'Procurement territory. Every request here can trigger an approval policy.',
        children: [
          {
            id: 'cat-i-new-license',
            name: 'New license or subscription',
            type: 'item',
            audience: 'internal',
            fulfillment: '5 business days',
            description: 'A tool nobody has bought yet — needs security review, budget owner sign-off and a renewal date.',
            knowledgeIds: [KB.LICENSE_POLICY, KB.APPROVAL_THRESHOLDS],
            subformIds: [SF.LICENSE_RENEWAL, SF.EXPENSE_APPROVAL],
          },
          {
            id: 'cat-i-renewal',
            name: 'Renewal & true-up',
            type: 'item',
            audience: 'internal',
            description: 'The 60-day renewal notice, seat reconciliation, and reclaiming licences from leavers.',
            knowledgeIds: [KB.LICENSE_POLICY, KB.RETURN_EQUIPMENT],
            subformIds: [SF.LICENSE_RENEWAL],
          },
          {
            id: 'cat-i-spend-approval',
            name: 'Software spend approval',
            type: 'item',
            audience: 'internal',
            description: 'Thresholds: under $500 is a manager, $500-$5,000 adds Finance, above that adds the VP.',
            knowledgeIds: [KB.APPROVAL_THRESHOLDS, KB.LICENSE_POLICY],
            subformIds: [SF.EXPENSE_APPROVAL],
          },
        ],
      },
      {
        id: 'cat-s-dev-tooling',
        name: 'Developer tooling',
        type: 'subcategory',
        audience: 'both',
        description: 'Shared with customers: the same API-key and sandbox guidance serves Northwind engineers and customer developers.',
        children: [
          {
            id: 'cat-i-api-credentials',
            name: 'API keys & service credentials',
            type: 'item',
            audience: 'both',
            fulfillment: '1 business day',
            description: 'Issue, rotate and scope a key. Never share one between environments.',
            knowledgeIds: [KB.API_KEYS, KB.SSO_EXPLAINED],
            subformIds: [SF.REQUEST_ACCESS, SF.INTEGRATION_HELP],
          },
          {
            id: 'cat-i-sandbox',
            name: 'Sandbox & test environments',
            type: 'item',
            audience: 'both',
            fulfillment: '2 business days',
            description: 'Provision a sandbox, refresh its data, or extend one past its 30-day expiry.',
            knowledgeIds: [KB.CHANGE_PROCESS, KB.API_KEYS],
            subformIds: [SF.SOFTWARE_REQUEST, SF.INTEGRATION_HELP],
          },
        ],
      },
    ],
  },

  /* ================================================================== *
   * 5 — Workplace & Facilities
   * ================================================================== */
  {
    id: CAT.P_WORKPLACE,
    name: 'Workplace & Facilities',
    type: 'product',
    audience: 'internal',
    ownerId: USR.LINDA,
    description: 'Buildings and desks, joining and leaving, and the ways-of-working material the service desk itself is trained on.',
    children: [
      {
        id: 'cat-s-building',
        name: 'Building & desks',
        type: 'subcategory',
        audience: 'internal',
        description: 'Chicago HQ, New York, Austin and the Bolingbrook warehouse.',
        children: [
          {
            id: 'cat-i-facilities-issue',
            name: 'Report a facilities issue',
            type: 'item',
            audience: 'internal',
            popular: true,
            fulfillment: 'Same day',
            description: 'Temperature, lighting, a leak, a broken chair — anything about the physical space.',
            knowledgeIds: [],
            subformIds: [SF.FACILITIES_ISSUE],
          },
          {
            id: 'cat-i-desk-move',
            name: 'Desk or seating change',
            type: 'item',
            audience: 'internal',
            fulfillment: '3 business days',
            description: 'Move a person or a whole team. Includes monitor arms, cable runs and the floor-plan update.',
            knowledgeIds: [KB.REQUEST_MONITOR],
            subformIds: [SF.FACILITIES_ISSUE],
          },
          {
            id: 'cat-i-badge-access',
            name: 'Badge & building access',
            type: 'item',
            audience: 'internal',
            fulfillment: '1 business day',
            description: 'New badge, replacement badge, after-hours access or access to the Elk Grove data centre.',
            knowledgeIds: [KB.ACCOUNT_LOCKED, KB.APPROVAL_THRESHOLDS],
            subformIds: [SF.REQUEST_ACCESS, SF.FACILITIES_ISSUE],
          },
        ],
      },
      {
        id: 'cat-s-joining-leaving',
        name: 'Joining & leaving',
        type: 'subcategory',
        audience: 'internal',
        description: 'The two most cross-functional requests Northwind runs. Both fan out to IT, Facilities and People Ops.',
        children: [
          {
            id: 'cat-i-new-hire',
            name: 'New hire onboarding',
            type: 'item',
            audience: 'internal',
            popular: true,
            fulfillment: 'Start date - 5 days',
            description: 'One request produces the account, the laptop, the badge, the seat and the first-week curriculum.',
            knowledgeIds: [KB.ONBOARDING_CHECKLIST, KB.LAPTOP_SETUP, KB.MFA_SETUP],
            subformIds: [SF.NEW_HIRE],
          },
          {
            id: 'cat-i-offboarding',
            name: 'Offboarding a leaver',
            type: 'item',
            audience: 'internal',
            fulfillment: 'Last day',
            description: 'Disable access at the right hour, recover equipment, reassign owned records, reclaim licences.',
            knowledgeIds: [KB.RETURN_EQUIPMENT, KB.ONBOARDING_CHECKLIST, KB.LICENSE_POLICY],
            subformIds: [SF.OFFBOARDING, SF.RETURN_HARDWARE],
          },
          {
            id: 'cat-i-contractor-onboarding',
            name: 'Contractor onboarding',
            type: 'item',
            audience: 'internal',
            fulfillment: '3 business days',
            description: 'A lighter onboarding with a mandatory end date and no default building access.',
            knowledgeIds: [KB.ONBOARDING_CHECKLIST, KB.SSO_EXPLAINED],
            subformIds: [SF.NEW_HIRE],
          },
          {
            id: 'cat-i-role-change',
            name: 'Internal move or role change',
            type: 'item',
            audience: 'internal',
            description: 'Access that should follow the person, access that should not, and the manager-chain update.',
            knowledgeIds: [KB.ONBOARDING_CHECKLIST, KB.APPROVAL_THRESHOLDS],
            subformIds: [SF.NEW_HIRE, SF.REQUEST_ACCESS],
          },
        ],
      },
      {
        id: 'cat-s-ways-of-working',
        name: 'Ways of working',
        type: 'subcategory',
        audience: 'internal',
        description: 'The service desk’s own enablement material. Every atom here is also a lesson in the Support Agent curriculum.',
        children: [
          {
            id: 'cat-i-working-a-queue',
            name: 'Working a ticket queue',
            type: 'item',
            audience: 'internal',
            description: 'Triage order, what a good first response looks like, and the macros that save the most typing.',
            knowledgeIds: [KB.TRIAGE_BASICS, KB.READING_A_TICKET, KB.USING_MACROS],
            subformIds: [],
          },
          {
            id: 'cat-i-customer-comms',
            name: 'Customer communication standards',
            type: 'item',
            audience: 'internal',
            description: 'Tone, structure and the close. Includes the de-escalation script the Austin team wrote.',
            knowledgeIds: [KB.WRITING_TO_CUSTOMERS, KB.HANDLING_ANGRY, KB.CLOSING_WELL],
            subformIds: [],
          },
          {
            id: 'cat-i-escalation-sla',
            name: 'Escalation paths & SLA commitments',
            type: 'item',
            audience: 'internal',
            description: 'Who to pull in, when the clock pauses, and what an Enterprise customer has actually been promised.',
            knowledgeIds: [KB.ESCALATION_PATHS, KB.SLA_EXPLAINED],
            subformIds: [],
          },
          {
            id: 'cat-i-raise-a-change',
            name: 'Raise a change request',
            type: 'item',
            audience: 'internal',
            description: 'Standard, normal and emergency changes — which one you are actually raising, and who authorises it.',
            knowledgeIds: [KB.CHANGE_PROCESS, KB.APPROVAL_THRESHOLDS],
            subformIds: [SF.EXPENSE_APPROVAL],
          },
        ],
      },
    ],
  },

  /* ================================================================== *
   * 6 — Northwind Storefront — the product customers buy.
   * Everything under here is customer-facing, which is why the whole product
   * carries audience 'external'.
   * ================================================================== */
  {
    id: CAT.P_STOREFRONT,
    name: 'Northwind Storefront',
    type: 'product',
    audience: 'external',
    ownerId: USR.LISA,
    description: 'The commerce platform Northwind sells. This branch is what customers see in the help centre and the portal.',
    children: [
      {
        id: 'cat-s-getting-started',
        name: 'Getting started',
        type: 'subcategory',
        audience: 'external',
        description: 'The first two weeks of a new customer. Deflection here is worth more than anywhere else in the catalog.',
        children: [
          {
            id: CAT.I_STOREFRONT_SETUP,
            name: 'Set up your storefront',
            type: 'item',
            audience: 'external',
            popular: true,
            description: 'Domain, theme, tax profile and the go-live checklist. Ten minutes if the domain is already delegated.',
            knowledgeIds: [KB.STOREFRONT_SETUP],
            subformIds: [SF.INTEGRATION_HELP],
          },
          {
            id: 'cat-i-import-catalog',
            name: 'Import your product catalog',
            type: 'item',
            audience: 'external',
            popular: true,
            description: 'CSV template, column mapping, variant handling, and what happens to rows that fail validation.',
            knowledgeIds: [KB.IMPORT_CATALOG, KB.STOREFRONT_SETUP],
            subformIds: [SF.INTEGRATION_HELP],
          },
          {
            id: 'cat-i-invite-team',
            name: 'Invite your team',
            type: 'item',
            audience: 'external',
            description: 'Roles, permissions and connecting your own identity provider so staff sign in with your SSO.',
            knowledgeIds: [KB.STOREFRONT_SETUP, KB.SSO_EXPLAINED],
            subformIds: [SF.INTEGRATION_HELP],
          },
        ],
      },
      {
        id: 'cat-s-payments-billing',
        name: 'Payments & billing',
        type: 'subcategory',
        audience: 'external',
        description: 'Money in from shoppers, and money out to Northwind. Two different things customers routinely conflate.',
        children: [
          {
            id: CAT.I_PAYMENTS,
            name: 'Connect payments',
            type: 'item',
            audience: 'external',
            popular: true,
            description: 'Connect a payment provider, verify the business, and understand the payout schedule.',
            knowledgeIds: [KB.CONNECT_PAYMENTS],
            subformIds: [SF.INTEGRATION_HELP, SF.STOREFRONT_BUG],
          },
          {
            id: CAT.I_BILLING,
            name: 'Invoices & billing questions',
            type: 'item',
            audience: 'external',
            popular: true,
            description: 'Read your Northwind invoice, change the billing contact, or query a line you do not recognise.',
            knowledgeIds: [KB.INVOICE_QUESTIONS],
            subformIds: [SF.BILLING_QUESTION],
          },
          {
            id: 'cat-i-plans-seats',
            name: 'Plans, seats & upgrades',
            type: 'item',
            audience: 'external',
            description: 'What each plan includes, how mid-cycle upgrades are prorated, and when a seat count is trued up.',
            knowledgeIds: [KB.INVOICE_QUESTIONS, KB.SLA_EXPLAINED],
            subformIds: [SF.BILLING_QUESTION],
          },
        ],
      },
      {
        id: 'cat-s-integrations',
        name: 'Integrations & API',
        type: 'subcategory',
        audience: 'external',
        description: 'Where customer developers land. Deep-linked from the API docs.',
        children: [
          {
            id: 'cat-i-storefront-api-keys',
            name: 'API keys',
            type: 'item',
            audience: 'external',
            description: 'Create a key, scope it to a store, rotate it without downtime, and revoke a leaked one.',
            knowledgeIds: [KB.API_KEYS],
            subformIds: [SF.INTEGRATION_HELP],
          },
          {
            id: 'cat-i-webhooks',
            name: 'Webhooks',
            type: 'item',
            audience: 'external',
            description: 'Subscribe to order events, verify the signature, and replay a delivery that your endpoint missed.',
            knowledgeIds: [KB.WEBHOOK_SETUP, KB.API_KEYS],
            subformIds: [SF.INTEGRATION_HELP, SF.STOREFRONT_BUG],
          },
          {
            id: 'cat-i-data-export',
            name: 'Data import & export',
            type: 'item',
            audience: 'external',
            description: 'Bulk exports, scheduled reports and a full account extract for a migration.',
            knowledgeIds: [KB.IMPORT_CATALOG, KB.API_KEYS],
            subformIds: [SF.INTEGRATION_HELP],
          },
        ],
      },
      {
        id: 'cat-s-problems-feedback',
        name: 'Problems & feedback',
        type: 'subcategory',
        audience: 'external',
        description: 'The intake side of external support — bugs, outages and the feature pipeline.',
        children: [
          {
            id: 'cat-i-report-bug',
            name: 'Report a problem',
            type: 'item',
            audience: 'external',
            popular: true,
            description: 'Checkout errors, missing orders, a theme that renders wrong on mobile. Include the store URL.',
            knowledgeIds: [KB.STOREFRONT_SETUP, KB.CONNECT_PAYMENTS],
            subformIds: [SF.STOREFRONT_BUG],
          },
          {
            id: 'cat-i-feature-request',
            name: 'Request a feature',
            type: 'item',
            audience: 'external',
            description: 'Goes to the product board, not to support. Customers can watch the request and get the release note.',
            knowledgeIds: [KB.WEBHOOK_SETUP],
            subformIds: [SF.FEATURE_REQUEST],
          },
          {
            id: 'cat-i-status-incidents',
            name: 'Status & incident updates',
            type: 'item',
            audience: 'both',
            description: 'The public status page, how incidents are communicated, and what the SLA credits are worth.',
            knowledgeIds: [KB.SLA_EXPLAINED, KB.ESCALATION_PATHS],
            subformIds: [SF.STOREFRONT_BUG],
          },
        ],
      },
    ],
  },
];
