/**
 * Products & Services catalog seed.
 *
 * Three levels, always: Product › Subcategory › Item. Items are LEAVES and the
 * only nodes that carry content — a product or a subcategory is navigation.
 *
 * Items do not OWN their content. They reference shared atoms:
 *     knowledgeIds -> `knowledge`   (the same article can be a lesson too)
 *     subformIds   -> `subforms`    (the same intake can hang off two items)
 * That indirection is what lets "Password Reset" appear under Accounts AND under
 * the Storefront without re-authoring anything, and what lets the Learning module
 * build a course out of catalog knowledge. See src/store/schema.js.
 *
 * Northwind Systems runs one catalog for two audiences: six internal products
 * for employees, and Northwind Storefront — the product customers actually buy —
 * for external customers. `audience` is per node, so a subcategory can be shared
 * by both ('both') even when its parent is internal.
 *
 * ------------------------------------------------------------------
 * THREE AUTHORING RULES, and they are what make this tree usable.
 *
 * 1. AN ITEM IS A FAULT, NOT A TOPIC. "Multi-factor code not arriving" is a
 *    situation somebody recognises as theirs. "Multi-factor authentication" is a
 *    subject, and a person with a problem cannot tell whether it is the one they
 *    are living. Name the symptom the person sees, not the cause behind it.
 *
 * 2. DENSITY. Every subcategory offers five to eight real choices. A tree that
 *    shows two or three options makes the person guess, and they guess wrong.
 *    Near-duplicates do not count — each item is a distinct situation.
 *
 * 3. "NOT LISTED" IS THE LAST OPTION AT EVERY LEVEL — an item at the end of
 *    every subcategory, a subcategory at the end of every product. That is how a
 *    catalog handles its long tail honestly instead of pretending the tree is
 *    complete. Those nodes carry the branch intake where one fits, so the
 *    promise ("read and routed by hand") has somewhere to land.
 *
 * Voice: terse, service-desk, sentence case. Descriptions are one line.
 * ------------------------------------------------------------------
 */

import { CAT, KB, SF, USR } from './ids.js';

export const CATALOG = [
  /* ================================================================== *
   * 1 — Accounts & Access
   * ================================================================== */
  {
    id: CAT.P_ACCOUNTS,
    name: 'Accounts & Access',
    type: 'product',
    audience: 'internal',
    ownerId: USR.EMMA,
    description: 'Sign-in, multi-factor, application access and everything that decides who can get into what.',
    children: [
      {
        id: 'cat-s-signin',
        name: 'Sign-in & passwords',
        type: 'subcategory',
        audience: 'internal',
        description: 'The single highest-volume topic on the service desk.',
        children: [
          {
            id: CAT.I_CANNOT_SIGN_IN,
            name: 'Cannot sign in',
            type: 'item',
            audience: 'internal',
            popular: true,
            fulfillment: 'Same day',
            description: 'The password is refused at the sign-in page, on a machine or an app that worked yesterday.',
            knowledgeIds: [KB.RESET_PASSWORD, KB.ACCOUNT_LOCKED],
            subformIds: [SF.REPORT_SIGNIN],
          },
          {
            /* Moved here from Identity & directory: this is where a person looks
             * when they are locked out. The id is untouched, so every reference
             * to it elsewhere in the seed still resolves. */
            id: 'cat-i-account-locked',
            name: 'Locked out after too many attempts',
            type: 'item',
            audience: 'internal',
            fulfillment: '1 hour',
            description: 'Repeated failed sign-ins, an expired contractor account, or a security hold after a phishing report.',
            knowledgeIds: [KB.ACCOUNT_LOCKED, KB.MFA_SETUP],
            subformIds: [SF.REPORT_SIGNIN],
          },
          {
            id: CAT.I_MFA,
            name: 'Multi-factor code not arriving',
            type: 'item',
            audience: 'internal',
            popular: true,
            fulfillment: '2 hours',
            description: 'The push never lands, the code is rejected, or the authenticator went with the old phone.',
            knowledgeIds: [KB.MFA_SETUP, KB.ACCOUNT_LOCKED],
            subformIds: [SF.MFA_RESET],
          },
          {
            id: 'cat-i-sso',
            name: 'Single sign-on loops back to login',
            type: 'item',
            audience: 'both',
            description: 'The app bounces between the Northwind sign-in and its own login screen, or asks for a separate password.',
            knowledgeIds: [KB.SSO_EXPLAINED, KB.RESET_PASSWORD],
            subformIds: [SF.REPORT_SIGNIN],
          },
          {
            id: 'cat-i-password-policy',
            name: 'Password change rejected',
            type: 'item',
            audience: 'internal',
            description: 'The new password will not save, or something still wants the old one hours after it changed.',
            knowledgeIds: [KB.RESET_PASSWORD, KB.SSO_EXPLAINED],
            subformIds: [SF.REPORT_SIGNIN],
          },
          {
            id: 'cat-i-passkey',
            name: 'Passkey or security key not recognised',
            type: 'item',
            audience: 'internal',
            description: 'The sign-in never offers the passkey, or the key reads as unregistered on a new machine.',
            knowledgeIds: [KB.MFA_SETUP, KB.SSO_EXPLAINED],
            subformIds: [SF.REPORT_SIGNIN],
          },
          {
            id: 'cat-i-signin-wrong-account',
            name: 'Signed in as the wrong account',
            type: 'item',
            audience: 'internal',
            description: 'The browser keeps resuming a personal or an old account, so everything shows the wrong data.',
            knowledgeIds: [KB.SSO_EXPLAINED],
            subformIds: [SF.REPORT_SIGNIN],
          },
          {
            id: 'cat-i-signin-not-listed',
            name: 'Not listed',
            type: 'item',
            audience: 'internal',
            description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.',
            knowledgeIds: [],
            subformIds: [SF.REPORT_SIGNIN],
          },
        ],
      },
      {
        id: 'cat-s-app-access',
        name: 'Application access',
        type: 'subcategory',
        audience: 'internal',
        description: 'Getting into an internal system, and losing the access you already had.',
        children: [
          {
            id: 'cat-i-request-app',
            name: 'No access to an application yet',
            type: 'item',
            audience: 'internal',
            popular: true,
            fulfillment: '1-2 business days',
            description: 'Salesforce, NetSuite, Looker, the data warehouse — anything that needs a manager approval before provisioning.',
            knowledgeIds: [KB.SSO_EXPLAINED, KB.APPROVAL_THRESHOLDS],
            subformIds: [SF.REQUEST_ACCESS],
          },
          {
            id: 'cat-i-access-denied',
            name: 'Access denied inside an app you already use',
            type: 'item',
            audience: 'internal',
            description: 'Signed in fine, but a tab, record or report answers that you are not permitted.',
            knowledgeIds: [KB.SSO_EXPLAINED],
            subformIds: [SF.REQUEST_ACCESS],
          },
          {
            id: 'cat-i-access-lost',
            name: 'Access disappeared after a role change',
            type: 'item',
            audience: 'internal',
            description: 'Permissions that worked last week are gone since a move, a promotion or a new manager.',
            knowledgeIds: [KB.SSO_EXPLAINED, KB.APPROVAL_THRESHOLDS],
            subformIds: [SF.REQUEST_ACCESS],
          },
          {
            id: 'cat-i-shared-mailbox-access',
            name: 'Cannot open a shared mailbox or group',
            type: 'item',
            audience: 'internal',
            fulfillment: '1 business day',
            description: 'support@ or billing@ is missing from Outlook, or send-as is refused when you reply.',
            knowledgeIds: [KB.EMAIL_SIGNATURE],
            subformIds: [SF.REQUEST_ACCESS, SF.DISTRIBUTION_LIST],
          },
          {
            id: 'cat-i-elevated-rights',
            name: 'Blocked without admin rights',
            type: 'item',
            audience: 'internal',
            fulfillment: '2 business days',
            description: 'An install, a production console or a break-glass account. Always time-boxed and always approved.',
            knowledgeIds: [KB.APPROVAL_THRESHOLDS, KB.CHANGE_PROCESS],
            subformIds: [SF.REQUEST_ACCESS],
          },
          {
            id: 'cat-i-access-approval-stuck',
            name: 'Access request stuck waiting for approval',
            type: 'item',
            audience: 'internal',
            description: 'The request is sitting with an approver who has not acted, or went to the wrong one entirely.',
            knowledgeIds: [KB.APPROVAL_THRESHOLDS],
            subformIds: [SF.REQUEST_ACCESS],
          },
          {
            id: 'cat-i-app-access-not-listed',
            name: 'Not listed',
            type: 'item',
            audience: 'internal',
            description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.',
            knowledgeIds: [],
            subformIds: [SF.REQUEST_ACCESS],
          },
        ],
      },
      {
        id: 'cat-s-identity',
        name: 'Identity & directory',
        type: 'subcategory',
        audience: 'internal',
        description: 'The records everything else resolves against — names, managers, contractors.',
        children: [
          {
            id: 'cat-i-directory-profile',
            name: 'Name or title wrong in the directory',
            type: 'item',
            audience: 'internal',
            fulfillment: '1 business day',
            description: 'A legal or preferred name, job title, manager, desk or pronouns that never caught up.',
            knowledgeIds: [KB.EMAIL_SIGNATURE, KB.ONBOARDING_CHECKLIST],
            subformIds: [SF.REQUEST_ACCESS],
          },
          {
            id: 'cat-i-name-change',
            name: 'Name change not reflected in mail or sign-in',
            type: 'item',
            audience: 'internal',
            description: 'The directory shows the new name, but mail, Teams and the sign-in page still show the old one.',
            knowledgeIds: [KB.EMAIL_SIGNATURE, KB.SSO_EXPLAINED],
            subformIds: [SF.EMAIL_PROBLEM],
          },
          {
            id: 'cat-i-contractor-account',
            name: 'Contractor account expired or missing',
            type: 'item',
            audience: 'internal',
            fulfillment: '3 business days',
            description: 'A partner cannot sign in because the end date passed, or the account was never created.',
            knowledgeIds: [KB.SSO_EXPLAINED, KB.ONBOARDING_CHECKLIST],
            subformIds: [SF.NEW_HIRE, SF.REQUEST_ACCESS],
          },
          {
            id: 'cat-i-wrong-manager',
            name: 'Approvals going to the wrong manager',
            type: 'item',
            audience: 'internal',
            description: 'Requests land with a previous manager because the reporting chain is stale.',
            knowledgeIds: [KB.APPROVAL_THRESHOLDS, KB.ONBOARDING_CHECKLIST],
            subformIds: [SF.REQUEST_ACCESS],
          },
          {
            id: 'cat-i-duplicate-account',
            name: 'Duplicate or leftover account',
            type: 'item',
            audience: 'internal',
            description: 'Two records for one person, or an old account still live after a rehire.',
            knowledgeIds: [KB.ACCOUNT_LOCKED, KB.SSO_EXPLAINED],
            subformIds: [SF.REPORT_SIGNIN],
          },
          {
            id: 'cat-i-missing-from-group',
            name: 'Missing from a team or group',
            type: 'item',
            audience: 'internal',
            description: 'The person is absent from the directory group that drives access and mailing lists.',
            knowledgeIds: [KB.EMAIL_SIGNATURE, KB.SSO_EXPLAINED],
            subformIds: [SF.DISTRIBUTION_LIST, SF.REQUEST_ACCESS],
          },
          {
            id: 'cat-i-identity-not-listed',
            name: 'Not listed',
            type: 'item',
            audience: 'internal',
            description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.',
            knowledgeIds: [],
            subformIds: [SF.REQUEST_ACCESS],
          },
        ],
      },
      {
        id: 'cat-s-accounts-not-listed',
        name: 'Not listed',
        type: 'subcategory',
        audience: 'internal',
        description: 'Something about accounts or access that none of the above covers. Read and routed by hand.',
        children: [
          {
            id: 'cat-i-accounts-not-listed',
            name: 'Not listed',
            type: 'item',
            audience: 'internal',
            description: 'Describe the problem in your own words — a person reads it and routes it by hand.',
            knowledgeIds: [],
            subformIds: [SF.REPORT_SIGNIN],
          },
        ],
      },
    ],
  },

  /* ================================================================== *
   * 2 — Email & Calendar
   * ================================================================== */
  {
    id: CAT.P_EMAIL,
    name: 'Email & Calendar',
    type: 'product',
    audience: 'internal',
    ownerId: USR.EMMA,
    description: 'Mail delivery, mobile setup, distribution lists and the meeting-room booking system.',
    children: [
      {
        id: 'cat-s-mail-delivery',
        name: 'Mailbox & delivery',
        type: 'subcategory',
        audience: 'internal',
        description: 'Mail that did not arrive, or arrived where it should not have.',
        children: [
          {
            id: 'cat-i-email-not-working',
            name: 'Email not sending or receiving',
            type: 'item',
            audience: 'internal',
            popular: true,
            fulfillment: 'Same day',
            description: 'Messages stuck in the outbox, or a mailbox that has stopped syncing in either direction.',
            knowledgeIds: [KB.SPAM_QUARANTINE, KB.EMAIL_ON_PHONE],
            subformIds: [SF.EMAIL_PROBLEM],
          },
          {
            id: 'cat-i-quarantine',
            name: 'Message held as spam',
            type: 'item',
            audience: 'internal',
            description: 'A message you were expecting is sitting in quarantine instead of your inbox.',
            knowledgeIds: [KB.SPAM_QUARANTINE],
            subformIds: [SF.EMAIL_PROBLEM],
          },
          {
            id: 'cat-i-email-bounce',
            name: 'Message bounced back',
            type: 'item',
            audience: 'internal',
            description: 'A single message returned undelivered, with a failure notice from the recipient’s server.',
            knowledgeIds: [KB.SPAM_QUARANTINE],
            subformIds: [SF.EMAIL_PROBLEM],
          },
          {
            id: 'cat-i-email-missing',
            name: 'Mail missing or deleted',
            type: 'item',
            audience: 'internal',
            description: 'A folder that emptied itself, a rule filing mail somewhere unexpected, or a message that vanished.',
            knowledgeIds: [KB.SPAM_QUARANTINE, KB.EMAIL_SIGNATURE],
            subformIds: [SF.EMAIL_PROBLEM],
          },
          {
            id: 'cat-i-mailbox-storage',
            name: 'Mailbox full',
            type: 'item',
            audience: 'internal',
            description: 'Over-quota warnings, or new mail stops arriving because the mailbox is at its limit.',
            knowledgeIds: [KB.SPAM_QUARANTINE, KB.EMAIL_SIGNATURE],
            subformIds: [SF.EMAIL_PROBLEM],
          },
          {
            id: 'cat-i-phishing',
            name: 'Suspicious or phishing email',
            type: 'item',
            audience: 'internal',
            fulfillment: 'Immediate',
            description: 'A message asking for credentials or a payment. Report it here, do not forward it on.',
            knowledgeIds: [KB.SPAM_QUARANTINE, KB.ACCOUNT_LOCKED],
            subformIds: [SF.EMAIL_PROBLEM],
          },
          {
            id: 'cat-i-mail-delivery-not-listed',
            name: 'Not listed',
            type: 'item',
            audience: 'internal',
            description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.',
            knowledgeIds: [],
            subformIds: [SF.EMAIL_PROBLEM],
          },
        ],
      },
      {
        id: 'cat-s-mail-clients',
        name: 'Mobile & mail clients',
        type: 'subcategory',
        audience: 'internal',
        description: 'Getting mail onto the device the person actually uses.',
        children: [
          {
            id: 'cat-i-email-on-phone',
            name: 'Mail not syncing on a phone or tablet',
            type: 'item',
            audience: 'internal',
            popular: true,
            description: 'The profile will not install, the app keeps asking to sign in, or new mail stops arriving on mobile.',
            knowledgeIds: [KB.EMAIL_ON_PHONE, KB.MFA_SETUP],
            subformIds: [SF.EMAIL_PROBLEM],
          },
          {
            id: 'cat-i-mobile-policy',
            name: 'Phone blocked by the device policy',
            type: 'item',
            audience: 'internal',
            description: 'Mail refuses to connect until the phone is enrolled or a passcode is set.',
            knowledgeIds: [KB.EMAIL_ON_PHONE, KB.MFA_SETUP],
            subformIds: [SF.EMAIL_PROBLEM],
          },
          {
            id: 'cat-i-desktop-mail-client',
            name: 'Mail profile will not set up on a new machine',
            type: 'item',
            audience: 'internal',
            description: 'Outlook or Apple Mail fails to create the profile, or offline mail never finishes downloading.',
            knowledgeIds: [KB.EMAIL_ON_PHONE, KB.INSTALL_SOFTWARE],
            subformIds: [SF.EMAIL_PROBLEM, SF.SOFTWARE_REQUEST],
          },
          {
            id: 'cat-i-calendar-sync',
            name: 'Calendar not syncing between devices',
            type: 'item',
            audience: 'internal',
            description: 'Events missing on the phone, or an invite you accepted that never appears.',
            knowledgeIds: [KB.EMAIL_ON_PHONE],
            subformIds: [SF.EMAIL_PROBLEM],
          },
          {
            id: 'cat-i-email-signature',
            name: 'Signature missing or wrong',
            type: 'item',
            audience: 'internal',
            description: 'The approved block never applied, or replies go out with a title from two roles ago.',
            knowledgeIds: [KB.EMAIL_SIGNATURE],
            subformIds: [SF.EMAIL_PROBLEM],
          },
          {
            id: 'cat-i-mail-search',
            name: 'Search returns nothing in the mail client',
            type: 'item',
            audience: 'internal',
            description: 'A message you can see in the folder does not come back from search.',
            knowledgeIds: [],
            subformIds: [SF.EMAIL_PROBLEM],
          },
          {
            id: 'cat-i-mail-clients-not-listed',
            name: 'Not listed',
            type: 'item',
            audience: 'internal',
            description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.',
            knowledgeIds: [],
            subformIds: [SF.EMAIL_PROBLEM],
          },
        ],
      },
      {
        id: 'cat-s-groups-calendars',
        name: 'Groups & calendars',
        type: 'subcategory',
        audience: 'internal',
        description: 'Anything addressed to more than one person.',
        children: [
          {
            id: 'cat-i-distribution-list',
            name: 'Distribution list missing people or refusing senders',
            type: 'item',
            audience: 'internal',
            fulfillment: '1 business day',
            description: 'Mail to a team list skips members, or a sender outside Northwind is bounced.',
            knowledgeIds: [KB.EMAIL_SIGNATURE, KB.APPROVAL_THRESHOLDS],
            subformIds: [SF.DISTRIBUTION_LIST],
          },
          {
            id: 'cat-i-shared-calendar',
            name: 'Cannot see a shared calendar',
            type: 'item',
            audience: 'internal',
            description: 'A colleague shared a calendar and it opens empty, greyed out, or not at all.',
            knowledgeIds: [KB.EMAIL_SIGNATURE],
            subformIds: [SF.EMAIL_PROBLEM],
          },
          {
            id: 'cat-i-invite-missing',
            name: 'Meeting invite never arrived',
            type: 'item',
            audience: 'internal',
            description: 'An invite sent to a list or an external guest that nobody received.',
            knowledgeIds: [KB.SPAM_QUARANTINE],
            subformIds: [SF.EMAIL_PROBLEM],
          },
          {
            id: 'cat-i-out-of-office',
            name: 'Out-of-office or delegate not working',
            type: 'item',
            audience: 'internal',
            description: 'Automatic replies never fire, or a delegate cannot send on your behalf.',
            knowledgeIds: [KB.EMAIL_SIGNATURE],
            subformIds: [SF.EMAIL_PROBLEM],
          },
          {
            id: 'cat-i-room-booking',
            name: 'Room shows free but is taken',
            type: 'item',
            audience: 'internal',
            description: 'Room calendars out of step with the panel at the door, or a booking that will not release.',
            knowledgeIds: [KB.EMAIL_SIGNATURE],
            subformIds: [SF.FACILITIES_ISSUE],
          },
          {
            id: 'cat-i-room-kit',
            name: 'Video kit in the room not working',
            type: 'item',
            audience: 'internal',
            fulfillment: 'Same day',
            description: 'No display, no camera, or the room will not join the meeting on the screen.',
            knowledgeIds: [],
            subformIds: [SF.FACILITIES_ISSUE],
          },
          {
            id: 'cat-i-groups-not-listed',
            name: 'Not listed',
            type: 'item',
            audience: 'internal',
            description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.',
            knowledgeIds: [],
            subformIds: [SF.EMAIL_PROBLEM],
          },
        ],
      },
      {
        id: 'cat-s-email-not-listed',
        name: 'Not listed',
        type: 'subcategory',
        audience: 'internal',
        description: 'Something about mail or calendars that none of the above covers. Read and routed by hand.',
        children: [
          {
            id: 'cat-i-email-not-listed',
            name: 'Not listed',
            type: 'item',
            audience: 'internal',
            description: 'Describe the problem in your own words — a person reads it and routes it by hand.',
            knowledgeIds: [],
            subformIds: [SF.EMAIL_PROBLEM],
          },
        ],
      },
    ],
  },

  /* ================================================================== *
   * 3 — Devices & Hardware
   * ================================================================== */
  {
    id: CAT.P_DEVICES,
    name: 'Devices & Hardware',
    type: 'product',
    audience: 'internal',
    ownerId: USR.JAMES,
    description: 'Laptops, peripherals, phones and the return/repair loop. Every item here can link to an asset record.',
    children: [
      {
        id: 'cat-s-computers',
        name: 'Laptops & desktops',
        type: 'subcategory',
        audience: 'internal',
        description: 'The primary machine. Refresh cycle is 36 months.',
        children: [
          {
            id: CAT.I_LAPTOP_ISSUE,
            name: 'Laptop not powering on',
            type: 'item',
            audience: 'internal',
            popular: true,
            fulfillment: 'Same day triage',
            description: 'Dead on the charger, no light at all, or it shuts down the moment it is unplugged.',
            knowledgeIds: [KB.SCREEN_FLICKER, KB.LAPTOP_SETUP],
            subformIds: [SF.LAPTOP_REPAIR],
          },
          {
            id: 'cat-i-laptop-performance',
            name: 'Laptop slow or freezing',
            type: 'item',
            audience: 'internal',
            popular: true,
            description: 'Slow to wake, fans at full tilt, everything lagging an hour into the day.',
            knowledgeIds: [KB.LAPTOP_SETUP],
            subformIds: [SF.LAPTOP_REPAIR],
          },
          {
            id: 'cat-i-laptop-screen',
            name: 'Laptop screen flickering or black',
            type: 'item',
            audience: 'internal',
            description: 'Flickering, dead pixels, a cracked panel, or a display that stays black on wake.',
            knowledgeIds: [KB.SCREEN_FLICKER],
            subformIds: [SF.LAPTOP_REPAIR],
          },
          {
            id: 'cat-i-laptop-battery',
            name: 'Battery drains or will not charge',
            type: 'item',
            audience: 'internal',
            fulfillment: 'Same day triage',
            description: 'An hour off the charger, a swollen case, or a charger the machine ignores entirely.',
            knowledgeIds: [],
            subformIds: [SF.LAPTOP_REPAIR],
          },
          {
            id: 'cat-i-wifi',
            name: 'Wi-Fi or internet dropping',
            type: 'item',
            audience: 'internal',
            description: 'Drops out around the office, will not join at home, or connects with no traffic behind it.',
            knowledgeIds: [],
            subformIds: [SF.LAPTOP_REPAIR],
          },
          {
            id: 'cat-i-machine-setup',
            name: 'New machine will not finish setup',
            type: 'item',
            audience: 'internal',
            description: 'Enrolment stalls, encryption never completes, or the VPN profile is missing after first boot.',
            knowledgeIds: [KB.LAPTOP_SETUP, KB.INSTALL_SOFTWARE, KB.MFA_SETUP],
            subformIds: [SF.NEW_HARDWARE],
          },
          {
            id: CAT.I_NEW_LAPTOP,
            name: 'Laptop needs replacing',
            type: 'item',
            audience: 'internal',
            popular: true,
            fulfillment: '5-7 business days',
            description: 'Past the 36-month cycle or beyond economical repair. Anything above the standard build needs manager approval.',
            knowledgeIds: [KB.LAPTOP_SETUP, KB.APPROVAL_THRESHOLDS],
            subformIds: [SF.NEW_HARDWARE],
          },
          {
            id: 'cat-i-computers-not-listed',
            name: 'Not listed',
            type: 'item',
            audience: 'internal',
            description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.',
            knowledgeIds: [],
            subformIds: [SF.LAPTOP_REPAIR],
          },
        ],
      },
      {
        id: 'cat-s-peripherals',
        name: 'Peripherals & accessories',
        type: 'subcategory',
        audience: 'internal',
        description: 'Everything that plugs into the primary machine.',
        children: [
          {
            id: 'cat-i-monitor',
            name: 'Monitor or dock not detected',
            type: 'item',
            audience: 'internal',
            fulfillment: '3-5 business days',
            description: 'Nothing on the second screen, a dock that drops out, or only one of two panels lighting up.',
            knowledgeIds: [KB.SCREEN_FLICKER, KB.REQUEST_MONITOR],
            subformIds: [SF.LAPTOP_REPAIR, SF.NEW_HARDWARE],
          },
          {
            id: 'cat-i-desk-accessories',
            name: 'Keyboard, mouse or headset not working',
            type: 'item',
            audience: 'internal',
            fulfillment: '3-5 business days',
            description: 'Dead batteries, a dongle that will not pair, or a mic nobody on the call can hear.',
            knowledgeIds: [KB.REQUEST_MONITOR],
            subformIds: [SF.NEW_HARDWARE],
          },
          {
            id: 'cat-i-printing',
            name: 'Printer not printing',
            type: 'item',
            audience: 'internal',
            description: 'Jobs queue and never come out, the printer is missing from the list, or scan-to-share fails.',
            knowledgeIds: [KB.INSTALL_SOFTWARE],
            subformIds: [SF.FACILITIES_ISSUE],
          },
          {
            id: 'cat-i-webcam',
            name: 'Camera or microphone not detected',
            type: 'item',
            audience: 'internal',
            description: 'Calls open with no video, or the wrong device is picked every single time.',
            knowledgeIds: [],
            subformIds: [SF.LAPTOP_REPAIR],
          },
          {
            id: 'cat-i-adapters',
            name: 'Missing cable, dongle or adapter',
            type: 'item',
            audience: 'internal',
            fulfillment: '3-5 business days',
            description: 'No way to reach the projector, the dock or a second display.',
            knowledgeIds: [KB.REQUEST_MONITOR],
            subformIds: [SF.NEW_HARDWARE],
          },
          {
            id: 'cat-i-peripheral-worn',
            name: 'Accessory damaged or worn out',
            type: 'item',
            audience: 'internal',
            description: 'A frayed cable, a cracked case, a headset band that finally snapped.',
            knowledgeIds: [KB.REQUEST_MONITOR, KB.RETURN_EQUIPMENT],
            subformIds: [SF.NEW_HARDWARE, SF.RETURN_HARDWARE],
          },
          {
            id: 'cat-i-peripherals-not-listed',
            name: 'Not listed',
            type: 'item',
            audience: 'internal',
            description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.',
            knowledgeIds: [],
            subformIds: [SF.LAPTOP_REPAIR],
          },
        ],
      },
      {
        id: 'cat-s-mobile',
        name: 'Mobile devices',
        type: 'subcategory',
        audience: 'internal',
        description: 'Company phones and tablets, and the incident path when one goes missing.',
        children: [
          {
            id: 'cat-i-lost-device',
            name: 'Lost or stolen device',
            type: 'item',
            audience: 'internal',
            popular: true,
            fulfillment: 'Immediate',
            description: 'Remote wipe, credential rotation and the security report. Raise this before anything else.',
            knowledgeIds: [KB.ACCOUNT_LOCKED, KB.MFA_SETUP, KB.RETURN_EQUIPMENT],
            subformIds: [SF.LAPTOP_REPAIR, SF.REPORT_SIGNIN],
          },
          {
            id: 'cat-i-phone-damaged',
            name: 'Phone cracked or will not charge',
            type: 'item',
            audience: 'internal',
            description: 'Physical damage, or a handset that no longer holds charge through a shift.',
            knowledgeIds: [KB.RETURN_EQUIPMENT],
            subformIds: [SF.LAPTOP_REPAIR, SF.RETURN_HARDWARE],
          },
          {
            id: 'cat-i-phone-service',
            name: 'No mobile signal or data',
            type: 'item',
            audience: 'internal',
            description: 'Calls fail, data stops at the border, or the SIM reads as unregistered.',
            knowledgeIds: [],
            subformIds: [SF.LAPTOP_REPAIR],
          },
          {
            id: 'cat-i-mdm-enrolment',
            name: 'Phone will not enrol in device management',
            type: 'item',
            audience: 'internal',
            description: 'Enrolment fails part-way, or the profile disappeared after an OS update.',
            knowledgeIds: [KB.EMAIL_ON_PHONE, KB.MFA_SETUP],
            subformIds: [SF.LAPTOP_REPAIR],
          },
          {
            id: 'cat-i-roaming',
            name: 'Travelling and roaming is not enabled',
            type: 'item',
            audience: 'internal',
            fulfillment: '2 business days',
            description: 'A trip that needs the international add-on before the person leaves.',
            knowledgeIds: [KB.APPROVAL_THRESHOLDS],
            subformIds: [SF.NEW_HARDWARE],
          },
          {
            id: 'cat-i-company-phone',
            name: 'No company phone or tablet yet',
            type: 'item',
            audience: 'internal',
            fulfillment: '5 business days',
            description: 'Eligible roles, plan tiers, and the international-roaming add-on for the field team.',
            knowledgeIds: [KB.EMAIL_ON_PHONE, KB.APPROVAL_THRESHOLDS],
            subformIds: [SF.NEW_HARDWARE],
          },
          {
            id: 'cat-i-mobile-not-listed',
            name: 'Not listed',
            type: 'item',
            audience: 'internal',
            description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.',
            knowledgeIds: [],
            subformIds: [SF.LAPTOP_REPAIR],
          },
        ],
      },
      {
        id: 'cat-s-returns',
        name: 'Returns & repairs',
        type: 'subcategory',
        audience: 'internal',
        description: 'The other end of the asset lifecycle — the part most catalogs forget.',
        children: [
          {
            id: 'cat-i-repair-warranty',
            name: 'Device needs repair or a warranty claim',
            type: 'item',
            audience: 'internal',
            fulfillment: '7-10 business days',
            description: 'Depot repair, an on-site vendor visit, or an accidental-damage claim against the fleet contract.',
            knowledgeIds: [KB.SCREEN_FLICKER, KB.RETURN_EQUIPMENT],
            subformIds: [SF.LAPTOP_REPAIR, SF.RETURN_HARDWARE],
          },
          {
            id: 'cat-i-loaner',
            name: 'Nothing to work on while a machine is away',
            type: 'item',
            audience: 'internal',
            fulfillment: 'Same day',
            description: 'A short-term laptop or hotspot while a machine is in repair or a new hire waits on stock.',
            knowledgeIds: [KB.LAPTOP_SETUP, KB.RETURN_EQUIPMENT],
            subformIds: [SF.NEW_HARDWARE, SF.RETURN_HARDWARE],
          },
          {
            id: 'cat-i-return-equipment',
            name: 'Equipment to return',
            type: 'item',
            audience: 'internal',
            fulfillment: '5 days from leave date',
            description: 'Prepaid label, wipe confirmation and the asset record hand-back. Required within 5 days of a leave date.',
            knowledgeIds: [KB.RETURN_EQUIPMENT, KB.ONBOARDING_CHECKLIST],
            subformIds: [SF.RETURN_HARDWARE],
          },
          {
            id: 'cat-i-return-label',
            name: 'Return label or collection never arrived',
            type: 'item',
            audience: 'internal',
            description: 'The prepaid label did not turn up, or the courier missed the collection window.',
            knowledgeIds: [KB.RETURN_EQUIPMENT],
            subformIds: [SF.RETURN_HARDWARE],
          },
          {
            id: 'cat-i-asset-record',
            name: 'Asset record shows the wrong owner',
            type: 'item',
            audience: 'internal',
            description: 'Kit assigned to someone who handed it back, or a machine that was never booked in.',
            knowledgeIds: [KB.RETURN_EQUIPMENT, KB.ONBOARDING_CHECKLIST],
            subformIds: [SF.RETURN_HARDWARE],
          },
          {
            id: 'cat-i-disposal',
            name: 'Old kit needs wiping and disposal',
            type: 'item',
            audience: 'internal',
            description: 'End-of-life hardware that must be wiped and certified before it leaves the building.',
            knowledgeIds: [KB.RETURN_EQUIPMENT],
            subformIds: [SF.RETURN_HARDWARE],
          },
          {
            id: 'cat-i-returns-not-listed',
            name: 'Not listed',
            type: 'item',
            audience: 'internal',
            description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.',
            knowledgeIds: [],
            subformIds: [SF.RETURN_HARDWARE],
          },
        ],
      },
      {
        id: 'cat-s-devices-not-listed',
        name: 'Not listed',
        type: 'subcategory',
        audience: 'internal',
        description: 'Something about a device that none of the above covers. Read and routed by hand.',
        children: [
          {
            id: 'cat-i-devices-not-listed',
            name: 'Not listed',
            type: 'item',
            audience: 'internal',
            description: 'Describe the problem in your own words — a person reads it and routes it by hand.',
            knowledgeIds: [],
            subformIds: [SF.LAPTOP_REPAIR],
          },
        ],
      },
    ],
  },

  /* ================================================================== *
   * 4 — Application & Software
   *
   * THE BROKEN-APP BRANCH. Subcategory is the application, item is the fault,
   * because that is how a person arrives: "Outlook keeps asking for my
   * password", never "email". Buying, renewing and licence compliance for the
   * same applications live in Software & Licensing (product 5) — both product
   * descriptions state the split, because two software products confuse people
   * unless somebody says out loud which is which.
   *
   * The product id is a literal rather than an entry in CAT. ids.js is for ids
   * that cross a domain boundary and nothing outside the catalog references this
   * product yet; promote it the day another seed file points at it.
   *
   * KNOWN GAP, and it is not cosmetic. There is no general "this application is
   * broken" subform in forms.js — the closest internal intakes are sign-in,
   * email, laptop-repair and software-request, and none of them fits a Teams
   * call with no audio. So the faults below that carry neither an atom nor an
   * intake render in the portal as "Reference only — this service has no request
   * form attached", which flatly contradicts what their own "Not listed" text
   * promises. Attaching a wrong-shaped form would hide that; it would not fix
   * it. THE FIX IS ONE SUBFORM IN forms.js: an application-fault intake routed
   * to Q.IT (which app, what happens, when it started, screenshot), then hung
   * off every item here that is currently formless. Until then this branch
   * deflects and browses but cannot be raised.
   * ================================================================== */
  {
    id: 'cat-p-applications',
    name: 'Application & Software',
    type: 'product',
    audience: 'internal',
    ownerId: USR.EMMA,
    description: 'An application you already have is broken — will not open, will not sign in, or lost your work. Buying and renewing it lives in Software & Licensing.',
    children: [
      {
        id: 'cat-s-m365',
        name: 'Microsoft 365',
        type: 'subcategory',
        audience: 'internal',
        description: 'Outlook, Teams, OneDrive, Word, Excel and Copilot. Mail that is not arriving at all belongs in Email & Calendar.',
        children: [
          {
            id: 'cat-i-m365-outlook-password',
            name: 'Outlook keeps asking for a password',
            type: 'item',
            audience: 'internal',
            popular: true,
            fulfillment: 'Same day',
            description: 'The prompt returns every few minutes even after the password is accepted.',
            knowledgeIds: [KB.RESET_PASSWORD, KB.SSO_EXPLAINED],
            subformIds: [SF.REPORT_SIGNIN],
          },
          {
            id: 'cat-i-m365-teams-call',
            name: 'Teams call has no sound or video',
            type: 'item',
            audience: 'internal',
            popular: true,
            description: 'Nobody can hear you, the camera never starts, or a screen share shows a black window.',
            knowledgeIds: [],
            subformIds: [],
          },
          {
            id: 'cat-i-m365-onedrive-sync',
            name: 'OneDrive not syncing',
            type: 'item',
            audience: 'internal',
            popular: true,
            description: 'The sync icon spins forever, or a file saved this morning is not on the other machine.',
            knowledgeIds: [],
            subformIds: [],
          },
          {
            id: 'cat-i-m365-files-missing',
            name: 'Files missing or deleted from SharePoint',
            type: 'item',
            audience: 'internal',
            fulfillment: 'Same day',
            description: 'A folder that emptied, a document nobody admits to moving, or a library that vanished from a site.',
            knowledgeIds: [],
            subformIds: [],
          },
          {
            id: 'cat-i-m365-permissions',
            name: 'No permission to a file or site',
            type: 'item',
            audience: 'internal',
            description: 'A document opens read-only, or a SharePoint site answers that you do not have permission.',
            knowledgeIds: [KB.SSO_EXPLAINED],
            subformIds: [SF.REQUEST_ACCESS],
          },
          {
            id: 'cat-i-m365-office-crash',
            name: 'Word or Excel crashes or loses work',
            type: 'item',
            audience: 'internal',
            description: 'The app closes mid-edit, a file will not open, or autosave lost the last hour.',
            knowledgeIds: [],
            subformIds: [],
          },
          {
            id: 'cat-i-m365-copilot',
            name: 'Copilot missing or refusing to answer',
            type: 'item',
            audience: 'internal',
            description: 'The Copilot button is not there, or it replies that it cannot reach your files.',
            knowledgeIds: [KB.LICENSE_POLICY],
            subformIds: [SF.SOFTWARE_REQUEST],
          },
          {
            id: 'cat-i-m365-not-listed',
            name: 'Not listed',
            type: 'item',
            audience: 'internal',
            description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.',
            knowledgeIds: [],
            subformIds: [],
          },
        ],
      },
      {
        id: 'cat-s-crm',
        name: 'Salesforce & CRM',
        type: 'subcategory',
        audience: 'internal',
        description: 'The revenue team’s record of record, and the tools that read from it.',
        children: [
          {
            id: 'cat-i-crm-signin',
            name: 'Cannot sign in to Salesforce',
            type: 'item',
            audience: 'internal',
            popular: true,
            fulfillment: 'Same day',
            description: 'The login is refused, the SSO tile does nothing, or the org asks for a separate password.',
            knowledgeIds: [KB.SSO_EXPLAINED, KB.RESET_PASSWORD],
            subformIds: [SF.REPORT_SIGNIN],
          },
          {
            id: 'cat-i-crm-permissions',
            name: 'Record or dashboard hidden or read-only',
            type: 'item',
            audience: 'internal',
            description: 'Signed in fine, but an account, opportunity or dashboard is hidden or will not take an edit.',
            knowledgeIds: [KB.SSO_EXPLAINED, KB.APPROVAL_THRESHOLDS],
            subformIds: [SF.REQUEST_ACCESS],
          },
          {
            id: 'cat-i-crm-save',
            name: 'Cannot save a record',
            type: 'item',
            audience: 'internal',
            description: 'A validation rule blocks the save, or the page errors the moment you submit.',
            knowledgeIds: [],
            subformIds: [],
          },
          {
            id: 'cat-i-crm-sync',
            name: 'Records not arriving from another system',
            type: 'item',
            audience: 'internal',
            description: 'Orders, cases or contacts that stopped appearing in Salesforce overnight.',
            knowledgeIds: [KB.API_KEYS],
            subformIds: [],
          },
          {
            id: 'cat-i-crm-report',
            name: 'Report or dashboard shows the wrong numbers',
            type: 'item',
            audience: 'internal',
            description: 'Totals that do not match the source, or a dashboard frozen on last week.',
            knowledgeIds: [],
            subformIds: [],
          },
          {
            id: 'cat-i-crm-slow',
            name: 'Salesforce slow or timing out',
            type: 'item',
            audience: 'internal',
            description: 'List views take a minute to open, or a page times out in the middle of an edit.',
            knowledgeIds: [],
            subformIds: [],
          },
          {
            id: 'cat-i-crm-not-listed',
            name: 'Not listed',
            type: 'item',
            audience: 'internal',
            description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.',
            knowledgeIds: [],
            subformIds: [],
          },
        ],
      },
      {
        id: 'cat-s-creative-cloud',
        name: 'Adobe Creative Cloud',
        type: 'subcategory',
        audience: 'internal',
        description: 'Design and video tooling. A seat you need but do not have is a licensing request, not a fault.',
        children: [
          {
            id: 'cat-i-cc-activation',
            name: 'Creative Cloud will not activate',
            type: 'item',
            audience: 'internal',
            popular: true,
            fulfillment: '2 business days',
            description: 'The app says the licence expired, or sign-in loops without ever activating.',
            knowledgeIds: [KB.ADOBE_ACTIVATION, KB.LICENSE_POLICY],
            subformIds: [SF.SOFTWARE_REQUEST],
          },
          {
            id: 'cat-i-cc-crash',
            name: 'Photoshop or Illustrator crashes on launch',
            type: 'item',
            audience: 'internal',
            description: 'The splash screen appears and the app closes before a document ever opens.',
            knowledgeIds: [],
            subformIds: [],
          },
          {
            id: 'cat-i-cc-fonts',
            name: 'Fonts missing from a document',
            type: 'item',
            audience: 'internal',
            description: 'Type falls back to a substitute, or an activated font never finishes downloading.',
            knowledgeIds: [],
            subformIds: [],
          },
          {
            id: 'cat-i-cc-cloud-files',
            name: 'Cloud documents not syncing',
            type: 'item',
            audience: 'internal',
            description: 'Work saved on one machine is missing on another, or a file is stuck uploading.',
            knowledgeIds: [],
            subformIds: [],
          },
          {
            id: 'cat-i-cc-export',
            name: 'Export or render fails',
            type: 'item',
            audience: 'internal',
            description: 'A render that never finishes, or an export that errors within sight of the end.',
            knowledgeIds: [],
            subformIds: [],
          },
          {
            /* No "seat not assigned" item here. This subcategory says a seat you
             * do not have is a licensing request, and then has to mean it —
             * that request is cat-i-adobe under Software & Licensing. */
            id: 'cat-i-cc-acrobat',
            name: 'Acrobat will not open or edit a PDF',
            type: 'item',
            audience: 'internal',
            description: 'A PDF that opens blank, refuses an edit, or will not take a signature.',
            knowledgeIds: [],
            subformIds: [],
          },
          {
            id: 'cat-i-cc-not-listed',
            name: 'Not listed',
            type: 'item',
            audience: 'internal',
            description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.',
            knowledgeIds: [],
            subformIds: [],
          },
        ],
      },
      {
        id: 'cat-s-collab',
        name: 'Slack & Zoom',
        type: 'subcategory',
        audience: 'internal',
        description: 'Chat and meetings. When these are down, everything else looks down too.',
        children: [
          {
            id: 'cat-i-collab-signin',
            name: 'Cannot sign in to the Slack workspace',
            type: 'item',
            audience: 'internal',
            fulfillment: 'Same day',
            description: 'The invite expired, the workspace is not listed, or SSO refuses the account.',
            knowledgeIds: [KB.SSO_EXPLAINED],
            subformIds: [SF.REPORT_SIGNIN],
          },
          {
            id: 'cat-i-collab-audio',
            name: 'Zoom or Slack call has no sound or video',
            type: 'item',
            audience: 'internal',
            popular: true,
            description: 'The wrong microphone is selected, or the camera is held by another app.',
            knowledgeIds: [],
            subformIds: [],
          },
          {
            id: 'cat-i-collab-share',
            name: 'Screen share not working',
            type: 'item',
            audience: 'internal',
            description: 'The share button greys out, or attendees see a black rectangle where the screen should be.',
            knowledgeIds: [],
            subformIds: [],
          },
          {
            id: 'cat-i-collab-notifications',
            name: 'Notifications not arriving',
            type: 'item',
            audience: 'internal',
            description: 'Mentions never surface on desktop or phone, so messages sit unread for hours.',
            knowledgeIds: [],
            subformIds: [],
          },
          {
            id: 'cat-i-collab-guest',
            name: 'External guest cannot join',
            type: 'item',
            audience: 'internal',
            description: 'A customer or partner blocked at the door of a channel or a meeting.',
            knowledgeIds: [KB.SSO_EXPLAINED],
            subformIds: [SF.REQUEST_ACCESS],
          },
          {
            id: 'cat-i-collab-recording',
            name: 'Recording or transcript missing',
            type: 'item',
            audience: 'internal',
            description: 'A meeting that was recorded and never appeared afterwards.',
            knowledgeIds: [],
            subformIds: [],
          },
          {
            id: 'cat-i-collab-not-listed',
            name: 'Not listed',
            type: 'item',
            audience: 'internal',
            description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.',
            knowledgeIds: [],
            subformIds: [],
          },
        ],
      },
      {
        id: 'cat-s-web-apps',
        name: 'Browsers & web apps',
        type: 'subcategory',
        audience: 'internal',
        description: 'Anything that lives in a browser tab, including the tools nobody thinks of as applications.',
        children: [
          {
            id: 'cat-i-web-not-loading',
            name: 'Page not loading or showing errors',
            type: 'item',
            audience: 'internal',
            popular: true,
            description: 'A blank tab, a spinner that never stops, or an error the page will not explain.',
            knowledgeIds: [],
            subformIds: [],
          },
          {
            /* Deliberately NOT "loops back to the sign-in page" — that is
             * cat-i-sso under Accounts & Access, and a person could not choose
             * between the two. This one is the opposite symptom: you do get in,
             * and then keep getting thrown out. */
            id: 'cat-i-web-session-drop',
            name: 'Signed out of a site over and over',
            type: 'item',
            audience: 'internal',
            description: 'You sign in, work for a few minutes, and the site drops the session again.',
            knowledgeIds: [KB.SSO_EXPLAINED, KB.RESET_PASSWORD],
            subformIds: [SF.REPORT_SIGNIN],
          },
          {
            id: 'cat-i-web-blocked',
            name: 'Site blocked or warned as unsafe',
            type: 'item',
            audience: 'internal',
            description: 'The browser stops on a certificate or policy warning before the page loads.',
            knowledgeIds: [],
            subformIds: [],
          },
          {
            /* Scoped to the BROKEN half on purpose: an extension nobody has
             * installed yet is cat-i-plugin, under Software & Licensing. */
            id: 'cat-i-web-extension',
            name: 'Extension or add-in stopped working',
            type: 'item',
            audience: 'internal',
            fulfillment: '1-2 business days',
            description: 'A browser tool that vanished after an update, or now errors on every page.',
            knowledgeIds: [KB.INSTALL_SOFTWARE],
            subformIds: [SF.SOFTWARE_REQUEST],
          },
          {
            id: 'cat-i-web-transfer',
            name: 'Downloads or uploads failing',
            type: 'item',
            audience: 'internal',
            description: 'A file that stops part-way, or an upload the site rejects without saying why.',
            knowledgeIds: [],
            subformIds: [],
          },
          {
            id: 'cat-i-web-slow',
            name: 'Browser slow, freezing or crashing',
            type: 'item',
            audience: 'internal',
            description: 'Tabs hang, the window goes white, or the browser restarts on its own.',
            knowledgeIds: [],
            subformIds: [],
          },
          {
            id: 'cat-i-web-not-listed',
            name: 'Not listed',
            type: 'item',
            audience: 'internal',
            description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.',
            knowledgeIds: [],
            subformIds: [],
          },
        ],
      },
      {
        id: 'cat-s-lob-apps',
        name: 'Line-of-business apps',
        type: 'subcategory',
        audience: 'internal',
        description: 'NetSuite, Workday, the warehouse system and the tools only one team touches.',
        children: [
          {
            id: 'cat-i-lob-signin',
            name: 'Cannot sign in to a line-of-business app',
            type: 'item',
            audience: 'internal',
            fulfillment: 'Same day',
            description: 'NetSuite, Workday or the warehouse system refusing the account outright.',
            knowledgeIds: [KB.SSO_EXPLAINED, KB.ACCOUNT_LOCKED],
            subformIds: [SF.REPORT_SIGNIN],
          },
          {
            id: 'cat-i-lob-permissions',
            name: 'The screen you need is missing from the app',
            type: 'item',
            audience: 'internal',
            description: 'The app opens, but the menu or screen the job depends on is not there for your account.',
            knowledgeIds: [KB.SSO_EXPLAINED],
            subformIds: [SF.REQUEST_ACCESS],
          },
          {
            id: 'cat-i-lob-error',
            name: 'Error on a routine task',
            type: 'item',
            audience: 'internal',
            description: 'A step that worked yesterday now fails with a message nobody recognises.',
            knowledgeIds: [],
            subformIds: [],
          },
          {
            id: 'cat-i-lob-integration',
            name: 'Overnight job or interface did not run',
            type: 'item',
            audience: 'internal',
            description: 'A scheduled job that never fired, leaving the next team with yesterday’s data.',
            knowledgeIds: [KB.API_KEYS, KB.CHANGE_PROCESS],
            subformIds: [],
          },
          {
            id: 'cat-i-lob-print',
            name: 'Documents or labels not printing from the app',
            type: 'item',
            audience: 'internal',
            description: 'Invoices, pick lists or shipping labels that never reach the printer.',
            knowledgeIds: [KB.INSTALL_SOFTWARE],
            subformIds: [SF.FACILITIES_ISSUE],
          },
          {
            id: 'cat-i-lob-slow',
            name: 'App slow or unavailable',
            type: 'item',
            audience: 'internal',
            fulfillment: 'Same day triage',
            description: 'Screens that take minutes, or a system nobody in the team can reach at all.',
            knowledgeIds: [KB.ESCALATION_PATHS],
            subformIds: [],
          },
          {
            id: 'cat-i-lob-not-listed',
            name: 'Not listed',
            type: 'item',
            audience: 'internal',
            description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.',
            knowledgeIds: [],
            subformIds: [],
          },
        ],
      },
      {
        id: 'cat-s-apps-not-listed',
        name: 'Not listed',
        type: 'subcategory',
        audience: 'internal',
        description: 'An application none of the above covers. Read and routed by hand.',
        children: [
          {
            id: 'cat-i-apps-not-listed',
            name: 'Not listed',
            type: 'item',
            audience: 'internal',
            description: 'Name the application and what it does wrong — a person reads it and routes it by hand.',
            knowledgeIds: [],
            subformIds: [],
          },
        ],
      },
    ],
  },

  /* ================================================================== *
   * 5 — Software & Licensing
   *
   * The COMMERCIAL side of software: buying it, renewing it, staying compliant.
   * A broken application belongs in Application & Software (product 4).
   * ================================================================== */
  {
    id: CAT.P_SOFTWARE,
    name: 'Software & Licensing',
    type: 'product',
    audience: 'internal',
    ownerId: USR.JAMES,
    description: 'Buying, installing, renewing and staying licence-compliant, plus the spend approvals. A broken app belongs in Application & Software.',
    children: [
      {
        id: 'cat-s-install',
        name: 'Install & updates',
        type: 'subcategory',
        audience: 'internal',
        description: 'Getting approved software onto a machine, and off it again.',
        children: [
          {
            id: CAT.I_SOFTWARE_REQ,
            name: 'Software you need is not installed',
            type: 'item',
            audience: 'internal',
            popular: true,
            fulfillment: '1-2 business days',
            description: 'Anything in the self-service catalogue installs immediately; everything else routes for review.',
            knowledgeIds: [KB.INSTALL_SOFTWARE, KB.LICENSE_POLICY],
            subformIds: [SF.SOFTWARE_REQUEST],
          },
          {
            id: 'cat-i-install-blocked',
            name: 'Install blocked by policy',
            type: 'item',
            audience: 'internal',
            description: 'Self-Service refuses the app, or the installer wants rights the account does not have.',
            knowledgeIds: [KB.INSTALL_SOFTWARE, KB.APPROVAL_THRESHOLDS],
            subformIds: [SF.SOFTWARE_REQUEST],
          },
          {
            id: 'cat-i-os-updates',
            name: 'Update will not install',
            type: 'item',
            audience: 'internal',
            description: 'A patch that fails every attempt, or a machine stuck asking to restart for a week.',
            knowledgeIds: [KB.INSTALL_SOFTWARE, KB.CHANGE_PROCESS],
            subformIds: [SF.SOFTWARE_REQUEST],
          },
          {
            id: 'cat-i-plugin',
            name: 'Add-in or plugin missing',
            type: 'item',
            audience: 'internal',
            fulfillment: '1-2 business days',
            description: 'An Outlook add-in, a browser extension or a design plugin outside the standard build.',
            knowledgeIds: [KB.INSTALL_SOFTWARE],
            subformIds: [SF.SOFTWARE_REQUEST],
          },
          {
            id: 'cat-i-adobe',
            name: 'No Adobe Creative Cloud seat yet',
            type: 'item',
            audience: 'internal',
            fulfillment: '2 business days',
            description: 'A named-user seat from the design pool, assigned before Creative Cloud will activate at all.',
            knowledgeIds: [KB.ADOBE_ACTIVATION, KB.LICENSE_POLICY],
            subformIds: [SF.SOFTWARE_REQUEST, SF.LICENSE_RENEWAL],
          },
          {
            id: 'cat-i-uninstall',
            name: 'Software no longer needed',
            type: 'item',
            audience: 'internal',
            description: 'An app nobody uses, removed so the seat can be reclaimed before the renewal date.',
            knowledgeIds: [KB.LICENSE_POLICY, KB.RETURN_EQUIPMENT],
            subformIds: [SF.SOFTWARE_REQUEST],
          },
          {
            id: 'cat-i-install-not-listed',
            name: 'Not listed',
            type: 'item',
            audience: 'internal',
            description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.',
            knowledgeIds: [],
            subformIds: [SF.SOFTWARE_REQUEST],
          },
        ],
      },
      {
        id: 'cat-s-licensing',
        name: 'Licences & renewals',
        type: 'subcategory',
        audience: 'internal',
        description: 'Procurement territory. Every request here can trigger an approval policy.',
        children: [
          {
            id: 'cat-i-license-expired',
            name: 'Licence expired or seat revoked',
            type: 'item',
            audience: 'internal',
            popular: true,
            fulfillment: '1 business day',
            description: 'The app opens read-only, asks you to buy, or says the subscription ended.',
            knowledgeIds: [KB.LICENSE_POLICY, KB.ADOBE_ACTIVATION],
            subformIds: [SF.LICENSE_RENEWAL],
          },
          {
            id: 'cat-i-new-license',
            name: 'Need a tool Northwind has not bought yet',
            type: 'item',
            audience: 'internal',
            fulfillment: '5 business days',
            description: 'A tool nobody has bought yet — needs security review, budget owner sign-off and a renewal date.',
            knowledgeIds: [KB.LICENSE_POLICY, KB.APPROVAL_THRESHOLDS],
            subformIds: [SF.LICENSE_RENEWAL, SF.EXPENSE_APPROVAL],
          },
          {
            id: 'cat-i-renewal',
            name: 'Renewal or true-up due',
            type: 'item',
            audience: 'internal',
            description: 'The 60-day renewal notice, seat reconciliation, and reclaiming licences from leavers.',
            knowledgeIds: [KB.LICENSE_POLICY, KB.RETURN_EQUIPMENT],
            subformIds: [SF.LICENSE_RENEWAL],
          },
          {
            id: 'cat-i-seat-transfer',
            name: 'Seat needs moving to someone else',
            type: 'item',
            audience: 'internal',
            description: 'A leaver’s licence reassigned rather than bought a second time.',
            knowledgeIds: [KB.LICENSE_POLICY, KB.RETURN_EQUIPMENT],
            subformIds: [SF.LICENSE_RENEWAL],
          },
          {
            id: 'cat-i-spend-approval',
            name: 'Software spend needs approving',
            type: 'item',
            audience: 'internal',
            description: 'Thresholds: under $500 is a manager, $500-$5,000 adds Finance, above that adds the VP.',
            knowledgeIds: [KB.APPROVAL_THRESHOLDS, KB.LICENSE_POLICY],
            subformIds: [SF.EXPENSE_APPROVAL],
          },
          {
            id: 'cat-i-vendor-invoice',
            name: 'Vendor quote or invoice does not match',
            type: 'item',
            audience: 'internal',
            description: 'A renewal quote that differs from the contract, or an invoice for seats nobody recognises.',
            knowledgeIds: [KB.APPROVAL_THRESHOLDS, KB.LICENSE_POLICY],
            subformIds: [SF.EXPENSE_APPROVAL, SF.LICENSE_RENEWAL],
          },
          {
            id: 'cat-i-licensing-not-listed',
            name: 'Not listed',
            type: 'item',
            audience: 'internal',
            description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.',
            knowledgeIds: [],
            subformIds: [SF.LICENSE_RENEWAL],
          },
        ],
      },
      {
        id: 'cat-s-dev-tooling',
        name: 'Developer tooling',
        type: 'subcategory',
        audience: 'both',
        description: 'Shared with customers: the same API-key and sandbox guidance serves Northwind engineers and customer developers.',
        children: [
          {
            id: 'cat-i-api-credentials',
            name: 'API key rejected or needs rotating',
            type: 'item',
            audience: 'both',
            fulfillment: '1 business day',
            description: 'A key returning unauthorised, scoped to the wrong environment, or exposed and needing rotation.',
            knowledgeIds: [KB.API_KEYS, KB.SSO_EXPLAINED],
            subformIds: [SF.REQUEST_ACCESS, SF.INTEGRATION_HELP],
          },
          {
            id: 'cat-i-sandbox',
            name: 'Sandbox expired or out of date',
            type: 'item',
            audience: 'both',
            fulfillment: '2 business days',
            description: 'A sandbox past its 30 days, or one whose data no longer resembles production.',
            knowledgeIds: [KB.CHANGE_PROCESS, KB.API_KEYS],
            subformIds: [SF.SOFTWARE_REQUEST, SF.INTEGRATION_HELP],
          },
          {
            id: 'cat-i-rate-limit',
            name: 'Requests rate limited or throttled',
            type: 'item',
            audience: 'both',
            description: 'Calls start returning 429 in the middle of a job that ran fine last month.',
            knowledgeIds: [KB.API_KEYS],
            subformIds: [SF.INTEGRATION_HELP],
          },
          {
            id: 'cat-i-repo-access',
            name: 'No access to a repository or pipeline',
            type: 'item',
            audience: 'internal',
            description: 'A push refused, a build the account cannot see, or a runner that will not start.',
            knowledgeIds: [KB.SSO_EXPLAINED, KB.API_KEYS],
            subformIds: [SF.REQUEST_ACCESS],
          },
          {
            id: 'cat-i-local-env',
            name: 'Local environment will not build',
            type: 'item',
            audience: 'internal',
            description: 'Dependencies fail to install, or the app runs everywhere except this machine.',
            knowledgeIds: [KB.INSTALL_SOFTWARE],
            subformIds: [SF.SOFTWARE_REQUEST],
          },
          {
            id: 'cat-i-test-data',
            name: 'Test data needs refreshing',
            type: 'item',
            audience: 'both',
            description: 'A sandbox that needs realistic data, or a reset before a demo.',
            knowledgeIds: [KB.CHANGE_PROCESS, KB.IMPORT_CATALOG],
            subformIds: [SF.INTEGRATION_HELP],
          },
          {
            id: 'cat-i-dev-tooling-not-listed',
            name: 'Not listed',
            type: 'item',
            audience: 'both',
            description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.',
            knowledgeIds: [],
            subformIds: [SF.INTEGRATION_HELP],
          },
        ],
      },
      {
        id: 'cat-s-software-not-listed',
        name: 'Not listed',
        type: 'subcategory',
        audience: 'internal',
        description: 'Something about software or licensing that none of the above covers. Read and routed by hand.',
        children: [
          {
            id: 'cat-i-software-not-listed',
            name: 'Not listed',
            type: 'item',
            audience: 'internal',
            description: 'Describe what you need in your own words — a person reads it and routes it by hand.',
            knowledgeIds: [],
            subformIds: [SF.SOFTWARE_REQUEST],
          },
        ],
      },
    ],
  },

  /* ================================================================== *
   * 6 — Workplace & Facilities
   * ================================================================== */
  {
    id: CAT.P_WORKPLACE,
    name: 'Workplace & Facilities',
    type: 'product',
    audience: 'internal',
    ownerId: USR.LINDA,
    description: 'Buildings and desks, joining and leaving, and the ways-of-working material the service desk itself is trained on.',
    children: [
      {
        id: 'cat-s-building',
        name: 'Building & desks',
        type: 'subcategory',
        audience: 'internal',
        description: 'Chicago HQ, New York, Austin and the Bolingbrook warehouse.',
        children: [
          {
            id: 'cat-i-facilities-issue',
            name: 'Something in the building is broken',
            type: 'item',
            audience: 'internal',
            popular: true,
            fulfillment: 'Same day',
            description: 'A leak, a broken chair, a door that will not shut — anything about the physical space.',
            knowledgeIds: [],
            subformIds: [SF.FACILITIES_ISSUE],
          },
          {
            id: 'cat-i-comfort',
            name: 'Too hot, too cold or no lighting',
            type: 'item',
            audience: 'internal',
            description: 'A floor that never settles, a dead light, or a room nobody can sit in for an hour.',
            knowledgeIds: [],
            subformIds: [SF.FACILITIES_ISSUE],
          },
          {
            id: 'cat-i-badge-access',
            name: 'Badge not opening a door',
            type: 'item',
            audience: 'internal',
            fulfillment: '1 business day',
            description: 'A new badge, a lost one, or access that stops at the Elk Grove data-centre door.',
            knowledgeIds: [KB.ACCOUNT_LOCKED, KB.APPROVAL_THRESHOLDS],
            subformIds: [SF.REQUEST_ACCESS, SF.FACILITIES_ISSUE],
          },
          {
            id: 'cat-i-desk-move',
            name: 'Desk or seating needs changing',
            type: 'item',
            audience: 'internal',
            fulfillment: '3 business days',
            description: 'Move a person or a whole team. Includes monitor arms, cable runs and the floor-plan update.',
            knowledgeIds: [KB.REQUEST_MONITOR],
            subformIds: [SF.FACILITIES_ISSUE],
          },
          {
            id: 'cat-i-supplies',
            name: 'Supplies or kitchen stock run out',
            type: 'item',
            audience: 'internal',
            description: 'Stationery, coffee, cleaning after a spill, or a fridge nobody has emptied.',
            knowledgeIds: [],
            subformIds: [SF.FACILITIES_ISSUE],
          },
          {
            id: 'cat-i-parking-deliveries',
            name: 'Parking, bike store or a delivery needs arranging',
            type: 'item',
            audience: 'internal',
            description: 'A space for the week, access to the bike store, or a delivery that needs signing for.',
            knowledgeIds: [],
            subformIds: [SF.FACILITIES_ISSUE],
          },
          {
            id: 'cat-i-building-not-listed',
            name: 'Not listed',
            type: 'item',
            audience: 'internal',
            description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.',
            knowledgeIds: [],
            subformIds: [SF.FACILITIES_ISSUE],
          },
        ],
      },
      {
        id: 'cat-s-joining-leaving',
        name: 'Joining & leaving',
        type: 'subcategory',
        audience: 'internal',
        description: 'The two most cross-functional requests Northwind runs. Both fan out to IT, Facilities and People Ops.',
        children: [
          {
            id: 'cat-i-new-hire',
            name: 'New hire starting',
            type: 'item',
            audience: 'internal',
            popular: true,
            fulfillment: 'Start date - 5 days',
            description: 'One request produces the account, the laptop, the badge, the seat and the first-week curriculum.',
            knowledgeIds: [KB.ONBOARDING_CHECKLIST, KB.LAPTOP_SETUP, KB.MFA_SETUP],
            subformIds: [SF.NEW_HIRE],
          },
          {
            id: 'cat-i-starter-not-ready',
            name: 'New starter has no account or laptop on day one',
            type: 'item',
            audience: 'internal',
            fulfillment: 'Same day',
            description: 'The start date arrived before the kit or the accounts did.',
            knowledgeIds: [KB.ONBOARDING_CHECKLIST, KB.LAPTOP_SETUP],
            subformIds: [SF.NEW_HIRE],
          },
          {
            id: 'cat-i-contractor-onboarding',
            name: 'Contractor starting',
            type: 'item',
            audience: 'internal',
            fulfillment: '3 business days',
            description: 'A lighter onboarding with a mandatory end date and no default building access.',
            knowledgeIds: [KB.ONBOARDING_CHECKLIST, KB.SSO_EXPLAINED],
            subformIds: [SF.NEW_HIRE],
          },
          {
            id: 'cat-i-role-change',
            name: 'Someone is moving role or team',
            type: 'item',
            audience: 'internal',
            description: 'Access that should follow the person, access that should not, and the manager-chain update.',
            knowledgeIds: [KB.ONBOARDING_CHECKLIST, KB.APPROVAL_THRESHOLDS],
            subformIds: [SF.NEW_HIRE, SF.REQUEST_ACCESS],
          },
          {
            id: 'cat-i-offboarding',
            name: 'Someone is leaving',
            type: 'item',
            audience: 'internal',
            fulfillment: 'Last day',
            description: 'Disable access at the right hour, recover equipment, reassign owned records, reclaim licences.',
            knowledgeIds: [KB.RETURN_EQUIPMENT, KB.ONBOARDING_CHECKLIST, KB.LICENSE_POLICY],
            subformIds: [SF.OFFBOARDING, SF.RETURN_HARDWARE],
          },
          {
            id: 'cat-i-leaver-access',
            name: 'A leaver still has access',
            type: 'item',
            audience: 'internal',
            fulfillment: 'Immediate',
            description: 'An account, badge or licence that survived the last day and should not have.',
            knowledgeIds: [KB.RETURN_EQUIPMENT, KB.ACCOUNT_LOCKED],
            subformIds: [SF.OFFBOARDING],
          },
          {
            id: 'cat-i-joining-not-listed',
            name: 'Not listed',
            type: 'item',
            audience: 'internal',
            description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.',
            knowledgeIds: [],
            subformIds: [SF.NEW_HIRE],
          },
        ],
      },
      {
        id: 'cat-s-ways-of-working',
        name: 'Ways of working',
        type: 'subcategory',
        audience: 'internal',
        description: 'The service desk’s own enablement material. Every atom here is also a lesson in the Support Agent curriculum.',
        children: [
          {
            id: 'cat-i-working-a-queue',
            name: 'Not sure how to work the queue',
            type: 'item',
            audience: 'internal',
            description: 'Triage order, what a good first response looks like, and the macros that save the most typing.',
            knowledgeIds: [KB.TRIAGE_BASICS, KB.READING_A_TICKET, KB.USING_MACROS],
            subformIds: [],
          },
          {
            id: 'cat-i-customer-comms',
            name: 'Not sure what to say to a customer',
            type: 'item',
            audience: 'internal',
            description: 'Tone, structure and the close. Includes the de-escalation script the Austin team wrote.',
            knowledgeIds: [KB.WRITING_TO_CUSTOMERS, KB.HANDLING_ANGRY, KB.CLOSING_WELL],
            subformIds: [],
          },
          {
            id: 'cat-i-escalation-sla',
            name: 'Not sure who to escalate to',
            type: 'item',
            audience: 'internal',
            description: 'Who to pull in, when the clock pauses, and what an Enterprise customer has actually been promised.',
            knowledgeIds: [KB.ESCALATION_PATHS, KB.SLA_EXPLAINED],
            subformIds: [],
          },
          {
            id: 'cat-i-wrong-queue',
            name: 'Work landing in the wrong queue',
            type: 'item',
            audience: 'internal',
            description: 'Tickets arriving where nobody can fix them, or bouncing between two teams.',
            knowledgeIds: [KB.TRIAGE_BASICS, KB.ESCALATION_PATHS],
            subformIds: [],
          },
          {
            id: 'cat-i-knowledge-gap',
            name: 'No article exists for a repeat question',
            type: 'item',
            audience: 'internal',
            description: 'The same question keeps arriving and there is nothing written to send back.',
            knowledgeIds: [KB.READING_A_TICKET, KB.USING_MACROS],
            subformIds: [],
          },
          {
            id: 'cat-i-raise-a-change',
            name: 'A change needs raising',
            type: 'item',
            audience: 'internal',
            description: 'Standard, normal and emergency changes — which one you are actually raising, and who authorises it.',
            knowledgeIds: [KB.CHANGE_PROCESS, KB.APPROVAL_THRESHOLDS],
            subformIds: [SF.EXPENSE_APPROVAL],
          },
          {
            id: 'cat-i-ways-not-listed',
            name: 'Not listed',
            type: 'item',
            audience: 'internal',
            description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.',
            knowledgeIds: [],
            subformIds: [],
          },
        ],
      },
      {
        id: 'cat-s-workplace-not-listed',
        name: 'Not listed',
        type: 'subcategory',
        audience: 'internal',
        description: 'Something about the workplace that none of the above covers. Read and routed by hand.',
        children: [
          {
            id: 'cat-i-workplace-not-listed',
            name: 'Not listed',
            type: 'item',
            audience: 'internal',
            description: 'Describe the problem in your own words — a person reads it and routes it by hand.',
            knowledgeIds: [],
            subformIds: [SF.FACILITIES_ISSUE],
          },
        ],
      },
    ],
  },

  /* ================================================================== *
   * 7 — Northwind Storefront — the product customers buy.
   * Everything under here is customer-facing, which is why the whole product
   * carries audience 'external'.
   * ================================================================== */
  {
    id: CAT.P_STOREFRONT,
    name: 'Northwind Storefront',
    type: 'product',
    audience: 'external',
    ownerId: USR.LISA,
    description: 'The commerce platform Northwind sells. This branch is what customers see in the help centre and the portal.',
    children: [
      {
        id: 'cat-s-getting-started',
        name: 'Getting started',
        type: 'subcategory',
        audience: 'external',
        description: 'The first two weeks of a new customer. Deflection here is worth more than anywhere else in the catalog.',
        children: [
          {
            id: CAT.I_STOREFRONT_SETUP,
            name: 'Set up your storefront',
            type: 'item',
            audience: 'external',
            popular: true,
            description: 'Domain, theme, tax profile and the go-live checklist. Ten minutes if the domain is already delegated.',
            knowledgeIds: [KB.STOREFRONT_SETUP],
            subformIds: [SF.INTEGRATION_HELP],
          },
          {
            id: 'cat-i-import-catalog',
            name: 'Product import failed or dropped rows',
            type: 'item',
            audience: 'external',
            popular: true,
            description: 'Rows rejected on validation, variants collapsed into one, or images that never attached.',
            knowledgeIds: [KB.IMPORT_CATALOG, KB.STOREFRONT_SETUP],
            subformIds: [SF.INTEGRATION_HELP],
          },
          {
            id: 'cat-i-domain',
            name: 'Store not loading on your own domain',
            type: 'item',
            audience: 'external',
            description: 'The store answers on the temporary address but not on the domain you delegated.',
            knowledgeIds: [KB.STOREFRONT_SETUP],
            subformIds: [SF.INTEGRATION_HELP, SF.STOREFRONT_BUG],
          },
          {
            id: 'cat-i-invite-team',
            name: 'Team member cannot be invited or signed in',
            type: 'item',
            audience: 'external',
            description: 'An invite that never arrives, a role with the wrong permissions, or SSO that will not connect.',
            knowledgeIds: [KB.STOREFRONT_SETUP, KB.SSO_EXPLAINED],
            subformIds: [SF.INTEGRATION_HELP],
          },
          {
            id: 'cat-i-theme',
            name: 'Theme renders wrong on mobile',
            type: 'item',
            audience: 'external',
            description: 'Layout breaks at phone width, or a section disappears after a theme update.',
            knowledgeIds: [KB.STOREFRONT_SETUP],
            subformIds: [SF.STOREFRONT_BUG],
          },
          {
            id: 'cat-i-tax-shipping',
            name: 'Tax or shipping rates wrong at checkout',
            type: 'item',
            audience: 'external',
            description: 'The wrong rate applied, or a region that shows no shipping option at all.',
            knowledgeIds: [KB.STOREFRONT_SETUP, KB.IMPORT_CATALOG],
            subformIds: [SF.STOREFRONT_BUG],
          },
          {
            id: 'cat-i-getting-started-not-listed',
            name: 'Not listed',
            type: 'item',
            audience: 'external',
            description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.',
            knowledgeIds: [],
            subformIds: [SF.STOREFRONT_BUG],
          },
        ],
      },
      {
        id: 'cat-s-payments-billing',
        name: 'Payments & billing',
        type: 'subcategory',
        audience: 'external',
        description: 'Money in from shoppers, and money out to Northwind. Two different things customers routinely conflate.',
        children: [
          {
            id: CAT.I_PAYMENTS,
            name: 'Payments not going through',
            type: 'item',
            audience: 'external',
            popular: true,
            description: 'A provider that will not connect, cards declined at checkout, or verification stuck in review.',
            knowledgeIds: [KB.CONNECT_PAYMENTS],
            subformIds: [SF.INTEGRATION_HELP, SF.STOREFRONT_BUG],
          },
          {
            id: 'cat-i-payout-missing',
            name: 'Payout missing or late',
            type: 'item',
            audience: 'external',
            description: 'A settlement that has not landed, or an amount that does not match the orders behind it.',
            knowledgeIds: [KB.CONNECT_PAYMENTS, KB.INVOICE_QUESTIONS],
            subformIds: [SF.BILLING_QUESTION],
          },
          {
            id: 'cat-i-refund-dispute',
            name: 'Refund or chargeback problem',
            type: 'item',
            audience: 'external',
            description: 'A refund that will not process, or a dispute raised by a shopper’s bank.',
            knowledgeIds: [KB.CONNECT_PAYMENTS, KB.INVOICE_QUESTIONS],
            subformIds: [SF.BILLING_QUESTION, SF.STOREFRONT_BUG],
          },
          {
            id: CAT.I_BILLING,
            name: 'Question about your invoice',
            type: 'item',
            audience: 'external',
            popular: true,
            description: 'Read your Northwind invoice, or query a line you do not recognise.',
            knowledgeIds: [KB.INVOICE_QUESTIONS],
            subformIds: [SF.BILLING_QUESTION],
          },
          {
            id: 'cat-i-plans-seats',
            name: 'Wrong plan or seat count',
            type: 'item',
            audience: 'external',
            description: 'Charged for seats nobody uses, or blocked by a limit your plan should already cover.',
            knowledgeIds: [KB.INVOICE_QUESTIONS, KB.SLA_EXPLAINED],
            subformIds: [SF.BILLING_QUESTION],
          },
          {
            id: 'cat-i-billing-contact',
            name: 'Billing contact or card needs changing',
            type: 'item',
            audience: 'external',
            description: 'Invoices going to someone who left, or a payment method that expired.',
            knowledgeIds: [KB.INVOICE_QUESTIONS],
            subformIds: [SF.BILLING_QUESTION],
          },
          {
            id: 'cat-i-payments-not-listed',
            name: 'Not listed',
            type: 'item',
            audience: 'external',
            description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.',
            knowledgeIds: [],
            subformIds: [SF.BILLING_QUESTION],
          },
        ],
      },
      {
        id: 'cat-s-integrations',
        name: 'Integrations & API',
        type: 'subcategory',
        audience: 'external',
        description: 'Where customer developers land. Deep-linked from the API docs.',
        children: [
          {
            id: 'cat-i-storefront-api-keys',
            name: 'API key rejected',
            type: 'item',
            audience: 'external',
            description: 'A key returning unauthorised, scoped to the wrong store, or one you need to rotate without downtime.',
            knowledgeIds: [KB.API_KEYS],
            subformIds: [SF.INTEGRATION_HELP],
          },
          {
            id: 'cat-i-api-errors',
            name: 'API returning errors',
            type: 'item',
            audience: 'external',
            description: 'Calls that worked yesterday now come back 4xx or 5xx with no change on your side.',
            knowledgeIds: [KB.API_KEYS, KB.SLA_EXPLAINED],
            subformIds: [SF.INTEGRATION_HELP, SF.STOREFRONT_BUG],
          },
          {
            id: 'cat-i-webhooks',
            name: 'Webhooks not arriving',
            type: 'item',
            audience: 'external',
            description: 'Order events that never reach your endpoint, or a signature that fails to verify.',
            knowledgeIds: [KB.WEBHOOK_SETUP, KB.API_KEYS],
            subformIds: [SF.INTEGRATION_HELP, SF.STOREFRONT_BUG],
          },
          {
            id: 'cat-i-orders-not-syncing',
            name: 'Orders not syncing to your system',
            type: 'item',
            audience: 'external',
            description: 'Orders visible in the storefront but missing from your ERP or fulfilment tool.',
            knowledgeIds: [KB.WEBHOOK_SETUP, KB.IMPORT_CATALOG],
            subformIds: [SF.INTEGRATION_HELP],
          },
          {
            id: 'cat-i-inventory-sync',
            name: 'Inventory counts out of step',
            type: 'item',
            audience: 'external',
            description: 'Stock levels that drift from your warehouse system, or an oversell at checkout.',
            knowledgeIds: [KB.IMPORT_CATALOG],
            subformIds: [SF.INTEGRATION_HELP, SF.STOREFRONT_BUG],
          },
          {
            id: 'cat-i-data-export',
            name: 'Export missing data',
            type: 'item',
            audience: 'external',
            description: 'A bulk export that stops short, or a scheduled report that quietly stopped running.',
            knowledgeIds: [KB.IMPORT_CATALOG, KB.API_KEYS],
            subformIds: [SF.INTEGRATION_HELP],
          },
          {
            id: 'cat-i-integrations-not-listed',
            name: 'Not listed',
            type: 'item',
            audience: 'external',
            description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.',
            knowledgeIds: [],
            subformIds: [SF.INTEGRATION_HELP],
          },
        ],
      },
      {
        id: 'cat-s-problems-feedback',
        name: 'Problems & feedback',
        type: 'subcategory',
        audience: 'external',
        description: 'The intake side of external support — bugs, outages and the feature pipeline.',
        children: [
          {
            id: 'cat-i-report-bug',
            name: 'Something in the storefront is broken',
            type: 'item',
            audience: 'external',
            popular: true,
            description: 'Anything in the admin or the store behaving wrongly. Include the store URL and what you expected.',
            knowledgeIds: [KB.STOREFRONT_SETUP, KB.CONNECT_PAYMENTS],
            subformIds: [SF.STOREFRONT_BUG],
          },
          {
            id: 'cat-i-checkout-failing',
            name: 'Checkout failing for shoppers',
            type: 'item',
            audience: 'external',
            popular: true,
            description: 'Shoppers reach payment and the page errors, hangs or empties the basket.',
            knowledgeIds: [KB.CONNECT_PAYMENTS, KB.STOREFRONT_SETUP],
            subformIds: [SF.STOREFRONT_BUG],
          },
          {
            id: 'cat-i-store-slow',
            name: 'Storefront slow or unavailable',
            type: 'item',
            audience: 'external',
            description: 'Pages timing out, or the store returning an error for everyone at once.',
            knowledgeIds: [KB.SLA_EXPLAINED, KB.ESCALATION_PATHS],
            subformIds: [SF.STOREFRONT_BUG],
          },
          {
            id: 'cat-i-status-incidents',
            name: 'No update during an outage',
            type: 'item',
            audience: 'both',
            description: 'Where the status page lives, how incidents are communicated, and what an SLA credit is worth.',
            knowledgeIds: [KB.SLA_EXPLAINED, KB.ESCALATION_PATHS],
            subformIds: [SF.STOREFRONT_BUG],
          },
          {
            id: 'cat-i-sla-credit',
            name: 'An incident breached your SLA',
            type: 'item',
            audience: 'external',
            description: 'Downtime past what the contract promises, and the credit that follows from it.',
            knowledgeIds: [KB.SLA_EXPLAINED, KB.INVOICE_QUESTIONS],
            subformIds: [SF.BILLING_QUESTION],
          },
          {
            id: 'cat-i-feature-request',
            name: 'Something the product cannot do yet',
            type: 'item',
            audience: 'external',
            description: 'Goes to the product board, not to support. You can watch the request and get the release note.',
            knowledgeIds: [KB.WEBHOOK_SETUP],
            subformIds: [SF.FEATURE_REQUEST],
          },
          {
            id: 'cat-i-problems-not-listed',
            name: 'Not listed',
            type: 'item',
            audience: 'external',
            description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.',
            knowledgeIds: [],
            subformIds: [SF.STOREFRONT_BUG],
          },
        ],
      },
      {
        id: 'cat-s-storefront-not-listed',
        name: 'Not listed',
        type: 'subcategory',
        audience: 'external',
        description: 'Something about the Storefront that none of the above covers. Read and routed by hand.',
        children: [
          {
            id: 'cat-i-storefront-not-listed',
            name: 'Not listed',
            type: 'item',
            audience: 'external',
            description: 'Describe the problem in your own words — a person reads it and routes it by hand.',
            knowledgeIds: [],
            subformIds: [SF.STOREFRONT_BUG],
          },
        ],
      },
    ],
  },
];
