/**
 * Products & Services catalog seed.
 *
 * Three levels, always: Product › Subcategory › Item. Items are LEAVES and the
 * only nodes that carry content — a product or a subcategory is navigation.
 *
 * AN ITEM IS AUTHORED ONCE, AND SITS IN EXACTLY ONE PLACE.
 *
 * `ITEMS` below is the authored record for every leaf; the tree holds ids rather
 * than inline objects, which keeps authoring and arrangement apart. But an id
 * appears in the tree EXACTLY ONCE, and smoke enforces it — because a leaf with
 * two parents has two breadcrumbs, and the drill can only show one. A trail that
 * says "Devices & Hardware ›" for something you opened under Network & Security
 * is worse than the duplication it was avoiding.
 *
 * WHEN A SYMPTOM BELONGS IN TWO PLACES, COPY THE LEAF.
 *
 * "Wi-Fi or internet dropping" lives under Network & Wi-Fi. "Cannot connect to
 * Wi-Fi on this machine" lives under Laptops & desktops. Two records, `copyOf`
 * linking the second to the first — and each free to carry its own intake, which
 * is the real prize: one machine that will not join is endpoint work, a floor
 * that is down is network work, and they should not raise the same ticket.
 *
 * This does not breach Rule 0. Rule 0 governs KNOWLEDGE and SUBFORMS — the
 * content — and both copies still reference the same atoms by id. What is
 * duplicated is a navigational leaf, which is the cheap thing.
 *
 * Items do not OWN their content either. They reference shared atoms:
 *     knowledgeIds -> `knowledge`   (the same article can be a lesson too)
 *     subformIds   -> `subforms`    (the same intake can hang off two items)
 * See src/store/schema.js.
 *
 * ------------------------------------------------------------------
 * AUTHORING RULES
 *
 * 1. AN ITEM IS A FAULT, NOT A TOPIC. "Multi-factor code not arriving" is a
 *    situation somebody recognises as theirs. "Multi-factor authentication" is a
 *    subject, and a person with a problem cannot tell whether it is the one they
 *    are living. Name the symptom the person sees, not the cause behind it.
 *
 * 2. DENSITY. Every subcategory offers five to eight real choices.
 *
 * 3. "NOT LISTED" IS THE LAST OPTION AT EVERY LEVEL — an item at the end of
 *    every subcategory, a subcategory at the end of every product.
 *
 * Voice: terse, service-desk, sentence case. Descriptions are one line.
 * ------------------------------------------------------------------
 */

import { CAT, KB, SF } from './ids.js';

/* ================================================================== *
 * THE ITEMS — authored once, keyed by id.
 * ================================================================== */

const ITEMS = {
  [CAT.I_LAPTOP_ISSUE]: { id: CAT.I_LAPTOP_ISSUE, type: 'item', name: 'Laptop not powering on', description: 'Dead on the charger, no light at all, or it shuts down the moment it is unplugged.', knowledgeIds: [KB.SCREEN_FLICKER, KB.LAPTOP_SETUP], subformIds: [SF.LAPTOP_REPAIR], popular: true, audience: 'internal', fulfillment: 'Same day triage' },
  ['cat-i-laptop-performance']: { id: 'cat-i-laptop-performance', type: 'item', name: 'Laptop slow or freezing', description: 'Slow to wake, fans at full tilt, everything lagging an hour into the day.', knowledgeIds: [KB.LAPTOP_SETUP], subformIds: [SF.LAPTOP_REPAIR], popular: true, audience: 'internal' },
  ['cat-i-laptop-screen']: { id: 'cat-i-laptop-screen', type: 'item', name: 'Laptop screen flickering or black', description: 'Flickering, dead pixels, a cracked panel, or a display that stays black on wake.', knowledgeIds: [KB.SCREEN_FLICKER], subformIds: [SF.LAPTOP_REPAIR], audience: 'internal' },
  ['cat-i-laptop-battery']: { id: 'cat-i-laptop-battery', type: 'item', name: 'Battery drains or will not charge', description: 'An hour off the charger, a swollen case, or a charger the machine ignores entirely.', subformIds: [SF.LAPTOP_REPAIR], audience: 'internal', fulfillment: 'Same day triage' },
  ['cat-i-machine-setup']: { id: 'cat-i-machine-setup', type: 'item', name: 'New machine will not finish setup', description: 'Enrolment stalls, encryption never completes, or the VPN profile is missing after first boot.', knowledgeIds: [KB.LAPTOP_SETUP, KB.INSTALL_SOFTWARE, KB.MFA_SETUP], subformIds: [SF.NEW_HARDWARE], audience: 'internal' },
  [CAT.I_NEW_LAPTOP]: { id: CAT.I_NEW_LAPTOP, type: 'item', name: 'Laptop needs replacing', description: 'Past the 36-month cycle or beyond economical repair. Anything above the standard build needs manager approval.', knowledgeIds: [KB.LAPTOP_SETUP, KB.APPROVAL_THRESHOLDS], subformIds: [SF.NEW_HARDWARE], popular: true, audience: 'internal', fulfillment: '5-7 business days' },
  ['cat-i-laptop-input']: { id: 'cat-i-laptop-input', type: 'item', name: 'Built-in keyboard or trackpad not responding', description: 'Keys repeat or stick, or the trackpad ignores taps after a wake.', subformIds: [SF.LAPTOP_REPAIR] },
  ['cat-i-disk-full']: { id: 'cat-i-disk-full', type: 'item', name: 'Machine out of disk space', description: 'Saves fail and updates will not install because the drive is full.', subformIds: [SF.LAPTOP_REPAIR] },
  ['cat-i-wifi']: { id: 'cat-i-wifi', type: 'item', name: 'Wi-Fi or internet dropping', description: 'Drops out around the office, or connects with no traffic behind it.', subformIds: [SF.LAPTOP_REPAIR], audience: 'internal' },
  /* THE LAPTOP HALF OF THE SAME SYMPTOM, as its own record.
   * It is a copy of the leaf, not of the content: both point at the same intake
   * today, and either may take a different one tomorrow — which is the reason to
   * copy rather than to place twice. One machine that will not join is endpoint
   * work; a floor that is down is network work. */
  ['cat-i-laptop-wifi']: { id: 'cat-i-laptop-wifi', type: 'item', name: 'Cannot connect to Wi-Fi on this machine', description: 'Other people are online, this laptop will not join or keeps asking for the password.', subformIds: [SF.LAPTOP_REPAIR], audience: 'internal', copyOf: 'cat-i-wifi' },
  ['cat-i-computers-not-listed']: { id: 'cat-i-computers-not-listed', type: 'item', name: 'Not listed', description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.', subformIds: [SF.LAPTOP_REPAIR], audience: 'internal' },
  ['cat-i-monitor']: { id: 'cat-i-monitor', type: 'item', name: 'Monitor or dock not detected', description: 'Nothing on the second screen, a dock that drops out, or only one of two panels lighting up.', knowledgeIds: [KB.SCREEN_FLICKER, KB.REQUEST_MONITOR], subformIds: [SF.LAPTOP_REPAIR, SF.NEW_HARDWARE], audience: 'internal', fulfillment: '3-5 business days' },
  ['cat-i-desk-accessories']: { id: 'cat-i-desk-accessories', type: 'item', name: 'Keyboard, mouse or headset not working', description: 'Dead batteries, a dongle that will not pair, or a mic nobody on the call can hear.', knowledgeIds: [KB.REQUEST_MONITOR], subformIds: [SF.NEW_HARDWARE], audience: 'internal', fulfillment: '3-5 business days' },
  ['cat-i-webcam']: { id: 'cat-i-webcam', type: 'item', name: 'Camera or microphone not detected', description: 'Calls open with no video, or the wrong device is picked every single time.', subformIds: [SF.LAPTOP_REPAIR], audience: 'internal' },
  ['cat-i-printing']: { id: 'cat-i-printing', type: 'item', name: 'Printer not printing', description: 'Jobs queue and never come out, the printer is missing from the list, or scan-to-share fails.', knowledgeIds: [KB.INSTALL_SOFTWARE], subformIds: [SF.FACILITIES_ISSUE], audience: 'internal' },
  ['cat-i-adapters']: { id: 'cat-i-adapters', type: 'item', name: 'Missing cable, dongle or adapter', description: 'No way to reach the projector, the dock or a second display.', knowledgeIds: [KB.REQUEST_MONITOR], subformIds: [SF.NEW_HARDWARE], audience: 'internal', fulfillment: '3-5 business days' },
  ['cat-i-peripheral-worn']: { id: 'cat-i-peripheral-worn', type: 'item', name: 'Accessory damaged or worn out', description: 'A frayed cable, a cracked case, a headset band that finally snapped.', knowledgeIds: [KB.REQUEST_MONITOR, KB.RETURN_EQUIPMENT], subformIds: [SF.NEW_HARDWARE, SF.RETURN_HARDWARE], audience: 'internal' },
  ['cat-i-peripherals-not-listed']: { id: 'cat-i-peripherals-not-listed', type: 'item', name: 'Not listed', description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.', subformIds: [SF.LAPTOP_REPAIR], audience: 'internal' },
  ['cat-i-lost-device']: { id: 'cat-i-lost-device', type: 'item', name: 'Lost or stolen device', description: 'Remote wipe, credential rotation and the security report. Raise this before anything else.', knowledgeIds: [KB.ACCOUNT_LOCKED, KB.MFA_SETUP, KB.RETURN_EQUIPMENT], subformIds: [SF.LAPTOP_REPAIR, SF.REPORT_SIGNIN], popular: true, audience: 'internal', fulfillment: 'Immediate' },
  ['cat-i-phone-damaged']: { id: 'cat-i-phone-damaged', type: 'item', name: 'Phone cracked or will not charge', description: 'Physical damage, or a handset that no longer holds charge through a shift.', knowledgeIds: [KB.RETURN_EQUIPMENT], subformIds: [SF.LAPTOP_REPAIR, SF.RETURN_HARDWARE], audience: 'internal' },
  ['cat-i-phone-service']: { id: 'cat-i-phone-service', type: 'item', name: 'No mobile signal or data', description: 'Calls fail, data stops at the border, or the SIM reads as unregistered.', subformIds: [SF.LAPTOP_REPAIR], audience: 'internal' },
  ['cat-i-mdm-enrolment']: { id: 'cat-i-mdm-enrolment', type: 'item', name: 'Phone will not enrol in device management', description: 'Enrolment fails part-way, or the profile disappeared after an OS update.', knowledgeIds: [KB.EMAIL_ON_PHONE, KB.MFA_SETUP], subformIds: [SF.LAPTOP_REPAIR], audience: 'internal' },
  ['cat-i-roaming']: { id: 'cat-i-roaming', type: 'item', name: 'Travelling and roaming is not enabled', description: 'A trip that needs the international add-on before the person leaves.', knowledgeIds: [KB.APPROVAL_THRESHOLDS], subformIds: [SF.NEW_HARDWARE], audience: 'internal', fulfillment: '2 business days' },
  ['cat-i-company-phone']: { id: 'cat-i-company-phone', type: 'item', name: 'No company phone or tablet yet', description: 'Eligible roles, plan tiers, and the international-roaming add-on for the field team.', knowledgeIds: [KB.EMAIL_ON_PHONE, KB.APPROVAL_THRESHOLDS], subformIds: [SF.NEW_HARDWARE], audience: 'internal', fulfillment: '5 business days' },
  ['cat-i-mobile-not-listed']: { id: 'cat-i-mobile-not-listed', type: 'item', name: 'Not listed', description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.', subformIds: [SF.LAPTOP_REPAIR], audience: 'internal' },
  ['cat-i-repair-warranty']: { id: 'cat-i-repair-warranty', type: 'item', name: 'Device needs repair or a warranty claim', description: 'Depot repair, an on-site vendor visit, or an accidental-damage claim against the fleet contract.', knowledgeIds: [KB.SCREEN_FLICKER, KB.RETURN_EQUIPMENT], subformIds: [SF.LAPTOP_REPAIR, SF.RETURN_HARDWARE], audience: 'internal', fulfillment: '7-10 business days' },
  ['cat-i-loaner']: { id: 'cat-i-loaner', type: 'item', name: 'Nothing to work on while a machine is away', description: 'A short-term laptop or hotspot while a machine is in repair or a new hire waits on stock.', knowledgeIds: [KB.LAPTOP_SETUP, KB.RETURN_EQUIPMENT], subformIds: [SF.NEW_HARDWARE, SF.RETURN_HARDWARE], audience: 'internal', fulfillment: 'Same day' },
  ['cat-i-return-equipment']: { id: 'cat-i-return-equipment', type: 'item', name: 'Equipment to return', description: 'Prepaid label, wipe confirmation and the asset record hand-back. Required within 5 days of a leave date.', knowledgeIds: [KB.RETURN_EQUIPMENT, KB.ONBOARDING_CHECKLIST], subformIds: [SF.RETURN_HARDWARE], audience: 'internal', fulfillment: '5 days from leave date' },
  ['cat-i-return-label']: { id: 'cat-i-return-label', type: 'item', name: 'Return label or collection never arrived', description: 'The prepaid label did not turn up, or the courier missed the collection window.', knowledgeIds: [KB.RETURN_EQUIPMENT], subformIds: [SF.RETURN_HARDWARE], audience: 'internal' },
  ['cat-i-asset-record']: { id: 'cat-i-asset-record', type: 'item', name: 'Asset record shows the wrong owner', description: 'Kit assigned to someone who handed it back, or a machine that was never booked in.', knowledgeIds: [KB.RETURN_EQUIPMENT, KB.ONBOARDING_CHECKLIST], subformIds: [SF.RETURN_HARDWARE], audience: 'internal' },
  ['cat-i-disposal']: { id: 'cat-i-disposal', type: 'item', name: 'Old kit needs wiping and disposal', description: 'End-of-life hardware that must be wiped and certified before it leaves the building.', knowledgeIds: [KB.RETURN_EQUIPMENT], subformIds: [SF.RETURN_HARDWARE], audience: 'internal' },
  ['cat-i-returns-not-listed']: { id: 'cat-i-returns-not-listed', type: 'item', name: 'Not listed', description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.', subformIds: [SF.RETURN_HARDWARE], audience: 'internal' },
  ['cat-i-devices-not-listed']: { id: 'cat-i-devices-not-listed', type: 'item', name: 'Not listed', description: 'Describe the problem in your own words — a person reads it and routes it by hand.', subformIds: [SF.LAPTOP_REPAIR], audience: 'internal' },
  ['cat-i-crm-signin']: { id: 'cat-i-crm-signin', type: 'item', name: 'Cannot sign in to Salesforce', description: 'The login is refused, the SSO tile does nothing, or the org asks for a separate password.', knowledgeIds: [KB.SSO_EXPLAINED, KB.RESET_PASSWORD], subformIds: [SF.REPORT_SIGNIN], popular: true, audience: 'internal', fulfillment: 'Same day' },
  ['cat-i-crm-permissions']: { id: 'cat-i-crm-permissions', type: 'item', name: 'Record or dashboard hidden or read-only', description: 'Signed in fine, but an account, opportunity or dashboard is hidden or will not take an edit.', knowledgeIds: [KB.SSO_EXPLAINED, KB.APPROVAL_THRESHOLDS], subformIds: [SF.REQUEST_ACCESS], audience: 'internal' },
  ['cat-i-crm-save']: { id: 'cat-i-crm-save', type: 'item', name: 'Cannot save a record', description: 'A validation rule blocks the save, or the page errors the moment you submit.', audience: 'internal' },
  ['cat-i-crm-sync']: { id: 'cat-i-crm-sync', type: 'item', name: 'Records not arriving from another system', description: 'Orders, cases or contacts that stopped appearing in Salesforce overnight.', knowledgeIds: [KB.API_KEYS], audience: 'internal' },
  ['cat-i-crm-report']: { id: 'cat-i-crm-report', type: 'item', name: 'Report or dashboard shows the wrong numbers', description: 'Totals that do not match the source, or a dashboard frozen on last week.', audience: 'internal' },
  ['cat-i-crm-slow']: { id: 'cat-i-crm-slow', type: 'item', name: 'Salesforce slow or timing out', description: 'List views take a minute to open, or a page times out in the middle of an edit.', audience: 'internal' },
  ['cat-i-crm-not-listed']: { id: 'cat-i-crm-not-listed', type: 'item', name: 'Not listed', description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.', audience: 'internal' },
  ['cat-i-cc-activation']: { id: 'cat-i-cc-activation', type: 'item', name: 'Creative Cloud will not activate', description: 'The app says the licence expired, or sign-in loops without ever activating.', knowledgeIds: [KB.ADOBE_ACTIVATION, KB.LICENSE_POLICY], subformIds: [SF.SOFTWARE_REQUEST], popular: true, audience: 'internal', fulfillment: '2 business days' },
  ['cat-i-adobe']: { id: 'cat-i-adobe', type: 'item', name: 'No Adobe Creative Cloud seat yet', description: 'A named-user seat from the design pool, assigned before Creative Cloud will activate at all.', knowledgeIds: [KB.ADOBE_ACTIVATION, KB.LICENSE_POLICY], subformIds: [SF.SOFTWARE_REQUEST, SF.LICENSE_RENEWAL], audience: 'internal', fulfillment: '2 business days' },
  ['cat-i-cc-crash']: { id: 'cat-i-cc-crash', type: 'item', name: 'Photoshop or Illustrator crashes on launch', description: 'The splash screen appears and the app closes before a document ever opens.', audience: 'internal' },
  ['cat-i-cc-fonts']: { id: 'cat-i-cc-fonts', type: 'item', name: 'Fonts missing from a document', description: 'Type falls back to a substitute, or an activated font never finishes downloading.', audience: 'internal' },
  ['cat-i-cc-cloud-files']: { id: 'cat-i-cc-cloud-files', type: 'item', name: 'Cloud documents not syncing', description: 'Work saved on one machine is missing on another, or a file is stuck uploading.', audience: 'internal' },
  ['cat-i-cc-export']: { id: 'cat-i-cc-export', type: 'item', name: 'Export or render fails', description: 'A render that never finishes, or an export that errors within sight of the end.', audience: 'internal' },
  ['cat-i-cc-acrobat']: { id: 'cat-i-cc-acrobat', type: 'item', name: 'Acrobat will not open or edit a PDF', description: 'A PDF that opens blank, refuses an edit, or will not take a signature.', audience: 'internal' },
  ['cat-i-cc-not-listed']: { id: 'cat-i-cc-not-listed', type: 'item', name: 'Not listed', description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.', audience: 'internal' },
  ['cat-i-collab-signin']: { id: 'cat-i-collab-signin', type: 'item', name: 'Cannot sign in to the Slack workspace', description: 'The invite expired, the workspace is not listed, or SSO refuses the account.', knowledgeIds: [KB.SSO_EXPLAINED], subformIds: [SF.REPORT_SIGNIN], audience: 'internal', fulfillment: 'Same day' },
  ['cat-i-collab-audio']: { id: 'cat-i-collab-audio', type: 'item', name: 'Zoom or Slack call has no sound or video', description: 'The wrong microphone is selected, or the camera is held by another app.', popular: true, audience: 'internal' },
  ['cat-i-collab-share']: { id: 'cat-i-collab-share', type: 'item', name: 'Screen share not working', description: 'The share button greys out, or attendees see a black rectangle where the screen should be.', audience: 'internal' },
  ['cat-i-collab-notifications']: { id: 'cat-i-collab-notifications', type: 'item', name: 'Notifications not arriving', description: 'Mentions never surface on desktop or phone, so messages sit unread for hours.', audience: 'internal' },
  ['cat-i-collab-guest']: { id: 'cat-i-collab-guest', type: 'item', name: 'External guest cannot join', description: 'A customer or partner blocked at the door of a channel or a meeting.', knowledgeIds: [KB.SSO_EXPLAINED], subformIds: [SF.REQUEST_ACCESS], audience: 'internal' },
  ['cat-i-collab-recording']: { id: 'cat-i-collab-recording', type: 'item', name: 'Recording or transcript missing', description: 'A meeting that was recorded and never appeared afterwards.', audience: 'internal' },
  ['cat-i-collab-not-listed']: { id: 'cat-i-collab-not-listed', type: 'item', name: 'Not listed', description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.', audience: 'internal' },
  ['cat-i-web-not-loading']: { id: 'cat-i-web-not-loading', type: 'item', name: 'Page not loading or showing errors', description: 'A blank tab, a spinner that never stops, or an error the page will not explain.', popular: true, audience: 'internal' },
  ['cat-i-web-session-drop']: { id: 'cat-i-web-session-drop', type: 'item', name: 'Signed out of a site over and over', description: 'You sign in, work for a few minutes, and the site drops the session again.', knowledgeIds: [KB.SSO_EXPLAINED, KB.RESET_PASSWORD], subformIds: [SF.REPORT_SIGNIN], audience: 'internal' },
  ['cat-i-web-blocked']: { id: 'cat-i-web-blocked', type: 'item', name: 'Site blocked or warned as unsafe', description: 'The browser stops on a certificate or policy warning before the page loads.', audience: 'internal' },
  ['cat-i-web-extension']: { id: 'cat-i-web-extension', type: 'item', name: 'Extension or add-in stopped working', description: 'A browser tool that vanished after an update, or now errors on every page.', knowledgeIds: [KB.INSTALL_SOFTWARE], subformIds: [SF.SOFTWARE_REQUEST], audience: 'internal', fulfillment: '1-2 business days' },
  ['cat-i-web-transfer']: { id: 'cat-i-web-transfer', type: 'item', name: 'Downloads or uploads failing', description: 'A file that stops part-way, or an upload the site rejects without saying why.', audience: 'internal' },
  ['cat-i-web-slow']: { id: 'cat-i-web-slow', type: 'item', name: 'Browser slow, freezing or crashing', description: 'Tabs hang, the window goes white, or the browser restarts on its own.', audience: 'internal' },
  ['cat-i-web-not-listed']: { id: 'cat-i-web-not-listed', type: 'item', name: 'Not listed', description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.', audience: 'internal' },
  ['cat-i-lob-signin']: { id: 'cat-i-lob-signin', type: 'item', name: 'Cannot sign in to a line-of-business app', description: 'NetSuite, Workday or the warehouse system refusing the account outright.', knowledgeIds: [KB.SSO_EXPLAINED, KB.ACCOUNT_LOCKED], subformIds: [SF.REPORT_SIGNIN], audience: 'internal', fulfillment: 'Same day' },
  ['cat-i-lob-permissions']: { id: 'cat-i-lob-permissions', type: 'item', name: 'The screen you need is missing from the app', description: 'The app opens, but the menu or screen the job depends on is not there for your account.', knowledgeIds: [KB.SSO_EXPLAINED], subformIds: [SF.REQUEST_ACCESS], audience: 'internal' },
  ['cat-i-lob-error']: { id: 'cat-i-lob-error', type: 'item', name: 'Error on a routine task', description: 'A step that worked yesterday now fails with a message nobody recognises.', audience: 'internal' },
  ['cat-i-lob-integration']: { id: 'cat-i-lob-integration', type: 'item', name: 'Overnight job or interface did not run', description: 'A scheduled job that never fired, leaving the next team with yesterday’s data.', knowledgeIds: [KB.API_KEYS, KB.CHANGE_PROCESS], audience: 'internal' },
  ['cat-i-lob-print']: { id: 'cat-i-lob-print', type: 'item', name: 'Documents or labels not printing from the app', description: 'Invoices, pick lists or shipping labels that never reach the printer.', knowledgeIds: [KB.INSTALL_SOFTWARE], subformIds: [SF.FACILITIES_ISSUE], audience: 'internal' },
  ['cat-i-lob-slow']: { id: 'cat-i-lob-slow', type: 'item', name: 'App slow or unavailable', description: 'Screens that take minutes, or a system nobody in the team can reach at all.', knowledgeIds: [KB.ESCALATION_PATHS], audience: 'internal', fulfillment: 'Same day triage' },
  ['cat-i-lob-not-listed']: { id: 'cat-i-lob-not-listed', type: 'item', name: 'Not listed', description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.', audience: 'internal' },
  [CAT.I_SOFTWARE_REQ]: { id: CAT.I_SOFTWARE_REQ, type: 'item', name: 'Software you need is not installed', description: 'Anything in the self-service catalogue installs immediately; everything else routes for review.', knowledgeIds: [KB.INSTALL_SOFTWARE, KB.LICENSE_POLICY], subformIds: [SF.SOFTWARE_REQUEST], popular: true, audience: 'internal', fulfillment: '1-2 business days' },
  ['cat-i-install-blocked']: { id: 'cat-i-install-blocked', type: 'item', name: 'Install blocked by policy', description: 'Self-Service refuses the app, or the installer wants rights the account does not have.', knowledgeIds: [KB.INSTALL_SOFTWARE, KB.APPROVAL_THRESHOLDS], subformIds: [SF.SOFTWARE_REQUEST], audience: 'internal' },
  ['cat-i-os-updates']: { id: 'cat-i-os-updates', type: 'item', name: 'Update will not install', description: 'A patch that fails every attempt, or a machine stuck asking to restart for a week.', knowledgeIds: [KB.INSTALL_SOFTWARE, KB.CHANGE_PROCESS], subformIds: [SF.SOFTWARE_REQUEST], audience: 'internal' },
  ['cat-i-uninstall']: { id: 'cat-i-uninstall', type: 'item', name: 'Software no longer needed', description: 'An app nobody uses, removed so the seat can be reclaimed before the renewal date.', knowledgeIds: [KB.LICENSE_POLICY, KB.RETURN_EQUIPMENT], subformIds: [SF.SOFTWARE_REQUEST], audience: 'internal' },
  ['cat-i-update-broke-app']: { id: 'cat-i-update-broke-app', type: 'item', name: 'App broken after an update', description: 'An app that worked last week now crashes or will not open since it updated.', subformIds: [SF.SOFTWARE_REQUEST] },
  ['cat-i-install-not-listed']: { id: 'cat-i-install-not-listed', type: 'item', name: 'Not listed', description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.', subformIds: [SF.SOFTWARE_REQUEST], audience: 'internal' },
  ['cat-i-license-expired']: { id: 'cat-i-license-expired', type: 'item', name: 'Licence expired or seat revoked', description: 'The app opens read-only, asks you to buy, or says the subscription ended.', knowledgeIds: [KB.LICENSE_POLICY, KB.ADOBE_ACTIVATION], subformIds: [SF.LICENSE_RENEWAL], popular: true, audience: 'internal', fulfillment: '1 business day' },
  ['cat-i-new-license']: { id: 'cat-i-new-license', type: 'item', name: 'Need a tool Northwind has not bought yet', description: 'A tool nobody has bought yet — needs security review, budget owner sign-off and a renewal date.', knowledgeIds: [KB.LICENSE_POLICY, KB.APPROVAL_THRESHOLDS], subformIds: [SF.LICENSE_RENEWAL, SF.EXPENSE_APPROVAL], audience: 'internal', fulfillment: '5 business days' },
  ['cat-i-renewal']: { id: 'cat-i-renewal', type: 'item', name: 'Renewal or true-up due', description: 'The 60-day renewal notice, seat reconciliation, and reclaiming licences from leavers.', knowledgeIds: [KB.LICENSE_POLICY, KB.RETURN_EQUIPMENT], subformIds: [SF.LICENSE_RENEWAL], audience: 'internal' },
  ['cat-i-seat-transfer']: { id: 'cat-i-seat-transfer', type: 'item', name: 'Seat needs moving to someone else', description: 'A leaver’s licence reassigned rather than bought a second time.', knowledgeIds: [KB.LICENSE_POLICY, KB.RETURN_EQUIPMENT], subformIds: [SF.LICENSE_RENEWAL], audience: 'internal' },
  ['cat-i-spend-approval']: { id: 'cat-i-spend-approval', type: 'item', name: 'Software spend needs approving', description: 'Thresholds: under $500 is a manager, $500-$5,000 adds Finance, above that adds the VP.', knowledgeIds: [KB.APPROVAL_THRESHOLDS, KB.LICENSE_POLICY], subformIds: [SF.EXPENSE_APPROVAL], audience: 'internal' },
  ['cat-i-vendor-invoice']: { id: 'cat-i-vendor-invoice', type: 'item', name: 'Vendor quote or invoice does not match', description: 'A renewal quote that differs from the contract, or an invoice for seats nobody recognises.', knowledgeIds: [KB.APPROVAL_THRESHOLDS, KB.LICENSE_POLICY], subformIds: [SF.EXPENSE_APPROVAL, SF.LICENSE_RENEWAL], audience: 'internal' },
  ['cat-i-licensing-not-listed']: { id: 'cat-i-licensing-not-listed', type: 'item', name: 'Not listed', description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.', subformIds: [SF.LICENSE_RENEWAL], audience: 'internal' },
  ['cat-i-api-credentials']: { id: 'cat-i-api-credentials', type: 'item', name: 'API key rejected or needs rotating', description: 'A key returning unauthorised, scoped to the wrong environment, or exposed and needing rotation.', knowledgeIds: [KB.API_KEYS, KB.SSO_EXPLAINED], subformIds: [SF.REQUEST_ACCESS, SF.INTEGRATION_HELP], audience: 'both', fulfillment: '1 business day' },
  ['cat-i-sandbox']: { id: 'cat-i-sandbox', type: 'item', name: 'Sandbox expired or out of date', description: 'A sandbox past its 30 days, or one whose data no longer resembles production.', knowledgeIds: [KB.CHANGE_PROCESS, KB.API_KEYS], subformIds: [SF.SOFTWARE_REQUEST, SF.INTEGRATION_HELP], audience: 'both', fulfillment: '2 business days' },
  ['cat-i-rate-limit']: { id: 'cat-i-rate-limit', type: 'item', name: 'Requests rate limited or throttled', description: 'Calls start returning 429 in the middle of a job that ran fine last month.', knowledgeIds: [KB.API_KEYS], subformIds: [SF.INTEGRATION_HELP], audience: 'both' },
  ['cat-i-repo-access']: { id: 'cat-i-repo-access', type: 'item', name: 'No access to a repository or pipeline', description: 'A push refused, a build the account cannot see, or a runner that will not start.', knowledgeIds: [KB.SSO_EXPLAINED, KB.API_KEYS], subformIds: [SF.REQUEST_ACCESS], audience: 'internal' },
  ['cat-i-local-env']: { id: 'cat-i-local-env', type: 'item', name: 'Local environment will not build', description: 'Dependencies fail to install, or the app runs everywhere except this machine.', knowledgeIds: [KB.INSTALL_SOFTWARE], subformIds: [SF.SOFTWARE_REQUEST], audience: 'internal' },
  ['cat-i-test-data']: { id: 'cat-i-test-data', type: 'item', name: 'Test data needs refreshing', description: 'A sandbox that needs realistic data, or a reset before a demo.', knowledgeIds: [KB.CHANGE_PROCESS, KB.IMPORT_CATALOG], subformIds: [SF.INTEGRATION_HELP], audience: 'both' },
  ['cat-i-dev-tooling-not-listed']: { id: 'cat-i-dev-tooling-not-listed', type: 'item', name: 'Not listed', description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.', subformIds: [SF.INTEGRATION_HELP], audience: 'both' },
  ['cat-i-apps-not-listed']: { id: 'cat-i-apps-not-listed', type: 'item', name: 'Not listed', description: 'Name the application and what it does wrong — a person reads it and routes it by hand.', audience: 'internal' },
  ['cat-i-m365-outlook-password']: { id: 'cat-i-m365-outlook-password', type: 'item', name: 'Outlook keeps asking for a password', description: 'The prompt returns every few minutes even after the password is accepted.', knowledgeIds: [KB.RESET_PASSWORD, KB.SSO_EXPLAINED], subformIds: [SF.REPORT_SIGNIN], popular: true, audience: 'internal', fulfillment: 'Same day' },
  ['cat-i-mailbox-storage']: { id: 'cat-i-mailbox-storage', type: 'item', name: 'Mailbox full', description: 'Over-quota warnings, or new mail stops arriving because the mailbox is at its limit.', knowledgeIds: [KB.SPAM_QUARANTINE, KB.EMAIL_SIGNATURE], subformIds: [SF.EMAIL_PROBLEM], audience: 'internal' },
  ['cat-i-mobile-policy']: { id: 'cat-i-mobile-policy', type: 'item', name: 'Phone blocked by the device policy', description: 'Mail refuses to connect until the phone is enrolled or a passcode is set.', knowledgeIds: [KB.EMAIL_ON_PHONE, KB.MFA_SETUP], subformIds: [SF.EMAIL_PROBLEM], audience: 'internal' },
  ['cat-i-desktop-mail-client']: { id: 'cat-i-desktop-mail-client', type: 'item', name: 'Mail profile will not set up on a new machine', description: 'Outlook or Apple Mail fails to create the profile, or offline mail never finishes downloading.', knowledgeIds: [KB.EMAIL_ON_PHONE, KB.INSTALL_SOFTWARE], subformIds: [SF.EMAIL_PROBLEM, SF.SOFTWARE_REQUEST], audience: 'internal' },
  ['cat-i-m365-copilot']: { id: 'cat-i-m365-copilot', type: 'item', name: 'Copilot missing or refusing to answer', description: 'The Copilot button is not there, or it replies that it cannot reach your files.', knowledgeIds: [KB.LICENSE_POLICY], subformIds: [SF.SOFTWARE_REQUEST], audience: 'internal' },
  ['cat-i-m365-no-licence']: { id: 'cat-i-m365-no-licence', type: 'item', name: 'Office says this product is unlicensed', description: 'An app opens read-only or refuses to start until a Microsoft 365 licence is assigned.', subformIds: [SF.SOFTWARE_REQUEST] },
  ['cat-i-m365-account-not-listed']: { id: 'cat-i-m365-account-not-listed', type: 'item', name: 'Not listed', description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.' },
  ['cat-i-m365-onedrive-sync']: { id: 'cat-i-m365-onedrive-sync', type: 'item', name: 'OneDrive not syncing', description: 'The sync icon spins forever, or a file saved this morning is not on the other machine.', popular: true, audience: 'internal' },
  ['cat-i-m365-files-missing']: { id: 'cat-i-m365-files-missing', type: 'item', name: 'Files missing or deleted from SharePoint', description: 'A folder that emptied, a document nobody admits to moving, or a library that vanished from a site.', audience: 'internal', fulfillment: 'Same day' },
  ['cat-i-m365-permissions']: { id: 'cat-i-m365-permissions', type: 'item', name: 'No permission to a file or site', description: 'A document opens read-only, or a SharePoint site answers that you do not have permission.', knowledgeIds: [KB.SSO_EXPLAINED], subformIds: [SF.REQUEST_ACCESS], audience: 'internal' },
  ['cat-i-m365-sharing-link']: { id: 'cat-i-m365-sharing-link', type: 'item', name: 'Sharing link will not open for someone outside Northwind', description: 'An external guest hits a sign-in wall or an access-denied page from a link you sent.', subformIds: [SF.REQUEST_ACCESS] },
  ['cat-i-m365-file-locked']: { id: 'cat-i-m365-file-locked', type: 'item', name: 'File locked by someone else', description: 'A document opens read-only because it is checked out or still open on another machine.' },
  ['cat-i-m365-onedrive-space']: { id: 'cat-i-m365-onedrive-space', type: 'item', name: 'OneDrive is out of storage' },
  ['cat-i-m365-files-not-listed']: { id: 'cat-i-m365-files-not-listed', type: 'item', name: 'Not listed', description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.' },
  ['cat-i-m365-office-crash']: { id: 'cat-i-m365-office-crash', type: 'item', name: 'Word or Excel crashes or loses work', description: 'The app closes mid-edit, a file will not open, or autosave lost the last hour.', audience: 'internal' },
  ['cat-i-m365-office-autosave']: { id: 'cat-i-m365-office-autosave', type: 'item', name: 'AutoSave overwrote work you wanted back', description: 'Changes saved over the version you needed, or AutoSave is greyed out entirely.' },
  ['cat-i-m365-office-coauthor']: { id: 'cat-i-m365-office-coauthor', type: 'item', name: 'Co-authoring left conflicting copies of a document', description: 'Two people edited at once and the file split into duplicate versions.' },
  ['cat-i-m365-office-template']: { id: 'cat-i-m365-office-template', type: 'item', name: 'Company template or branding missing', description: 'The Northwind template does not appear when starting a new document or deck.' },
  ['cat-i-m365-office-addin']: { id: 'cat-i-m365-office-addin', type: 'item', name: 'Add-in missing or disabled in Word or Excel', subformIds: [SF.SOFTWARE_REQUEST] },
  ['cat-i-m365-office-macro']: { id: 'cat-i-m365-office-macro', type: 'item', name: 'Macros blocked in a workbook', description: 'A spreadsheet that used to run its macros now opens with them disabled.' },
  ['cat-i-m365-office-not-listed']: { id: 'cat-i-m365-office-not-listed', type: 'item', name: 'Not listed', description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.' },
  ['cat-i-email-not-working']: { id: 'cat-i-email-not-working', type: 'item', name: 'Email not sending or receiving', description: 'Messages stuck in the outbox, or a mailbox that has stopped syncing in either direction.', knowledgeIds: [KB.SPAM_QUARANTINE, KB.EMAIL_ON_PHONE], subformIds: [SF.EMAIL_PROBLEM], popular: true, audience: 'internal', fulfillment: 'Same day' },
  ['cat-i-email-on-phone']: { id: 'cat-i-email-on-phone', type: 'item', name: 'Mail not syncing on a phone or tablet', description: 'The profile will not install, the app keeps asking to sign in, or new mail stops arriving on mobile.', knowledgeIds: [KB.EMAIL_ON_PHONE, KB.MFA_SETUP], subformIds: [SF.EMAIL_PROBLEM], popular: true, audience: 'internal' },
  ['cat-i-m365-teams-call']: { id: 'cat-i-m365-teams-call', type: 'item', name: 'Teams call has no sound or video', description: 'Nobody can hear you, the camera never starts, or a screen share shows a black window.', popular: true, audience: 'internal' },
  ['cat-i-quarantine']: { id: 'cat-i-quarantine', type: 'item', name: 'Message held as spam', description: 'A message you were expecting is sitting in quarantine instead of your inbox.', knowledgeIds: [KB.SPAM_QUARANTINE], subformIds: [SF.EMAIL_PROBLEM], audience: 'internal' },
  ['cat-i-email-bounce']: { id: 'cat-i-email-bounce', type: 'item', name: 'Message bounced back', description: 'A single message returned undelivered, with a failure notice from the recipient’s server.', knowledgeIds: [KB.SPAM_QUARANTINE], subformIds: [SF.EMAIL_PROBLEM], audience: 'internal' },
  ['cat-i-email-missing']: { id: 'cat-i-email-missing', type: 'item', name: 'Mail missing or deleted', description: 'A folder that emptied itself, a rule filing mail somewhere unexpected, or a message that vanished.', knowledgeIds: [KB.SPAM_QUARANTINE, KB.EMAIL_SIGNATURE], subformIds: [SF.EMAIL_PROBLEM], audience: 'internal' },
  ['cat-i-phishing']: { id: 'cat-i-phishing', type: 'item', name: 'Suspicious or phishing email', description: 'A message asking for credentials or a payment. Report it here, do not forward it on.', knowledgeIds: [KB.SPAM_QUARANTINE, KB.ACCOUNT_LOCKED], subformIds: [SF.EMAIL_PROBLEM], audience: 'internal', fulfillment: 'Immediate' },
  ['cat-i-mail-search']: { id: 'cat-i-mail-search', type: 'item', name: 'Search returns nothing in the mail client', description: 'A message you can see in the folder does not come back from search.', subformIds: [SF.EMAIL_PROBLEM], audience: 'internal' },
  ['cat-i-email-signature']: { id: 'cat-i-email-signature', type: 'item', name: 'Signature missing or wrong', description: 'The approved block never applied, or replies go out with a title from two roles ago.', knowledgeIds: [KB.EMAIL_SIGNATURE], subformIds: [SF.EMAIL_PROBLEM], audience: 'internal' },
  ['cat-i-calendar-sync']: { id: 'cat-i-calendar-sync', type: 'item', name: 'Calendar not syncing between devices', description: 'Events missing on the phone, or an invite you accepted that never appears.', knowledgeIds: [KB.EMAIL_ON_PHONE], subformIds: [SF.EMAIL_PROBLEM], audience: 'internal' },
  ['cat-i-shared-calendar']: { id: 'cat-i-shared-calendar', type: 'item', name: 'Cannot see a shared calendar', description: 'A colleague shared a calendar and it opens empty, greyed out, or not at all.', knowledgeIds: [KB.EMAIL_SIGNATURE], subformIds: [SF.EMAIL_PROBLEM], audience: 'internal' },
  ['cat-i-invite-missing']: { id: 'cat-i-invite-missing', type: 'item', name: 'Meeting invite never arrived', description: 'An invite sent to a list or an external guest that nobody received.', knowledgeIds: [KB.SPAM_QUARANTINE], subformIds: [SF.EMAIL_PROBLEM], audience: 'internal' },
  ['cat-i-out-of-office']: { id: 'cat-i-out-of-office', type: 'item', name: 'Out-of-office or delegate not working', description: 'Automatic replies never fire, or a delegate cannot send on your behalf.', knowledgeIds: [KB.EMAIL_SIGNATURE], subformIds: [SF.EMAIL_PROBLEM], audience: 'internal' },
  ['cat-i-distribution-list']: { id: 'cat-i-distribution-list', type: 'item', name: 'Distribution list missing people or refusing senders', description: 'Mail to a team list skips members, or a sender outside Northwind is bounced.', knowledgeIds: [KB.EMAIL_SIGNATURE, KB.APPROVAL_THRESHOLDS], subformIds: [SF.DISTRIBUTION_LIST], audience: 'internal', fulfillment: '1 business day' },
  ['cat-i-room-booking']: { id: 'cat-i-room-booking', type: 'item', name: 'Room shows free but is taken', description: 'Room calendars out of step with the panel at the door, or a booking that will not release.', knowledgeIds: [KB.EMAIL_SIGNATURE], subformIds: [SF.FACILITIES_ISSUE], audience: 'internal' },
  ['cat-i-room-kit']: { id: 'cat-i-room-kit', type: 'item', name: 'Video kit in the room not working', description: 'No display, no camera, or the room will not join the meeting on the screen.', subformIds: [SF.FACILITIES_ISSUE], audience: 'internal', fulfillment: 'Same day' },
  ['cat-i-m365-teams-recording']: { id: 'cat-i-m365-teams-recording', type: 'item', name: 'Teams meeting recording or transcript missing', description: 'The recording never appeared after the meeting, or the transcript is empty.' },
  ['cat-i-mail-delivery-not-listed']: { id: 'cat-i-mail-delivery-not-listed', type: 'item', name: 'Not listed', description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.', subformIds: [SF.EMAIL_PROBLEM], audience: 'internal' },
  ['cat-i-m365-not-listed']: { id: 'cat-i-m365-not-listed', type: 'item', name: 'Not listed', description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.', audience: 'internal' },
  [CAT.I_CANNOT_SIGN_IN]: { id: CAT.I_CANNOT_SIGN_IN, type: 'item', name: 'Cannot sign in', description: 'The password is refused at the sign-in page, on a machine or an app that worked yesterday.', knowledgeIds: [KB.RESET_PASSWORD, KB.ACCOUNT_LOCKED], subformIds: [SF.REPORT_SIGNIN], popular: true, audience: 'internal', fulfillment: 'Same day' },
  [CAT.I_MFA]: { id: CAT.I_MFA, type: 'item', name: 'Multi-factor code not arriving', description: 'The push never lands, the code is rejected, or the authenticator went with the old phone.', knowledgeIds: [KB.MFA_SETUP, KB.ACCOUNT_LOCKED], subformIds: [SF.MFA_RESET], popular: true, audience: 'internal', fulfillment: '2 hours' },
  ['cat-i-account-locked']: { id: 'cat-i-account-locked', type: 'item', name: 'Locked out after too many attempts', description: 'Repeated failed sign-ins, an expired contractor account, or a security hold after a phishing report.', knowledgeIds: [KB.ACCOUNT_LOCKED, KB.MFA_SETUP], subformIds: [SF.REPORT_SIGNIN], audience: 'internal', fulfillment: '1 hour' },
  ['cat-i-password-policy']: { id: 'cat-i-password-policy', type: 'item', name: 'Password change rejected', description: 'The new password will not save, or something still wants the old one hours after it changed.', knowledgeIds: [KB.RESET_PASSWORD, KB.SSO_EXPLAINED], subformIds: [SF.REPORT_SIGNIN], audience: 'internal' },
  ['cat-i-sso']: { id: 'cat-i-sso', type: 'item', name: 'Single sign-on loops back to login', description: 'The app bounces between the Northwind sign-in and its own login screen, or asks for a separate password.', knowledgeIds: [KB.SSO_EXPLAINED, KB.RESET_PASSWORD], subformIds: [SF.REPORT_SIGNIN], audience: 'both' },
  ['cat-i-passkey']: { id: 'cat-i-passkey', type: 'item', name: 'Passkey or security key not recognised', description: 'The sign-in never offers the passkey, or the key reads as unregistered on a new machine.', knowledgeIds: [KB.MFA_SETUP, KB.SSO_EXPLAINED], subformIds: [SF.REPORT_SIGNIN], audience: 'internal' },
  ['cat-i-signin-wrong-account']: { id: 'cat-i-signin-wrong-account', type: 'item', name: 'Signed in as the wrong account', description: 'The browser keeps resuming a personal or an old account, so everything shows the wrong data.', knowledgeIds: [KB.SSO_EXPLAINED], subformIds: [SF.REPORT_SIGNIN], audience: 'internal' },
  ['cat-i-signin-not-listed']: { id: 'cat-i-signin-not-listed', type: 'item', name: 'Not listed', description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.', subformIds: [SF.REPORT_SIGNIN], audience: 'internal' },
  ['cat-i-request-app']: { id: 'cat-i-request-app', type: 'item', name: 'No access to an application yet', description: 'Salesforce, NetSuite, Looker, the data warehouse — anything that needs a manager approval before provisioning.', knowledgeIds: [KB.SSO_EXPLAINED, KB.APPROVAL_THRESHOLDS], subformIds: [SF.REQUEST_ACCESS], popular: true, audience: 'internal', fulfillment: '1-2 business days' },
  ['cat-i-access-denied']: { id: 'cat-i-access-denied', type: 'item', name: 'Access denied inside an app you already use', description: 'Signed in fine, but a tab, record or report answers that you are not permitted.', knowledgeIds: [KB.SSO_EXPLAINED], subformIds: [SF.REQUEST_ACCESS], audience: 'internal' },
  ['cat-i-access-lost']: { id: 'cat-i-access-lost', type: 'item', name: 'Access disappeared after a role change', description: 'Permissions that worked last week are gone since a move, a promotion or a new manager.', knowledgeIds: [KB.SSO_EXPLAINED, KB.APPROVAL_THRESHOLDS], subformIds: [SF.REQUEST_ACCESS], audience: 'internal' },
  ['cat-i-shared-mailbox-access']: { id: 'cat-i-shared-mailbox-access', type: 'item', name: 'Cannot open a shared mailbox or group', description: 'support@ or billing@ is missing from Outlook, or send-as is refused when you reply.', knowledgeIds: [KB.EMAIL_SIGNATURE], subformIds: [SF.REQUEST_ACCESS, SF.DISTRIBUTION_LIST], audience: 'internal', fulfillment: '1 business day' },
  ['cat-i-elevated-rights']: { id: 'cat-i-elevated-rights', type: 'item', name: 'Blocked without admin rights', description: 'An install, a production console or a break-glass account. Always time-boxed and always approved.', knowledgeIds: [KB.APPROVAL_THRESHOLDS, KB.CHANGE_PROCESS], subformIds: [SF.REQUEST_ACCESS], audience: 'internal', fulfillment: '2 business days' },
  ['cat-i-access-approval-stuck']: { id: 'cat-i-access-approval-stuck', type: 'item', name: 'Access request stuck waiting for approval', description: 'The request is sitting with an approver who has not acted, or went to the wrong one entirely.', knowledgeIds: [KB.APPROVAL_THRESHOLDS], subformIds: [SF.REQUEST_ACCESS], audience: 'internal' },
  ['cat-i-app-access-not-listed']: { id: 'cat-i-app-access-not-listed', type: 'item', name: 'Not listed', description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.', subformIds: [SF.REQUEST_ACCESS], audience: 'internal' },
  ['cat-i-directory-profile']: { id: 'cat-i-directory-profile', type: 'item', name: 'Name or title wrong in the directory', description: 'A legal or preferred name, job title, manager, desk or pronouns that never caught up.', knowledgeIds: [KB.EMAIL_SIGNATURE, KB.ONBOARDING_CHECKLIST], subformIds: [SF.REQUEST_ACCESS], audience: 'internal', fulfillment: '1 business day' },
  ['cat-i-name-change']: { id: 'cat-i-name-change', type: 'item', name: 'Name change not reflected in mail or sign-in', description: 'The directory shows the new name, but mail, Teams and the sign-in page still show the old one.', knowledgeIds: [KB.EMAIL_SIGNATURE, KB.SSO_EXPLAINED], subformIds: [SF.EMAIL_PROBLEM], audience: 'internal' },
  ['cat-i-contractor-account']: { id: 'cat-i-contractor-account', type: 'item', name: 'Contractor account expired or missing', description: 'A partner cannot sign in because the end date passed, or the account was never created.', knowledgeIds: [KB.SSO_EXPLAINED, KB.ONBOARDING_CHECKLIST], subformIds: [SF.NEW_HIRE, SF.REQUEST_ACCESS], audience: 'internal', fulfillment: '3 business days' },
  ['cat-i-wrong-manager']: { id: 'cat-i-wrong-manager', type: 'item', name: 'Approvals going to the wrong manager', description: 'Requests land with a previous manager because the reporting chain is stale.', knowledgeIds: [KB.APPROVAL_THRESHOLDS, KB.ONBOARDING_CHECKLIST], subformIds: [SF.REQUEST_ACCESS], audience: 'internal' },
  ['cat-i-duplicate-account']: { id: 'cat-i-duplicate-account', type: 'item', name: 'Duplicate or leftover account', description: 'Two records for one person, or an old account still live after a rehire.', knowledgeIds: [KB.ACCOUNT_LOCKED, KB.SSO_EXPLAINED], subformIds: [SF.REPORT_SIGNIN], audience: 'internal' },
  ['cat-i-missing-from-group']: { id: 'cat-i-missing-from-group', type: 'item', name: 'Missing from a team or group', description: 'The person is absent from the directory group that drives access and mailing lists.', knowledgeIds: [KB.EMAIL_SIGNATURE, KB.SSO_EXPLAINED], subformIds: [SF.DISTRIBUTION_LIST, SF.REQUEST_ACCESS], audience: 'internal' },
  ['cat-i-identity-not-listed']: { id: 'cat-i-identity-not-listed', type: 'item', name: 'Not listed', description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.', subformIds: [SF.REQUEST_ACCESS], audience: 'internal' },
  ['cat-i-vpn-not-connecting']: { id: 'cat-i-vpn-not-connecting', type: 'item', name: 'VPN will not connect', description: 'The client hangs at connecting, or drops the moment it authenticates.', subformIds: [SF.REPORT_SIGNIN] },
  ['cat-i-wifi-weak-in-one-area']: { id: 'cat-i-wifi-weak-in-one-area', type: 'item', name: 'Wi-Fi weak or dropping in one room', description: 'Fine everywhere else, unusable in one meeting room or corner of the floor.' },
  ['cat-i-dead-network-port']: { id: 'cat-i-dead-network-port', type: 'item', name: 'Dead network port at the desk', description: 'Nothing comes up when a cable goes into the wall socket.', subformIds: [SF.FACILITIES_ISSUE] },
  ['cat-i-dns-not-resolving']: { id: 'cat-i-dns-not-resolving', type: 'item', name: 'Sites will not load though the network is up', description: 'Names fail to resolve while the connection itself looks connected.' },
  ['cat-i-guest-wifi']: { id: 'cat-i-guest-wifi', type: 'item', name: 'Visitor cannot get on guest Wi-Fi', description: 'The guest code is refused, or the sign-in page never appears.' },
  ['cat-i-office-offline']: { id: 'cat-i-office-offline', type: 'item', name: 'Whole floor or office is offline' },
  ['cat-i-network-not-listed']: { id: 'cat-i-network-not-listed', type: 'item', name: 'Not listed', description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.' },
  /* Facilities' own leaf for the same door. Security owns badge RIGHTS; the
   * building team owns the door itself, and they are different tickets. */
  ['cat-i-badge-door']: { id: 'cat-i-badge-door', type: 'item', name: 'Door or badge reader not working', description: 'The reader is dead, the door will not release, or it opens for nobody.', subformIds: [SF.FACILITIES_ISSUE], audience: 'internal', copyOf: 'cat-i-badge-access' },
  ['cat-i-badge-access']: { id: 'cat-i-badge-access', type: 'item', name: 'Badge not opening a door', description: 'A new badge, a lost one, or access that stops at the Elk Grove data-centre door.', knowledgeIds: [KB.ACCOUNT_LOCKED, KB.APPROVAL_THRESHOLDS], subformIds: [SF.REQUEST_ACCESS, SF.FACILITIES_ISSUE], audience: 'internal', fulfillment: '1 business day' },
  ['cat-i-badge-reader-dead']: { id: 'cat-i-badge-reader-dead', type: 'item', name: 'Badge reader dead at a door', description: 'No light and no beep for anyone, not just one badge.', subformIds: [SF.FACILITIES_ISSUE] },
  ['cat-i-badge-lost']: { id: 'cat-i-badge-lost', type: 'item', name: 'Badge lost or stolen', description: 'Needs deactivating now and a replacement issued.', subformIds: [SF.FACILITIES_ISSUE, SF.REQUEST_ACCESS] },
  ['cat-i-door-not-latching']: { id: 'cat-i-door-not-latching', type: 'item', name: 'Door not latching or propped open', subformIds: [SF.FACILITIES_ISSUE] },
  ['cat-i-door-alarm']: { id: 'cat-i-door-alarm', type: 'item', name: 'Door alarm sounding and will not stop', subformIds: [SF.FACILITIES_ISSUE] },
  ['cat-i-tailgating']: { id: 'cat-i-tailgating', type: 'item', name: 'Someone on the floor without a badge', description: 'Tailgated in behind a badged person, or unescorted in a restricted area.', subformIds: [SF.FACILITIES_ISSUE] },
  ['cat-i-camera-offline']: { id: 'cat-i-camera-offline', type: 'item', name: 'Security camera offline or pointed the wrong way', subformIds: [SF.FACILITIES_ISSUE] },
  ['cat-i-physical-security-not-listed']: { id: 'cat-i-physical-security-not-listed', type: 'item', name: 'Not listed', description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.', subformIds: [SF.FACILITIES_ISSUE] },
  ['cat-i-comms-room-beeping']: { id: 'cat-i-comms-room-beeping', type: 'item', name: 'Something beeping in the comms room', description: 'A steady alarm from a network closet or server room, source unknown.', subformIds: [SF.FACILITIES_ISSUE] },
  ['cat-i-ups-on-battery']: { id: 'cat-i-ups-on-battery', type: 'item', name: 'UPS on battery or showing a fault light', subformIds: [SF.FACILITIES_ISSUE] },
  ['cat-i-comms-room-hot']: { id: 'cat-i-comms-room-hot', type: 'item', name: 'Comms room is hot', description: 'The room is noticeably warm or the cooling has stopped.', subformIds: [SF.FACILITIES_ISSUE] },
  ['cat-i-switch-red-light']: { id: 'cat-i-switch-red-light', type: 'item', name: 'Switch or access point showing red or no lights', subformIds: [SF.FACILITIES_ISSUE] },
  ['cat-i-cable-unplugged']: { id: 'cat-i-cable-unplugged', type: 'item', name: 'Cable pulled out or kit unplugged', description: 'A patch lead out of the panel, or something switched off at the socket.', subformIds: [SF.FACILITIES_ISSUE] },
  ['cat-i-comms-cabinet-open']: { id: 'cat-i-comms-cabinet-open', type: 'item', name: 'Comms cabinet left open or unlocked', subformIds: [SF.FACILITIES_ISSUE] },
  ['cat-i-closet-not-listed']: { id: 'cat-i-closet-not-listed', type: 'item', name: 'Not listed', description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.', subformIds: [SF.FACILITIES_ISSUE] },
  ['cat-i-accounts-not-listed']: { id: 'cat-i-accounts-not-listed', type: 'item', name: 'Not listed', description: 'Describe the problem in your own words — a person reads it and routes it by hand.', subformIds: [SF.REPORT_SIGNIN], audience: 'internal' },
  ['cat-i-facilities-issue']: { id: 'cat-i-facilities-issue', type: 'item', name: 'Something in the building is broken', description: 'A leak, a broken chair, a door that will not shut — anything about the physical space.', subformIds: [SF.FACILITIES_ISSUE], popular: true, audience: 'internal', fulfillment: 'Same day' },
  ['cat-i-comfort']: { id: 'cat-i-comfort', type: 'item', name: 'Too hot, too cold or no lighting', description: 'A floor that never settles, a dead light, or a room nobody can sit in for an hour.', subformIds: [SF.FACILITIES_ISSUE], audience: 'internal' },
  ['cat-i-desk-move']: { id: 'cat-i-desk-move', type: 'item', name: 'Desk or seating needs changing', description: 'Move a person or a whole team. Includes monitor arms, cable runs and the floor-plan update.', knowledgeIds: [KB.REQUEST_MONITOR], subformIds: [SF.FACILITIES_ISSUE], audience: 'internal', fulfillment: '3 business days' },
  ['cat-i-supplies']: { id: 'cat-i-supplies', type: 'item', name: 'Supplies or kitchen stock run out', description: 'Stationery, coffee, cleaning after a spill, or a fridge nobody has emptied.', subformIds: [SF.FACILITIES_ISSUE], audience: 'internal' },
  ['cat-i-parking-deliveries']: { id: 'cat-i-parking-deliveries', type: 'item', name: 'Parking, bike store or a delivery needs arranging', description: 'A space for the week, access to the bike store, or a delivery that needs signing for.', subformIds: [SF.FACILITIES_ISSUE], audience: 'internal' },
  ['cat-i-building-not-listed']: { id: 'cat-i-building-not-listed', type: 'item', name: 'Not listed', description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.', subformIds: [SF.FACILITIES_ISSUE], audience: 'internal' },
  ['cat-i-new-hire']: { id: 'cat-i-new-hire', type: 'item', name: 'New hire starting', description: 'One request produces the account, the laptop, the badge, the seat and the first-week curriculum.', knowledgeIds: [KB.ONBOARDING_CHECKLIST, KB.LAPTOP_SETUP, KB.MFA_SETUP], subformIds: [SF.NEW_HIRE], popular: true, audience: 'internal', fulfillment: 'Start date - 5 days' },
  ['cat-i-starter-not-ready']: { id: 'cat-i-starter-not-ready', type: 'item', name: 'New starter has no account or laptop on day one', description: 'The start date arrived before the kit or the accounts did.', knowledgeIds: [KB.ONBOARDING_CHECKLIST, KB.LAPTOP_SETUP], subformIds: [SF.NEW_HIRE], audience: 'internal', fulfillment: 'Same day' },
  ['cat-i-contractor-onboarding']: { id: 'cat-i-contractor-onboarding', type: 'item', name: 'Contractor starting', description: 'A lighter onboarding with a mandatory end date and no default building access.', knowledgeIds: [KB.ONBOARDING_CHECKLIST, KB.SSO_EXPLAINED], subformIds: [SF.NEW_HIRE], audience: 'internal', fulfillment: '3 business days' },
  ['cat-i-role-change']: { id: 'cat-i-role-change', type: 'item', name: 'Someone is moving role or team', description: 'Access that should follow the person, access that should not, and the manager-chain update.', knowledgeIds: [KB.ONBOARDING_CHECKLIST, KB.APPROVAL_THRESHOLDS], subformIds: [SF.NEW_HIRE, SF.REQUEST_ACCESS], audience: 'internal' },
  ['cat-i-offboarding']: { id: 'cat-i-offboarding', type: 'item', name: 'Someone is leaving', description: 'Disable access at the right hour, recover equipment, reassign owned records, reclaim licences.', knowledgeIds: [KB.RETURN_EQUIPMENT, KB.ONBOARDING_CHECKLIST, KB.LICENSE_POLICY], subformIds: [SF.OFFBOARDING, SF.RETURN_HARDWARE], audience: 'internal', fulfillment: 'Last day' },
  ['cat-i-leaver-access']: { id: 'cat-i-leaver-access', type: 'item', name: 'A leaver still has access', description: 'An account, badge or licence that survived the last day and should not have.', knowledgeIds: [KB.RETURN_EQUIPMENT, KB.ACCOUNT_LOCKED], subformIds: [SF.OFFBOARDING], audience: 'internal', fulfillment: 'Immediate' },
  ['cat-i-joining-not-listed']: { id: 'cat-i-joining-not-listed', type: 'item', name: 'Not listed', description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.', subformIds: [SF.NEW_HIRE], audience: 'internal' },
  ['cat-i-working-a-queue']: { id: 'cat-i-working-a-queue', type: 'item', name: 'Not sure how to work the queue', description: 'Triage order, what a good first response looks like, and the macros that save the most typing.', knowledgeIds: [KB.TRIAGE_BASICS, KB.READING_A_TICKET, KB.USING_MACROS], audience: 'internal' },
  ['cat-i-customer-comms']: { id: 'cat-i-customer-comms', type: 'item', name: 'Not sure what to say to a customer', description: 'Tone, structure and the close. Includes the de-escalation script the Austin team wrote.', knowledgeIds: [KB.WRITING_TO_CUSTOMERS, KB.HANDLING_ANGRY, KB.CLOSING_WELL], audience: 'internal' },
  ['cat-i-escalation-sla']: { id: 'cat-i-escalation-sla', type: 'item', name: 'Not sure who to escalate to', description: 'Who to pull in, when the clock pauses, and what an Enterprise customer has actually been promised.', knowledgeIds: [KB.ESCALATION_PATHS, KB.SLA_EXPLAINED], audience: 'internal' },
  ['cat-i-wrong-queue']: { id: 'cat-i-wrong-queue', type: 'item', name: 'Work landing in the wrong queue', description: 'Tickets arriving where nobody can fix them, or bouncing between two teams.', knowledgeIds: [KB.TRIAGE_BASICS, KB.ESCALATION_PATHS], audience: 'internal' },
  ['cat-i-knowledge-gap']: { id: 'cat-i-knowledge-gap', type: 'item', name: 'No article exists for a repeat question', description: 'The same question keeps arriving and there is nothing written to send back.', knowledgeIds: [KB.READING_A_TICKET, KB.USING_MACROS], audience: 'internal' },
  ['cat-i-raise-a-change']: { id: 'cat-i-raise-a-change', type: 'item', name: 'A change needs raising', description: 'Standard, normal and emergency changes — which one you are actually raising, and who authorises it.', knowledgeIds: [KB.CHANGE_PROCESS, KB.APPROVAL_THRESHOLDS], subformIds: [SF.EXPENSE_APPROVAL], audience: 'internal' },
  ['cat-i-ways-not-listed']: { id: 'cat-i-ways-not-listed', type: 'item', name: 'Not listed', description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.', audience: 'internal' },
  ['cat-i-workplace-not-listed']: { id: 'cat-i-workplace-not-listed', type: 'item', name: 'Not listed', description: 'Describe the problem in your own words — a person reads it and routes it by hand.', subformIds: [SF.FACILITIES_ISSUE], audience: 'internal' },
  [CAT.I_STOREFRONT_SETUP]: { id: CAT.I_STOREFRONT_SETUP, type: 'item', name: 'Set up your storefront', description: 'Domain, theme, tax profile and the go-live checklist. Ten minutes if the domain is already delegated.', knowledgeIds: [KB.STOREFRONT_SETUP], subformIds: [SF.INTEGRATION_HELP], popular: true, audience: 'external' },
  ['cat-i-import-catalog']: { id: 'cat-i-import-catalog', type: 'item', name: 'Product import failed or dropped rows', description: 'Rows rejected on validation, variants collapsed into one, or images that never attached.', knowledgeIds: [KB.IMPORT_CATALOG, KB.STOREFRONT_SETUP], subformIds: [SF.INTEGRATION_HELP], popular: true, audience: 'external' },
  ['cat-i-domain']: { id: 'cat-i-domain', type: 'item', name: 'Store not loading on your own domain', description: 'The store answers on the temporary address but not on the domain you delegated.', knowledgeIds: [KB.STOREFRONT_SETUP], subformIds: [SF.INTEGRATION_HELP, SF.STOREFRONT_BUG], audience: 'external' },
  ['cat-i-invite-team']: { id: 'cat-i-invite-team', type: 'item', name: 'Team member cannot be invited or signed in', description: 'An invite that never arrives, a role with the wrong permissions, or SSO that will not connect.', knowledgeIds: [KB.STOREFRONT_SETUP, KB.SSO_EXPLAINED], subformIds: [SF.INTEGRATION_HELP], audience: 'external' },
  ['cat-i-theme']: { id: 'cat-i-theme', type: 'item', name: 'Theme renders wrong on mobile', description: 'Layout breaks at phone width, or a section disappears after a theme update.', knowledgeIds: [KB.STOREFRONT_SETUP], subformIds: [SF.STOREFRONT_BUG], audience: 'external' },
  ['cat-i-tax-shipping']: { id: 'cat-i-tax-shipping', type: 'item', name: 'Tax or shipping rates wrong at checkout', description: 'The wrong rate applied, or a region that shows no shipping option at all.', knowledgeIds: [KB.STOREFRONT_SETUP, KB.IMPORT_CATALOG], subformIds: [SF.STOREFRONT_BUG], audience: 'external' },
  ['cat-i-getting-started-not-listed']: { id: 'cat-i-getting-started-not-listed', type: 'item', name: 'Not listed', description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.', subformIds: [SF.STOREFRONT_BUG], audience: 'external' },
  [CAT.I_PAYMENTS]: { id: CAT.I_PAYMENTS, type: 'item', name: 'Payments not going through', description: 'A provider that will not connect, cards declined at checkout, or verification stuck in review.', knowledgeIds: [KB.CONNECT_PAYMENTS], subformIds: [SF.INTEGRATION_HELP, SF.STOREFRONT_BUG], popular: true, audience: 'external' },
  ['cat-i-payout-missing']: { id: 'cat-i-payout-missing', type: 'item', name: 'Payout missing or late', description: 'A settlement that has not landed, or an amount that does not match the orders behind it.', knowledgeIds: [KB.CONNECT_PAYMENTS, KB.INVOICE_QUESTIONS], subformIds: [SF.BILLING_QUESTION], audience: 'external' },
  ['cat-i-refund-dispute']: { id: 'cat-i-refund-dispute', type: 'item', name: 'Refund or chargeback problem', description: 'A refund that will not process, or a dispute raised by a shopper’s bank.', knowledgeIds: [KB.CONNECT_PAYMENTS, KB.INVOICE_QUESTIONS], subformIds: [SF.BILLING_QUESTION, SF.STOREFRONT_BUG], audience: 'external' },
  [CAT.I_BILLING]: { id: CAT.I_BILLING, type: 'item', name: 'Question about your invoice', description: 'Read your Northwind invoice, or query a line you do not recognise.', knowledgeIds: [KB.INVOICE_QUESTIONS], subformIds: [SF.BILLING_QUESTION], popular: true, audience: 'external' },
  ['cat-i-plans-seats']: { id: 'cat-i-plans-seats', type: 'item', name: 'Wrong plan or seat count', description: 'Charged for seats nobody uses, or blocked by a limit your plan should already cover.', knowledgeIds: [KB.INVOICE_QUESTIONS, KB.SLA_EXPLAINED], subformIds: [SF.BILLING_QUESTION], audience: 'external' },
  ['cat-i-billing-contact']: { id: 'cat-i-billing-contact', type: 'item', name: 'Billing contact or card needs changing', description: 'Invoices going to someone who left, or a payment method that expired.', knowledgeIds: [KB.INVOICE_QUESTIONS], subformIds: [SF.BILLING_QUESTION], audience: 'external' },
  ['cat-i-payments-not-listed']: { id: 'cat-i-payments-not-listed', type: 'item', name: 'Not listed', description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.', subformIds: [SF.BILLING_QUESTION], audience: 'external' },
  ['cat-i-storefront-api-keys']: { id: 'cat-i-storefront-api-keys', type: 'item', name: 'API key rejected', description: 'A key returning unauthorised, scoped to the wrong store, or one you need to rotate without downtime.', knowledgeIds: [KB.API_KEYS], subformIds: [SF.INTEGRATION_HELP], audience: 'external' },
  ['cat-i-api-errors']: { id: 'cat-i-api-errors', type: 'item', name: 'API returning errors', description: 'Calls that worked yesterday now come back 4xx or 5xx with no change on your side.', knowledgeIds: [KB.API_KEYS, KB.SLA_EXPLAINED], subformIds: [SF.INTEGRATION_HELP, SF.STOREFRONT_BUG], audience: 'external' },
  ['cat-i-webhooks']: { id: 'cat-i-webhooks', type: 'item', name: 'Webhooks not arriving', description: 'Order events that never reach your endpoint, or a signature that fails to verify.', knowledgeIds: [KB.WEBHOOK_SETUP, KB.API_KEYS], subformIds: [SF.INTEGRATION_HELP, SF.STOREFRONT_BUG], audience: 'external' },
  ['cat-i-orders-not-syncing']: { id: 'cat-i-orders-not-syncing', type: 'item', name: 'Orders not syncing to your system', description: 'Orders visible in the storefront but missing from your ERP or fulfilment tool.', knowledgeIds: [KB.WEBHOOK_SETUP, KB.IMPORT_CATALOG], subformIds: [SF.INTEGRATION_HELP], audience: 'external' },
  ['cat-i-inventory-sync']: { id: 'cat-i-inventory-sync', type: 'item', name: 'Inventory counts out of step', description: 'Stock levels that drift from your warehouse system, or an oversell at checkout.', knowledgeIds: [KB.IMPORT_CATALOG], subformIds: [SF.INTEGRATION_HELP, SF.STOREFRONT_BUG], audience: 'external' },
  ['cat-i-data-export']: { id: 'cat-i-data-export', type: 'item', name: 'Export missing data', description: 'A bulk export that stops short, or a scheduled report that quietly stopped running.', knowledgeIds: [KB.IMPORT_CATALOG, KB.API_KEYS], subformIds: [SF.INTEGRATION_HELP], audience: 'external' },
  ['cat-i-integrations-not-listed']: { id: 'cat-i-integrations-not-listed', type: 'item', name: 'Not listed', description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.', subformIds: [SF.INTEGRATION_HELP], audience: 'external' },
  ['cat-i-report-bug']: { id: 'cat-i-report-bug', type: 'item', name: 'Something in the storefront is broken', description: 'Anything in the admin or the store behaving wrongly. Include the store URL and what you expected.', knowledgeIds: [KB.STOREFRONT_SETUP, KB.CONNECT_PAYMENTS], subformIds: [SF.STOREFRONT_BUG], popular: true, audience: 'external' },
  ['cat-i-checkout-failing']: { id: 'cat-i-checkout-failing', type: 'item', name: 'Checkout failing for shoppers', description: 'Shoppers reach payment and the page errors, hangs or empties the basket.', knowledgeIds: [KB.CONNECT_PAYMENTS, KB.STOREFRONT_SETUP], subformIds: [SF.STOREFRONT_BUG], popular: true, audience: 'external' },
  ['cat-i-store-slow']: { id: 'cat-i-store-slow', type: 'item', name: 'Storefront slow or unavailable', description: 'Pages timing out, or the store returning an error for everyone at once.', knowledgeIds: [KB.SLA_EXPLAINED, KB.ESCALATION_PATHS], subformIds: [SF.STOREFRONT_BUG], audience: 'external' },
  ['cat-i-status-incidents']: { id: 'cat-i-status-incidents', type: 'item', name: 'No update during an outage', description: 'Where the status page lives, how incidents are communicated, and what an SLA credit is worth.', knowledgeIds: [KB.SLA_EXPLAINED, KB.ESCALATION_PATHS], subformIds: [SF.STOREFRONT_BUG], audience: 'both' },
  ['cat-i-sla-credit']: { id: 'cat-i-sla-credit', type: 'item', name: 'An incident breached your SLA', description: 'Downtime past what the contract promises, and the credit that follows from it.', knowledgeIds: [KB.SLA_EXPLAINED, KB.INVOICE_QUESTIONS], subformIds: [SF.BILLING_QUESTION], audience: 'external' },
  ['cat-i-feature-request']: { id: 'cat-i-feature-request', type: 'item', name: 'Something the product cannot do yet', description: 'Goes to the product board, not to support. You can watch the request and get the release note.', knowledgeIds: [KB.WEBHOOK_SETUP], subformIds: [SF.FEATURE_REQUEST], audience: 'external' },
  ['cat-i-problems-not-listed']: { id: 'cat-i-problems-not-listed', type: 'item', name: 'Not listed', description: 'Nothing above matches. Describe it in your own words — a person reads it and routes it by hand.', subformIds: [SF.STOREFRONT_BUG], audience: 'external' },
  ['cat-i-storefront-not-listed']: { id: 'cat-i-storefront-not-listed', type: 'item', name: 'Not listed', description: 'Describe the problem in your own words — a person reads it and routes it by hand.', subformIds: [SF.STOREFRONT_BUG], audience: 'external' },
};

/** A subcategory holds REFERENCES, so one item can appear under several. */
const sub = (id, name, description, audience, itemIds) => ({
  id,
  type: 'subcategory',
  name,
  ...(description ? { description } : {}),
  ...(audience ? { audience } : {}),
  children: itemIds.map(x => ITEMS[x]),
});

export const CATALOG = [
  {
    id: CAT.P_DEVICES,
    type: 'product',
    name: 'Devices & Hardware',
    description: 'Laptops, phones, peripherals and the return or repair loop.',
    audience: 'internal',
    children: [
      sub('cat-s-computers', 'Laptops & desktops', 'The machine itself — power, speed, screen, battery, connectivity.', null, [CAT.I_LAPTOP_ISSUE, 'cat-i-laptop-performance', 'cat-i-laptop-screen', 'cat-i-laptop-battery', 'cat-i-machine-setup', CAT.I_NEW_LAPTOP, 'cat-i-laptop-input', 'cat-i-disk-full', 'cat-i-laptop-wifi', 'cat-i-computers-not-listed']),
      sub('cat-s-peripherals', 'Peripherals & accessories', 'Monitors, docks, keyboards, headsets and what plugs into them.', null, ['cat-i-monitor', 'cat-i-desk-accessories', 'cat-i-webcam', 'cat-i-printing', 'cat-i-adapters', 'cat-i-peripheral-worn', 'cat-i-peripherals-not-listed']),
      sub('cat-s-mobile', 'Mobile devices', 'Company phones and tablets.', null, ['cat-i-lost-device', 'cat-i-phone-damaged', 'cat-i-phone-service', 'cat-i-mdm-enrolment', 'cat-i-roaming', 'cat-i-company-phone', 'cat-i-mobile-not-listed']),
      sub('cat-s-returns', 'Returns & repairs', 'Sending kit back, swapping it out, getting it fixed.', null, ['cat-i-repair-warranty', 'cat-i-loaner', 'cat-i-return-equipment', 'cat-i-return-label', 'cat-i-asset-record', 'cat-i-disposal', 'cat-i-returns-not-listed']),
      sub('cat-s-devices-not-listed', 'Not listed', 'Hardware that does not fit the shelves above.', null, ['cat-i-devices-not-listed']),
    ],
  },
  {
    id: CAT.P_APPLICATIONS,
    type: 'product',
    name: 'Applications & Software',
    description: 'The business applications Northwind runs on, and the licences behind them.',
    audience: 'internal',
    children: [
      sub('cat-s-crm', 'Salesforce & CRM', '', null, ['cat-i-crm-signin', 'cat-i-crm-permissions', 'cat-i-crm-save', 'cat-i-crm-sync', 'cat-i-crm-report', 'cat-i-crm-slow', 'cat-i-crm-not-listed']),
      sub('cat-s-creative-cloud', 'Adobe Creative Cloud', '', null, ['cat-i-cc-activation', 'cat-i-adobe', 'cat-i-cc-crash', 'cat-i-cc-fonts', 'cat-i-cc-cloud-files', 'cat-i-cc-export', 'cat-i-cc-acrobat', 'cat-i-cc-not-listed']),
      sub('cat-s-collab', 'Slack & Zoom', '', null, ['cat-i-collab-signin', 'cat-i-collab-audio', 'cat-i-collab-share', 'cat-i-collab-notifications', 'cat-i-collab-guest', 'cat-i-collab-recording', 'cat-i-collab-not-listed']),
      sub('cat-s-web-apps', 'Browsers & web apps', '', null, ['cat-i-web-not-loading', 'cat-i-web-session-drop', 'cat-i-web-blocked', 'cat-i-web-extension', 'cat-i-web-transfer', 'cat-i-web-slow', 'cat-i-web-not-listed']),
      sub('cat-s-lob-apps', 'Line-of-business apps', '', null, ['cat-i-lob-signin', 'cat-i-lob-permissions', 'cat-i-lob-error', 'cat-i-lob-integration', 'cat-i-lob-print', 'cat-i-lob-slow', 'cat-i-lob-not-listed']),
      sub('cat-s-install', 'Install & updates', '', null, [CAT.I_SOFTWARE_REQ, 'cat-i-install-blocked', 'cat-i-os-updates', 'cat-i-uninstall', 'cat-i-update-broke-app', 'cat-i-install-not-listed']),
      sub('cat-s-licensing', 'Licences & renewals', '', null, ['cat-i-license-expired', 'cat-i-new-license', 'cat-i-renewal', 'cat-i-seat-transfer', 'cat-i-spend-approval', 'cat-i-vendor-invoice', 'cat-i-licensing-not-listed']),
      sub('cat-s-dev-tooling', 'Developer tooling', '', null, ['cat-i-api-credentials', 'cat-i-sandbox', 'cat-i-rate-limit', 'cat-i-repo-access', 'cat-i-local-env', 'cat-i-test-data', 'cat-i-dev-tooling-not-listed']),
      sub('cat-s-apps-not-listed', 'Not listed', 'An application that does not fit the shelves above.', null, ['cat-i-apps-not-listed']),
    ],
  },
  {
    id: CAT.P_M365,
    type: 'product',
    name: 'Microsoft 365',
    description: 'The Microsoft suite Northwind runs on — account, files, apps and mail.',
    audience: 'internal',
    children: [
      sub('cat-s-m365-account', 'M365 Account', 'Sign-in prompts, licences and mailbox limits on the account itself.', null, ['cat-i-m365-outlook-password', 'cat-i-mailbox-storage', 'cat-i-mobile-policy', 'cat-i-desktop-mail-client', 'cat-i-m365-copilot', 'cat-i-m365-no-licence', 'cat-i-m365-account-not-listed']),
      sub('cat-s-m365-files', 'SharePoint & OneDrive', 'Files, libraries, sync and who can open what.', null, ['cat-i-m365-onedrive-sync', 'cat-i-m365-files-missing', 'cat-i-m365-permissions', 'cat-i-m365-sharing-link', 'cat-i-m365-file-locked', 'cat-i-m365-onedrive-space', 'cat-i-m365-files-not-listed']),
      sub('cat-s-m365-office', 'Office Apps', 'Word, Excel and PowerPoint — crashes, templates, add-ins and lost edits.', null, ['cat-i-m365-office-crash', 'cat-i-m365-office-autosave', 'cat-i-m365-office-coauthor', 'cat-i-m365-office-template', 'cat-i-m365-office-addin', 'cat-i-m365-office-macro', 'cat-i-m365-office-not-listed']),
      sub('cat-s-m365-outlook', 'Outlook & Teams', 'Mail, calendars, meetings and calls.', null, ['cat-i-email-not-working', 'cat-i-email-on-phone', 'cat-i-m365-teams-call', 'cat-i-quarantine', 'cat-i-email-bounce', 'cat-i-email-missing', 'cat-i-phishing', 'cat-i-mail-search', 'cat-i-email-signature', 'cat-i-calendar-sync', 'cat-i-shared-calendar', 'cat-i-invite-missing', 'cat-i-out-of-office', 'cat-i-distribution-list', 'cat-i-room-booking', 'cat-i-room-kit', 'cat-i-m365-teams-recording', 'cat-i-mail-delivery-not-listed']),
      sub('cat-s-m365-not-listed', 'Not listed', 'Anything in the Microsoft suite that does not fit the four lanes above.', null, ['cat-i-m365-not-listed']),
    ],
  },
  {
    id: CAT.P_NETSEC,
    type: 'product',
    name: 'Network & Security',
    description: 'Getting in, staying in, the network you get in over, and the doors and cabinets behind it.',
    audience: 'internal',
    children: [
      sub('cat-s-signin', 'Sign-in & passwords', 'Passwords, multi-factor and lockouts.', null, [CAT.I_CANNOT_SIGN_IN, CAT.I_MFA, 'cat-i-account-locked', 'cat-i-password-policy', 'cat-i-sso', 'cat-i-passkey', 'cat-i-signin-wrong-account', 'cat-i-signin-not-listed']),
      sub('cat-s-app-access', 'Application access', 'Rights inside a system you can already sign in to.', null, ['cat-i-request-app', 'cat-i-access-denied', 'cat-i-access-lost', 'cat-i-shared-mailbox-access', 'cat-i-elevated-rights', 'cat-i-access-approval-stuck', 'cat-i-app-access-not-listed']),
      sub('cat-s-identity', 'Identity & directory', 'Who you are on paper — names, groups, joiners and leavers.', null, ['cat-i-directory-profile', 'cat-i-name-change', 'cat-i-contractor-account', 'cat-i-wrong-manager', 'cat-i-duplicate-account', 'cat-i-missing-from-group', 'cat-i-identity-not-listed']),
      sub('cat-s-network', 'Network & Wi-Fi', 'Wi-Fi, VPN, ports and connectivity.', null, ['cat-i-wifi', 'cat-i-vpn-not-connecting', 'cat-i-wifi-weak-in-one-area', 'cat-i-dead-network-port', 'cat-i-dns-not-resolving', 'cat-i-guest-wifi', 'cat-i-office-offline', 'cat-i-network-not-listed']),
      sub('cat-s-physical', 'Physical security', 'Badges, doors, readers and cameras.', null, ['cat-i-badge-access', 'cat-i-badge-reader-dead', 'cat-i-badge-lost', 'cat-i-door-not-latching', 'cat-i-door-alarm', 'cat-i-tailgating', 'cat-i-camera-offline', 'cat-i-physical-security-not-listed']),
      sub('cat-s-closet', 'Network closet & on-site kit', 'Comms rooms, racks, UPS and the noises they make.', null, ['cat-i-comms-room-beeping', 'cat-i-ups-on-battery', 'cat-i-comms-room-hot', 'cat-i-switch-red-light', 'cat-i-cable-unplugged', 'cat-i-comms-cabinet-open', 'cat-i-closet-not-listed']),
      sub('cat-s-netsec-not-listed', 'Not listed', 'Access or network trouble that does not fit the shelves above.', null, ['cat-i-accounts-not-listed']),
    ],
  },
  {
    id: CAT.P_WORKPLACE,
    type: 'product',
    name: 'Workplace & Facilities',
    description: 'Buildings and desks, joining and leaving, and the ways-of-working material the service desk itself is trained on.',
    audience: 'internal',
    children: [
      sub('cat-s-building', 'Building & desks', 'Chicago HQ, New York, Austin and the Bolingbrook warehouse.', 'internal', ['cat-i-facilities-issue', 'cat-i-comfort', 'cat-i-badge-door', 'cat-i-desk-move', 'cat-i-supplies', 'cat-i-parking-deliveries', 'cat-i-building-not-listed']),
      sub('cat-s-joining-leaving', 'Joining & leaving', 'The two most cross-functional requests Northwind runs. Both fan out to IT, Facilities and People Ops.', 'internal', ['cat-i-new-hire', 'cat-i-starter-not-ready', 'cat-i-contractor-onboarding', 'cat-i-role-change', 'cat-i-offboarding', 'cat-i-leaver-access', 'cat-i-joining-not-listed']),
      sub('cat-s-ways-of-working', 'Ways of working', 'The service desk’s own enablement material. Every atom here is also a lesson in the Support Agent curriculum.', 'internal', ['cat-i-working-a-queue', 'cat-i-customer-comms', 'cat-i-escalation-sla', 'cat-i-wrong-queue', 'cat-i-knowledge-gap', 'cat-i-raise-a-change', 'cat-i-ways-not-listed']),
      sub('cat-s-workplace-not-listed', 'Not listed', 'Something about the workplace that none of the above covers. Read and routed by hand.', 'internal', ['cat-i-workplace-not-listed']),
    ],
  },
  {
    id: CAT.P_STOREFRONT,
    type: 'product',
    name: 'Northwind Storefront',
    description: 'The commerce platform Northwind sells. This branch is what customers see in the help centre and the portal.',
    audience: 'external',
    children: [
      sub('cat-s-getting-started', 'Getting started', 'The first two weeks of a new customer. Deflection here is worth more than anywhere else in the catalog.', 'external', [CAT.I_STOREFRONT_SETUP, 'cat-i-import-catalog', 'cat-i-domain', 'cat-i-invite-team', 'cat-i-theme', 'cat-i-tax-shipping', 'cat-i-getting-started-not-listed']),
      sub('cat-s-payments-billing', 'Payments & billing', 'Money in from shoppers, and money out to Northwind. Two different things customers routinely conflate.', 'external', [CAT.I_PAYMENTS, 'cat-i-payout-missing', 'cat-i-refund-dispute', CAT.I_BILLING, 'cat-i-plans-seats', 'cat-i-billing-contact', 'cat-i-payments-not-listed']),
      sub('cat-s-integrations', 'Integrations & API', 'Where customer developers land. Deep-linked from the API docs.', 'external', ['cat-i-storefront-api-keys', 'cat-i-api-errors', 'cat-i-webhooks', 'cat-i-orders-not-syncing', 'cat-i-inventory-sync', 'cat-i-data-export', 'cat-i-integrations-not-listed']),
      sub('cat-s-problems-feedback', 'Problems & feedback', 'The intake side of external support — bugs, outages and the feature pipeline.', 'external', ['cat-i-report-bug', 'cat-i-checkout-failing', 'cat-i-store-slow', 'cat-i-status-incidents', 'cat-i-sla-credit', 'cat-i-feature-request', 'cat-i-problems-not-listed']),
      sub('cat-s-storefront-not-listed', 'Not listed', 'Something about the Storefront that none of the above covers. Read and routed by hand.', 'external', ['cat-i-storefront-not-listed']),
    ],
  },
];
