/**
 * Forms seed — Northwind Systems.
 *
 * TWO RECORDS, DELIBERATELY SEPARATE:
 *
 *   FORM     a published portal entry point. It is scoped to products and to an
 *            audience, and it is what a person lands on: "Employee Help Centre",
 *            "Northwind Storefront Support". A form owns no fields.
 *
 *   SUBFORM  an actual request intake, attached to catalog items. THIS is where
 *            fields, routing and approval live.
 *
 * The differentiator is that one catalog item carries SEVERAL subforms.
 * "Cannot sign in" has both `sf-report-signin` (report a problem → IT queue) and
 * `sf-request-access` (request access → IT queue behind an access-grant
 * approval). Same item, different intakes, different downstream behaviour. A
 * single form-per-item model cannot express that, and every helpdesk eventually
 * needs it.
 *
 * Conditional display (`showIf`) is evaluated with the SAME engine that runs
 * business rules — lib/conditions.js — against the answer map keyed by field id.
 * So `{ fieldId: 'swr-cost', op: 'gt', value: 500 }` reads "show this field once
 * the annual cost passes 500", and the builder renders that sentence in plain
 * language rather than making an admin read JSON.
 */

import { Q, SF, POL, CAT, USR, LIC } from './ids.js';

/* ------------------------------------------------------------------ *
 * Reusable option sets — written once so the same vocabulary appears on
 * every intake that asks the same question.
 * ------------------------------------------------------------------ */

const SITES = ['Chicago HQ', 'New York', 'Austin Support Centre', 'Elk Grove DC', 'Bolingbrook Warehouse', 'Remote / home office'];
const URGENCY = ['Blocking my work right now', 'Slowing me down', 'Annoying but I can work', 'Planning ahead'];
const BROWSERS = ['Chrome', 'Safari', 'Edge', 'Firefox', 'Mobile app (iOS)', 'Mobile app (Android)'];

/* ==================================================================== *
 * SUBFORMS — one per id in SF, 4-8 fields each.
 * ==================================================================== */

export const SUBFORMS = [
  /* ---------------- Accounts & access ---------------- */
  {
    id: SF.REPORT_SIGNIN,
    raises: 'incident',
    name: 'Report a sign-in problem',
    description: 'Something is stopping you getting into a Northwind system.',
    audience: 'internal',
    routing: { queueId: Q.IT },
    submitLabel: 'Report the problem',
    confirmation: 'IT Support has your report. Most sign-in problems are cleared within an hour during business hours.',
    ownerId: USR.EMMA,
    updatedAt: '2026-07-28T14:20:00',
    submissions30d: 148,
    enabled: true,
    fields: [
      { id: 'signin-system', type: 'select', label: 'Which system?', required: true,
        options: ['Northwind SSO', 'Email / Outlook', 'Salesforce', 'Workday', 'VPN', 'RelayHQ', 'Something else'],
        help: 'Pick the one you were trying to open when it failed.' },
      { id: 'signin-symptom', type: 'select', label: 'What happens when you try?', required: true,
        options: ['Password rejected', 'Account locked out', 'MFA code never arrives', 'Loops back to the login page', 'An error message I do not recognise'] },
      { id: 'signin-error', type: 'text', label: 'Type the error exactly as it appears', required: false,
        placeholder: 'e.g. AADSTS50126: Invalid username or password',
        help: 'Copying the code verbatim usually saves a round trip.',
        showIf: { fieldId: 'signin-symptom', op: 'is', value: 'An error message I do not recognise' } },
      { id: 'signin-started', type: 'date', label: 'When did it start?', required: false },
      { id: 'signin-tried-reset', type: 'checkbox', label: 'I have already tried resetting my password', required: false },
      { id: 'signin-detail', type: 'textarea', label: 'Anything else we should know?', required: false,
        placeholder: 'What you were doing, what changed recently, who else is affected…' },
      { id: 'signin-shot', type: 'file', label: 'Screenshot', required: false, help: 'PNG or JPG, up to 10 MB.' },
    ],
  },

  {
    id: SF.REQUEST_ACCESS,
    raises: 'service_request',
    fulfils: null,
    name: 'Request access to a system',
    description: 'Ask for a new account, a new role, or a higher permission level.',
    audience: 'internal',
    routing: { queueId: Q.IT },
    approvalPolicyId: POL.ACCESS_GRANT,
    submitLabel: 'Request access',
    confirmation: 'Your manager has been asked to approve. You will get an email the moment they decide.',
    ownerId: USR.EMMA,
    updatedAt: '2026-08-04T09:40:00',
    submissions30d: 63,
    enabled: true,
    fields: [
      { id: 'access-system', type: 'select', label: 'System', required: true,
        options: ['Salesforce', 'Workday', 'Snowflake', 'GitHub', 'AWS Console', 'Stripe Dashboard', 'RelayHQ Admin', 'Shared drive'] },
      { id: 'access-level', type: 'select', label: 'Access level', required: true,
        options: ['read', 'write', 'admin'],
        help: 'Ask for the least you need. Admin is reviewed by the system owner as well as your manager.' },
      { id: 'access-justification', type: 'textarea', label: 'Why do you need admin?', required: true,
        placeholder: 'Name the task that cannot be done at write level.',
        showIf: { fieldId: 'access-level', op: 'is', value: 'admin' } },
      { id: 'access-duration', type: 'select', label: 'How long?', required: true,
        options: ['Permanent — part of my role', 'Temporary — for a project'] },
      { id: 'access-until', type: 'date', label: 'Remove access on', required: true,
        help: 'Temporary grants are revoked automatically on this date.',
        showIf: { fieldId: 'access-duration', op: 'is', value: 'Temporary — for a project' } },
      { id: 'access-manager', type: 'user', label: 'Approving manager', required: true,
        help: 'Defaults to your manager in the directory. Change it only if they are out.' },
      { id: 'access-needed-by', type: 'date', label: 'Needed by', required: false },
    ],
  },

  {
    id: SF.MFA_RESET,
    raises: 'service_request',
    fulfils: { kind: 'software', licenceId: LIC.DUO },
    name: 'Reset multi-factor authentication',
    description: 'Lost, replaced or wiped the device that holds your MFA codes.',
    audience: 'internal',
    routing: { queueId: Q.IT },
    submitLabel: 'Request an MFA reset',
    confirmation: 'An IT engineer will call the number on your directory record to verify it is you before resetting.',
    ownerId: USR.EMMA,
    updatedAt: '2026-06-19T11:05:00',
    submissions30d: 27,
    enabled: true,
    fields: [
      { id: 'mfa-reason', type: 'select', label: 'What happened?', required: true,
        options: ['New phone', 'Phone lost or stolen', 'Phone wiped or reset', 'Authenticator app deleted', 'Changed phone number'] },
      { id: 'mfa-lost-when', type: 'date', label: 'When did you lose the device?', required: true,
        help: 'We revoke every active session issued after this time.',
        showIf: { fieldId: 'mfa-reason', op: 'is', value: 'Phone lost or stolen' } },
      { id: 'mfa-new-device', type: 'select', label: 'New device', required: true,
        options: ['iPhone', 'Android phone', 'Company iPad', 'Hardware security key'] },
      { id: 'mfa-callback', type: 'phone', label: 'Number we can verify you on', required: true,
        placeholder: '+1 (312) 555-0100' },
      { id: 'mfa-confirm', type: 'checkbox', label: 'I understand every existing session will be signed out', required: true },
    ],
  },

  /* ---------------- Email ---------------- */
  {
    id: SF.EMAIL_PROBLEM,
    raises: 'incident',
    name: 'Email is not working',
    description: 'Mail not sending, not arriving, or the client will not connect.',
    audience: 'internal',
    routing: { queueId: Q.IT },
    submitLabel: 'Report email problem',
    confirmation: 'Logged with IT Support. If mail is down for a whole site we will post to the status channel.',
    ownerId: USR.EMMA,
    updatedAt: '2026-07-02T16:12:00',
    submissions30d: 91,
    enabled: true,
    fields: [
      { id: 'email-symptom', type: 'select', label: 'What is wrong?', required: true,
        options: ['Mail is not arriving', 'Mail will not send', 'Client keeps asking for my password', 'Calendar invites are missing', 'A message went to quarantine'] },
      { id: 'email-address', type: 'email', label: 'Affected mailbox', required: true,
        placeholder: 'name@northwind.example',
        help: 'Use the shared mailbox address if this is about a shared inbox.' },
      { id: 'email-device', type: 'select', label: 'Where are you seeing it?', required: true,
        options: ['Outlook on laptop', 'Outlook on phone', 'Webmail', 'Apple Mail', 'Everywhere'] },
      { id: 'email-quarantine-subject', type: 'text', label: 'Subject line of the quarantined message', required: false,
        placeholder: 'Paste the subject so we can find it in the quarantine log',
        showIf: { fieldId: 'email-symptom', op: 'is', value: 'A message went to quarantine' } },
      { id: 'email-started', type: 'date', label: 'First noticed', required: false },
      { id: 'email-detail', type: 'textarea', label: 'Details', required: false,
        placeholder: 'Sender, recipient, bounce text…' },
    ],
  },

  {
    id: SF.DISTRIBUTION_LIST,
    raises: 'service_request',
    fulfils: { kind: 'software', licenceId: LIC.MS365_E3 },
    name: 'Distribution list change',
    description: 'Create a list, or add and remove members on one you own.',
    audience: 'internal',
    routing: { queueId: Q.IT },
    submitLabel: 'Submit list change',
    confirmation: 'Changes to an existing list are usually applied the same day.',
    ownerId: USR.EMMA,
    updatedAt: '2026-05-30T10:00:00',
    submissions30d: 19,
    enabled: true,
    fields: [
      { id: 'dl-change', type: 'select', label: 'What do you need?', required: true,
        options: ['Add members', 'Remove members', 'Create a new list', 'Delete a list', 'Change the list owner'] },
      { id: 'dl-address', type: 'email', label: 'List address', required: false,
        placeholder: 'team-name@northwind.example',
        showIf: { fieldId: 'dl-change', op: 'is_not', value: 'Create a new list' } },
      { id: 'dl-new-name', type: 'text', label: 'Name for the new list', required: false,
        placeholder: 'e.g. austin-support-leads',
        help: 'Lowercase, hyphenated. We append @northwind.example.',
        showIf: { fieldId: 'dl-change', op: 'is', value: 'Create a new list' } },
      { id: 'dl-members', type: 'user', label: 'People to add or remove', required: false },
      { id: 'dl-owner', type: 'user', label: 'List owner', required: true,
        help: 'The owner approves future membership changes without raising a ticket.' },
      { id: 'dl-reason', type: 'textarea', label: 'Reason', required: false, placeholder: 'Reorg, new team, project wrapped up…' },
    ],
  },

  /* ---------------- Devices ---------------- */
  {
    id: SF.LAPTOP_REPAIR,
    raises: 'incident',
    name: 'Laptop repair or replacement',
    description: 'Your machine is damaged, failing or unusable.',
    audience: 'internal',
    routing: { queueId: Q.IT },
    submitLabel: 'Book a repair',
    confirmation: 'Bring the machine to the IT bar at your site, or wait for the courier label if you are remote.',
    ownerId: USR.EMMA,
    updatedAt: '2026-08-11T08:55:00',
    submissions30d: 44,
    enabled: true,
    fields: [
      { id: 'repair-asset', type: 'asset', label: 'Which machine?', required: true,
        help: 'Pick from the devices assigned to you. The serial and warranty come with it.' },
      { id: 'repair-symptom', type: 'select', label: 'Symptom', required: true,
        options: ['Will not power on', 'Screen damaged or flickering', 'Keyboard or trackpad faulty', 'Battery will not hold charge', 'Overheating or very loud fan', 'Liquid damage', 'Something else'] },
      { id: 'repair-urgency', type: 'select', label: 'How urgent?', required: true, options: URGENCY },
      { id: 'repair-loaner', type: 'checkbox', label: 'I need a loaner while it is being repaired', required: false },
      { id: 'repair-site', type: 'select', label: 'Where will you hand it over?', required: true, options: SITES },
      { id: 'repair-detail', type: 'textarea', label: 'What happened?', required: false,
        placeholder: 'When it started, whether it was dropped, what you have already tried…' },
      { id: 'repair-photo', type: 'file', label: 'Photo of the damage', required: false },
    ],
  },

  {
    id: SF.NEW_HARDWARE,
    raises: 'service_request',
    fulfils: null,
    name: 'Request new hardware',
    description: 'A monitor, dock, headset, phone or an additional machine.',
    audience: 'internal',
    routing: { queueId: Q.PROCUREMENT },
    approvalPolicyId: POL.SPEND_OVER_500,
    submitLabel: 'Request hardware',
    confirmation: 'Procurement will confirm stock. Anything over the spend threshold goes to your manager first.',
    ownerId: USR.JAMES,
    updatedAt: '2026-08-09T13:15:00',
    submissions30d: 58,
    enabled: true,
    fields: [
      { id: 'hw-type', type: 'select', label: 'What do you need?', required: true,
        options: ['Monitor', 'Laptop (additional)', 'Docking station', 'Headset', 'Mobile phone', 'Keyboard / mouse', 'Webcam', 'Other'] },
      { id: 'hw-model', type: 'text', label: 'Preferred model', required: false,
        placeholder: 'Leave blank to get the standard issue for your role' },
      { id: 'hw-qty', type: 'number', label: 'Quantity', required: true, placeholder: '1' },
      { id: 'hw-cost', type: 'currency', label: 'Estimated cost (USD)', required: true,
        help: 'Best estimate is fine — Procurement replaces it with the real quote.' },
      { id: 'hw-justification', type: 'textarea', label: 'Business justification', required: true,
        placeholder: 'What work does this unblock? Why is the standard kit not enough?',
        help: 'Required above the $500 threshold because your manager has to sign it off.',
        showIf: { fieldId: 'hw-cost', op: 'gt', value: 500 } },
      { id: 'hw-needed-by', type: 'date', label: 'Needed by', required: false },
      { id: 'hw-ship-to', type: 'select', label: 'Deliver to', required: true, options: SITES },
    ],
  },

  {
    id: SF.RETURN_HARDWARE,
    raises: 'service_request',
    fulfils: null,
    name: 'Return equipment',
    description: 'Send back a device you no longer need, or one belonging to someone who has left.',
    audience: 'internal',
    routing: { queueId: Q.IT },
    submitLabel: 'Arrange a return',
    confirmation: 'The asset record moves to In Transit as soon as the courier scans it.',
    ownerId: USR.EMMA,
    updatedAt: '2026-06-25T15:30:00',
    submissions30d: 22,
    enabled: true,
    fields: [
      { id: 'ret-asset', type: 'asset', label: 'Equipment being returned', required: true },
      { id: 'ret-reason', type: 'select', label: 'Reason', required: true,
        options: ['Upgraded to a new device', 'No longer needed', 'Employee is leaving', 'Faulty — do not redeploy', 'End of lease'] },
      { id: 'ret-condition', type: 'select', label: 'Condition', required: true,
        options: ['Like new', 'Normal wear', 'Damaged', 'Not working'] },
      { id: 'ret-method', type: 'select', label: 'How will it get back to us?', required: true,
        options: ['Drop at the IT bar', 'Courier pickup', 'Internal mail'] },
      { id: 'ret-address', type: 'textarea', label: 'Pickup address', required: true,
        placeholder: 'Street, city, postcode — plus any gate or reception instructions',
        showIf: { fieldId: 'ret-method', op: 'is', value: 'Courier pickup' } },
      { id: 'ret-available', type: 'date', label: 'Available from', required: false },
    ],
  },

  /* ---------------- Software & licensing ---------------- */
  {
    id: SF.SOFTWARE_REQUEST,
    raises: 'service_request',
    fulfils: null,
    name: 'Request software',
    description: 'A licence for an application that is not in the standard bundle.',
    audience: 'internal',
    routing: { queueId: Q.PROCUREMENT },
    approvalPolicyId: POL.SPEND_OVER_500,
    submitLabel: 'Request licence',
    confirmation: 'If we already hold a spare seat you will have it today. New purchases need approval first.',
    ownerId: USR.JAMES,
    updatedAt: '2026-08-14T10:45:00',
    submissions30d: 76,
    enabled: true,
    fields: [
      { id: 'swr-app', type: 'select', label: 'Application', required: true,
        options: ['Adobe Creative Cloud', 'Figma', 'Tableau', 'Snowflake', 'Miro', 'Notion', 'JetBrains', 'Something not listed'] },
      { id: 'swr-other', type: 'text', label: 'Which application?', required: true,
        placeholder: 'Vendor and product name, plus a link to their pricing page',
        showIf: { fieldId: 'swr-app', op: 'is', value: 'Something not listed' } },
      { id: 'swr-licence', type: 'select', label: 'Licence type', required: true,
        options: ['Single user', 'Team (up to 10)', 'Department', 'Enterprise'] },
      { id: 'swr-seats', type: 'number', label: 'Seats', required: true, placeholder: '1' },
      { id: 'swr-cost', type: 'currency', label: 'Annual cost (USD)', required: true },
      { id: 'swr-justification', type: 'textarea', label: 'Business justification', required: true,
        placeholder: 'What does this let the team do that the current tooling does not?',
        help: 'Shown once the annual cost passes $500, which is the approval threshold.',
        showIf: { fieldId: 'swr-cost', op: 'gt', value: 500 } },
      { id: 'swr-data', type: 'select', label: 'Will it hold customer data?', required: true,
        options: ['No customer data', 'Customer data — anonymised', 'Customer data — identifiable', 'Not sure'],
        help: 'Anything identifiable triggers a security review before purchase.' },
      { id: 'swr-needed-by', type: 'date', label: 'Needed by', required: false },
    ],
  },

  {
    id: SF.LICENSE_RENEWAL,
    raises: 'service_request',
    fulfils: null,
    name: 'Renew a software licence',
    description: 'A contract is coming up for renewal and someone has to decide.',
    audience: 'internal',
    routing: { queueId: Q.PROCUREMENT },
    submitLabel: 'Start the renewal',
    confirmation: 'Procurement will open the vendor conversation 45 days before the renewal date.',
    ownerId: USR.JAMES,
    updatedAt: '2026-07-16T09:20:00',
    submissions30d: 12,
    enabled: true,
    fields: [
      { id: 'ren-asset', type: 'asset', label: 'Licence or contract', required: true },
      { id: 'ren-vendor', type: 'text', label: 'Vendor contact', required: false,
        placeholder: 'Name and email of the account manager, if you have one' },
      { id: 'ren-decision', type: 'select', label: 'What should we do?', required: true,
        options: ['Renew as-is', 'Renew with more seats', 'Renew with fewer seats', 'Let it lapse', 'Move to a different vendor'] },
      { id: 'ren-seats', type: 'number', label: 'Seats for the next term', required: false,
        showIf: { fieldId: 'ren-decision', op: 'is_not', value: 'Let it lapse' } },
      { id: 'ren-cost', type: 'currency', label: 'Quoted renewal cost (USD)', required: false },
      { id: 'ren-date', type: 'date', label: 'Renewal date', required: true },
      { id: 'ren-notes', type: 'textarea', label: 'Notes for Procurement', required: false },
    ],
  },

  /* ---------------- People ---------------- */
  {
    id: SF.NEW_HIRE,
    raises: 'service_request',
    fulfils: null,
    name: 'New hire onboarding',
    description: 'Everything a person needs on day one — account, laptop, access, desk.',
    audience: 'internal',
    routing: { queueId: Q.PEOPLE },
    approvalPolicyId: POL.NEW_HIRE,
    submitLabel: 'Start onboarding',
    confirmation: 'People Ops will fan this out into IT, Facilities and Payroll tasks against the start date.',
    ownerId: USR.PATTI,
    updatedAt: '2026-08-12T12:00:00',
    submissions30d: 9,
    enabled: true,
    fields: [
      { id: 'nh-name', type: 'text', label: 'New hire full name', required: true, placeholder: 'As it appears on the contract' },
      { id: 'nh-start', type: 'date', label: 'Start date', required: true,
        help: 'Raise this at least ten working days out or the laptop will not be imaged in time.' },
      { id: 'nh-function', type: 'select', label: 'Job function', required: true,
        options: ['Support Agent', 'IT Support', 'Procurement', 'People Ops', 'Facilities', 'Finance', 'Product', 'Sales', 'Marketing'],
        help: 'Determines the access bundle and the training curriculum they are enrolled on.' },
      { id: 'nh-manager', type: 'user', label: 'Reporting manager', required: true },
      { id: 'nh-site', type: 'select', label: 'Primary site', required: true, options: SITES },
      { id: 'nh-laptop', type: 'select', label: 'Laptop', required: true,
        options: ['MacBook Pro 14"', 'MacBook Air 15"', 'Dell Latitude 7450', 'ThinkPad X1 Carbon'] },
      { id: 'nh-extras', type: 'multiselect', label: 'Extra kit', required: false,
        options: ['Second monitor', 'Docking station', 'Headset', 'Mobile phone', 'Standing desk', 'Corporate card'] },
      { id: 'nh-notes', type: 'textarea', label: 'Anything else People Ops should know?', required: false,
        placeholder: 'Accessibility needs, visa timing, contractor arrangement…' },
    ],
  },

  {
    id: SF.OFFBOARDING,
    raises: 'service_request',
    fulfils: null,
    name: 'Offboarding',
    description: 'Close accounts, recover equipment and hand over work when someone leaves.',
    audience: 'internal',
    routing: { queueId: Q.PEOPLE },
    approvalPolicyId: POL.OFFBOARDING,
    submitLabel: 'Start offboarding',
    confirmation: 'Access is revoked at 17:00 on the last day unless HR tells us otherwise.',
    ownerId: USR.PATTI,
    updatedAt: '2026-08-06T17:10:00',
    submissions30d: 6,
    enabled: true,
    fields: [
      { id: 'off-person', type: 'user', label: 'Departing employee', required: true },
      { id: 'off-last-day', type: 'date', label: 'Last working day', required: true },
      { id: 'off-reason', type: 'select', label: 'Reason', required: true,
        options: ['Resignation', 'End of contract', 'Retirement', 'Involuntary', 'Internal transfer'] },
      { id: 'off-immediate', type: 'checkbox', label: 'Revoke all access immediately', required: false,
        help: 'Use for involuntary departures. Skips the usual end-of-day grace period.' },
      { id: 'off-escort', type: 'textarea', label: 'Security instructions', required: true,
        placeholder: 'Who collects the badge, who is in the room, when Facilities should be told',
        showIf: { fieldId: 'off-immediate', op: 'is_true', value: true } },
      { id: 'off-mailbox', type: 'user', label: 'Forward mail and calendar to', required: true },
      { id: 'off-equipment', type: 'select', label: 'Equipment return', required: true,
        options: ['Handing back in person', 'Courier pickup arranged', 'Already returned', 'Nothing to return'] },
    ],
  },

  /* ---------------- Finance & workplace ---------------- */
  {
    id: SF.EXPENSE_APPROVAL,
    raises: 'service_request',
    fulfils: null,
    name: 'Expense pre-approval',
    description: 'Get spend signed off before you commit to it.',
    audience: 'internal',
    routing: { queueId: Q.FINANCE },
    approvalPolicyId: POL.SPEND_OVER_500,
    submitLabel: 'Request pre-approval',
    confirmation: 'Do not book anything until this is approved — reimbursement is not guaranteed without it.',
    ownerId: USR.MICHAEL,
    updatedAt: '2026-08-13T11:35:00',
    submissions30d: 84,
    enabled: true,
    fields: [
      { id: 'exp-type', type: 'select', label: 'Type of spend', required: true,
        options: ['Travel', 'Conference or training', 'Client entertainment', 'Equipment', 'Subscription', 'Other'] },
      { id: 'exp-amount', type: 'currency', label: 'Amount (USD)', required: true },
      { id: 'exp-cost-centre', type: 'select', label: 'Cost centre', required: true,
        options: ['Operations', 'IT', 'Support', 'Product', 'Sales', 'Marketing', 'People', 'Finance'] },
      { id: 'exp-when', type: 'date', label: 'Date of spend', required: true },
      { id: 'exp-vendor', type: 'text', label: 'Vendor or supplier', required: false, placeholder: 'Who are you paying?' },
      { id: 'exp-justification', type: 'textarea', label: 'Business justification', required: true,
        placeholder: 'What outcome does this spend buy, and what happens if we do not?',
        help: 'Finance requires written justification above $500.',
        showIf: { fieldId: 'exp-amount', op: 'gt', value: 500 } },
      { id: 'exp-quote', type: 'file', label: 'Quote or estimate', required: false },
    ],
  },

  {
    id: SF.FACILITIES_ISSUE,
    raises: 'incident',
    name: 'Report a facilities issue',
    description: 'Something in the building is broken, unsafe or uncomfortable.',
    audience: 'internal',
    routing: { queueId: Q.FACILITIES },
    submitLabel: 'Report the issue',
    confirmation: 'Facilities triage twice a day. Anything flagged unsafe is picked up immediately.',
    ownerId: USR.LINDA,
    updatedAt: '2026-07-21T08:05:00',
    submissions30d: 37,
    enabled: true,
    fields: [
      { id: 'fac-site', type: 'select', label: 'Site', required: true, options: SITES },
      { id: 'fac-where', type: 'text', label: 'Floor, room or desk', required: true, placeholder: 'e.g. 4th floor, Ravinia meeting room' },
      { id: 'fac-type', type: 'select', label: 'What is wrong?', required: true,
        options: ['Heating or air conditioning', 'Lighting', 'Plumbing', 'Furniture', 'Door or badge reader', 'Cleanliness', 'Meeting room AV', 'Something else'] },
      { id: 'fac-unsafe', type: 'checkbox', label: 'This is a safety hazard', required: false,
        help: 'Ticks the priority up to Urgent and pages the on-site duty manager.' },
      { id: 'fac-hazard-detail', type: 'textarea', label: 'Describe the hazard and whether the area is cordoned off', required: true,
        showIf: { fieldId: 'fac-unsafe', op: 'is_true', value: true } },
      { id: 'fac-photo', type: 'file', label: 'Photo', required: false },
      { id: 'fac-detail', type: 'textarea', label: 'Details', required: false, placeholder: 'How long has it been like this?' },
    ],
  },

  /* ---------------- External customer intakes ---------------- */
  {
    id: SF.STOREFRONT_BUG,
    raises: 'incident',
    name: 'Report a Storefront bug',
    description: 'Something in Northwind Storefront is not behaving the way the docs say it should.',
    audience: 'external',
    routing: { queueId: Q.SUPPORT },
    submitLabel: 'Report the bug',
    confirmation: 'Support will reproduce it against your account. Checkout-affecting reports skip the queue.',
    ownerId: USR.LISA,
    updatedAt: '2026-08-15T07:50:00',
    submissions30d: 212,
    enabled: true,
    fields: [
      { id: 'bug-area', type: 'select', label: 'Where in Storefront?', required: true,
        options: ['Checkout', 'Product catalog', 'Inventory sync', 'Payments', 'Shipping rates', 'Admin dashboard', 'Reporting', 'Customer accounts'] },
      { id: 'bug-what', type: 'textarea', label: 'What happened?', required: true,
        placeholder: 'What you did, what you expected, what you got instead.' },
      { id: 'bug-url', type: 'text', label: 'Storefront URL', required: false, placeholder: 'https://shop.example.com/checkout' },
      { id: 'bug-checkout', type: 'checkbox', label: 'Customers cannot complete a purchase', required: false,
        help: 'Anything blocking revenue is treated as urgent regardless of your plan.' },
      { id: 'bug-order', type: 'text', label: 'A recent failed order ID', required: true,
        placeholder: 'e.g. NW-2026-118402',
        help: 'Lets us pull the exact transaction log instead of guessing.',
        showIf: { fieldId: 'bug-checkout', op: 'is_true', value: true } },
      { id: 'bug-browser', type: 'select', label: 'Browser or app', required: false, options: BROWSERS },
      { id: 'bug-started', type: 'date', label: 'First seen', required: false },
      { id: 'bug-shot', type: 'file', label: 'Screenshot or screen recording', required: false },
    ],
  },

  {
    id: SF.BILLING_QUESTION,
    raises: 'service_request',
    fulfils: null,
    name: 'Billing question',
    description: 'An invoice, a charge, a refund or a plan change.',
    audience: 'external',
    routing: { queueId: Q.FINANCE },
    submitLabel: 'Ask billing',
    confirmation: 'Billing answers within one business day. Nothing is charged while a query is open.',
    ownerId: USR.MICHAEL,
    updatedAt: '2026-08-10T14:25:00',
    submissions30d: 68,
    enabled: true,
    fields: [
      { id: 'bill-topic', type: 'select', label: 'What is this about?', required: true,
        options: ['A specific invoice', 'An unexpected charge', 'Refund request', 'Change our plan', 'Update payment method', 'Tax or VAT'] },
      { id: 'bill-invoice', type: 'text', label: 'Invoice number', required: true,
        placeholder: 'e.g. INV-2026-04417',
        showIf: { fieldId: 'bill-topic', op: 'is', value: 'A specific invoice' } },
      { id: 'bill-amount', type: 'currency', label: 'Amount in question (USD)', required: false },
      { id: 'bill-contact', type: 'email', label: 'Billing contact', required: true,
        placeholder: 'accounts@yourcompany.example',
        help: 'We copy this address on every reply so your finance team stays in the loop.' },
      { id: 'bill-detail', type: 'textarea', label: 'Tell us more', required: true,
        placeholder: 'What you expected to see and what you actually saw.' },
      { id: 'bill-doc', type: 'file', label: 'Invoice or purchase order', required: false },
    ],
  },

  {
    id: SF.FEATURE_REQUEST,
    raises: 'service_request',
    fulfils: null,
    name: 'Request a feature',
    description: 'Tell the product team what Storefront should do that it does not.',
    audience: 'both',
    routing: { queueId: Q.ENGINEERING },
    submitLabel: 'Send to the product team',
    confirmation: 'Every request is read. We link yours to the roadmap item if one already exists.',
    ownerId: USR.MIKE,
    updatedAt: '2026-08-01T13:40:00',
    submissions30d: 41,
    enabled: true,
    fields: [
      { id: 'fr-summary', type: 'text', label: 'One-line summary', required: true,
        placeholder: 'e.g. Bulk-edit shipping rates by region' },
      { id: 'fr-problem', type: 'textarea', label: 'What problem would this solve?', required: true,
        placeholder: 'Describe the situation, not the solution — it helps us find better answers.' },
      { id: 'fr-area', type: 'select', label: 'Product area', required: true,
        options: ['Checkout', 'Catalog', 'Inventory', 'Payments', 'Shipping', 'Reporting', 'API & webhooks', 'Admin'] },
      { id: 'fr-frequency', type: 'select', label: 'How often does this bite you?', required: true,
        options: ['Several times a day', 'Weekly', 'Monthly', 'Only at peak trading'] },
      { id: 'fr-workaround', type: 'textarea', label: 'What do you do today instead?', required: false,
        placeholder: 'Spreadsheets, manual steps, a script someone wrote…' },
      { id: 'fr-beta', type: 'checkbox', label: 'We would test an early version', required: false },
    ],
  },

  {
    id: SF.INTEGRATION_HELP,
    raises: 'incident',
    name: 'Integration and API help',
    description: 'API calls, webhooks, SFTP feeds and third-party connectors.',
    audience: 'external',
    routing: { queueId: Q.ENGINEERING },
    submitLabel: 'Get engineering help',
    confirmation: 'A support engineer will pick this up. Include a trace ID and we can usually answer on the first reply.',
    ownerId: USR.LISA,
    updatedAt: '2026-08-15T16:00:00',
    submissions30d: 55,
    enabled: true,
    fields: [
      { id: 'int-surface', type: 'select', label: 'Which integration surface?', required: true,
        options: ['REST API', 'Webhooks', 'SFTP catalog feed', 'Zapier connector', 'Shopify bridge', 'Custom connector'] },
      { id: 'int-env', type: 'select', label: 'Environment', required: true, options: ['Sandbox', 'Production'] },
      { id: 'int-endpoint', type: 'text', label: 'Endpoint or event name', required: false,
        placeholder: 'e.g. POST /v2/orders  ·  order.fulfilled' },
      { id: 'int-expected', type: 'textarea', label: 'What did you expect, and what came back?', required: true,
        placeholder: 'Include the status code and the response body if you have them.' },
      { id: 'int-trace', type: 'text', label: 'Request or trace ID', required: false,
        placeholder: 'From the x-nw-trace-id response header' },
      { id: 'int-prod-impact', type: 'select', label: 'Production impact', required: true,
        options: ['Orders are failing', 'Data is stale but flowing', 'Only affects our sandbox work', 'No impact — planning a build'],
        showIf: { fieldId: 'int-env', op: 'is', value: 'Production' } },
      { id: 'int-logs', type: 'file', label: 'Logs or HAR file', required: false },
    ],
  },
];

/* ==================================================================== *
 * FORMS — published portal entry points.
 *
 * A form is scoped to products. The portal shows a person the products their
 * form covers, they drill to an item, and the item offers its subforms. So the
 * form decides WHAT IS VISIBLE and the subform decides WHAT HAPPENS.
 * ==================================================================== */

export const FORMS = [
  {
    id: 'form-employee-help',
    name: 'Employee Help Centre',
    description: 'The one place Northwind staff go for anything IT, workplace, people or finance related.',
    headline: 'How can we help?',
    subhead: 'Search first — most answers are already written down. If not, raise a request and we will pick it up.',
    audience: 'internal',
    productIds: [CAT.P_ACCOUNTS, CAT.P_EMAIL, CAT.P_DEVICES, CAT.P_SOFTWARE, CAT.P_WORKPLACE],
    published: true,
    slug: 'help',
    requireSignIn: true,
    showKnowledge: true,
    ownerId: USR.EMMA,
    updatedAt: '2026-08-12T09:30:00',
    submissions30d: 612,
  },
  {
    id: 'form-storefront-support',
    name: 'Northwind Storefront Support',
    description: 'Customer-facing support for the Storefront product — bugs, billing, integrations and feature requests.',
    headline: 'Storefront support',
    subhead: 'Browse the guides, or tell us what is going wrong and we will get an engineer on it.',
    audience: 'external',
    productIds: [CAT.P_STOREFRONT],
    published: true,
    slug: 'support',
    requireSignIn: false,
    showKnowledge: true,
    ownerId: USR.LISA,
    updatedAt: '2026-08-15T08:00:00',
    submissions30d: 1184,
  },
  {
    id: 'form-new-hire-onboarding',
    name: 'New Hire Onboarding',
    description: 'A narrow form for hiring managers: raise everything a new joiner needs from one page.',
    headline: 'Bringing someone new in?',
    subhead: 'One submission opens the account, orders the kit and books the desk.',
    audience: 'internal',
    productIds: [CAT.P_WORKPLACE, CAT.P_DEVICES, CAT.P_ACCOUNTS],
    published: true,
    slug: 'onboarding',
    requireSignIn: true,
    showKnowledge: true,
    ownerId: USR.PATTI,
    updatedAt: '2026-08-12T12:05:00',
    submissions30d: 23,
  },
  {
    id: 'form-partner-portal',
    name: 'Partner Portal',
    description: 'Reseller and implementation-partner intake. Held back until the partner tier pricing is signed off.',
    headline: 'Partner support',
    subhead: 'Deal registration, implementation help and co-selling questions.',
    audience: 'external',
    productIds: [CAT.P_STOREFRONT],
    published: false,
    slug: 'partners',
    requireSignIn: true,
    showKnowledge: false,
    ownerId: USR.ADMIN,
    updatedAt: '2026-07-09T15:45:00',
    submissions30d: 0,
  },
];
