/**
 * Service records seed — tickets, problems, changes and running approvals.
 *
 * This one file feeds FOUR modules (Workspace, Problems, Changes, Approvals),
 * so the records have to agree with each other: a ticket that says it is a
 * linked incident of a problem must appear in that problem's `linkedTicketIds`,
 * and a change that resolves a problem must be the problem's `resolvedByChangeId`.
 *
 * THE DEMO CLOCK IS 2026-08-16T09:00 (see `NOW` in store.js). Every timestamp
 * here is written as a local ISO string without a zone so it compares cleanly
 * against that clock — a `Z` suffix would shift the seed by the viewer's offset
 * and turn "2 hours ago" into "yesterday" depending on where the demo is run.
 *
 * TWO AUDIENCES ON ONE DESK. Northwind Systems runs RelayHQ for its own staff
 * AND for the customers who buy Northwind Storefront. Internal tickets carry
 * `isExternal: false` and a `requesterId` from the corporate directory; customer
 * tickets carry `isExternal: true`, a `contactId` and an `orgId`, and their SLA
 * comes from the account's plan rather than from the internal policy.
 *
 * Cross-domain ids come from ./ids.js — never spelled as literals.
 */

import { Q, SF, CAT, POL, SLA, KB, LOC, USR, ORG, CON } from './ids.js';

/* ==================================================================== *
 * TICKETS
 *
 * 22 records across three weeks. Eleven internal employee requests, eleven
 * external customer tickets. Six are breaching an SLA target right now, which
 * is what gives the workspace's overdue treatment something to draw.
 * ==================================================================== */

export const TICKETS = [
  /* ---------------- external: Lumen Retail Group (Enterprise) ---------------- */
  {
    id: 'tkt-4801',
    key: 'TKT-4801',
    title: 'Checkout returns 502 during Saturday peak traffic',
    description:
      'Between 21:40 and 22:10 CT roughly one in six checkout attempts returned a 502 from the storefront edge. '
      + 'Our own monitoring shows the orders API responding, so the failure looks like it sits between the edge and the '
      + 'checkout service. We took about $40k of abandoned baskets in that window across 214 stores.',
    status: 'in_progress',
    priority: 'urgent',
    queueId: Q.ENGINEERING,
    assigneeId: USR.ADMIN,
    isExternal: true,
    contactId: CON.DANA,
    orgId: ORG.LUMEN,
    source: 'phone',
    subformId: SF.STOREFRONT_BUG,
    catalogItemId: CAT.I_STOREFRONT_SETUP,
    labels: ['vip', 'possible-incident', 'checkout'],
    cc: [USR.LISA, USR.ADMIN, CON.RAVI],
    comments: [
      { id: 'cmt-4801-1', authorId: CON.DANA, body: 'Calling this in because the portal was also slow. Checkout is failing intermittently across every region.', internal: false, at: '2026-08-15T22:18:00' },
      { id: 'cmt-4801-2', authorId: USR.LISA, body: 'Dana — we have you. Paging the on-call engineer now and opening an incident bridge. I will update you every 20 minutes until this clears.', internal: false, at: '2026-08-15T22:41:00' },
      { id: 'cmt-4801-3', authorId: USR.PRIYA, body: 'Edge is shedding load — the checkout pool is saturating its connection limit at ~3.2k rps and the LB returns 502 rather than queueing. Same signature as PRB-201. Rolling the pool size up by hand as a stopgap.', internal: true, at: '2026-08-15T23:07:00' },
      { id: 'cmt-4801-4', authorId: USR.PRIYA, body: 'Error rate is back to baseline as of 23:20 CT. The manual pool increase holds until the adaptive rate-limiting change (CHG-1047) lands next weekend. Leaving this open until we have a full 24 hours clean.', internal: false, at: '2026-08-15T23:34:00' },
      { id: 'cmt-4801-5', authorId: USR.ADMIN, body: 'Resolution target passed at 02:18. Keeping the breach on the record rather than resetting the clock — Lumen will see it in the monthly report and we should be the ones who mention it first.', internal: true, at: '2026-08-16T08:05:00' },
    ],
    links: [
      { type: 'problem', id: 'prb-checkout-502' },
      { type: 'change', id: 'chg-1047' },
    ],
    slaPolicyId: SLA.ENTERPRISE,
    firstResponseAt: '2026-08-15T22:41:00',
    createdAt: '2026-08-15T22:18:00',
    updatedAt: '2026-08-16T08:05:00',
  },
  {
    id: 'tkt-4802',
    key: 'TKT-4802',
    title: 'Store 214 register cannot sync inventory after the 3.4 upgrade',
    description:
      'Since the 3.4 rollout on Tuesday, the register at store 214 shows stock counts that are two to three hours stale. '
      + 'Manual "sync now" reports success but nothing changes. Two other stores in the Midwest region look the same.',
    status: 'open',
    priority: 'high',
    queueId: Q.SUPPORT,
    assigneeId: USR.DEVON,
    isExternal: true,
    contactId: CON.RAVI,
    orgId: ORG.LUMEN,
    source: 'email',
    subformId: SF.STOREFRONT_BUG,
    catalogItemId: CAT.I_STOREFRONT_SETUP,
    labels: ['enterprise', 'sync', 'release-3.4'],
    cc: [CON.DANA, USR.LISA],
    comments: [
      { id: 'cmt-4802-1', authorId: CON.RAVI, body: 'Attaching the register log for 214. The sync job says "completed 0 records" every fifteen minutes.', internal: false, at: '2026-08-14T09:40:00' },
      { id: 'cmt-4802-2', authorId: USR.DEVON, body: 'Thanks Ravi — I can reproduce this against your sandbox. "Completed 0 records" is the tell: the delta cursor is not advancing. Escalating to engineering with the log attached.', internal: false, at: '2026-08-14T10:12:00' },
      { id: 'cmt-4802-3', authorId: USR.DEVON, body: 'Three tenants now. Attaching to PRB-202 rather than chasing each store separately.', internal: true, at: '2026-08-14T16:30:00' },
      { id: 'cmt-4802-4', authorId: USR.PRIYA, body: 'Confirmed: the 3.4 migration left the cursor table with a null watermark for tenants created before 2023. Fix is a one-line backfill, going into the next patch train.', internal: true, at: '2026-08-15T11:02:00' },
    ],
    links: [
      { type: 'problem', id: 'prb-sync-334' },
    ],
    slaPolicyId: SLA.ENTERPRISE,
    firstResponseAt: '2026-08-14T10:12:00',
    createdAt: '2026-08-14T09:40:00',
    updatedAt: '2026-08-15T11:02:00',
  },
  {
    id: 'tkt-4803',
    key: 'TKT-4803',
    title: 'Duplicate charge on August invoice INV-20418',
    description:
      'We were billed twice for the August seat count — $4,250 on the 1st and again on the 3rd. '
      + 'The second charge does not appear in the billing history in the admin console, only on the card statement.',
    status: 'pending',
    priority: 'medium',
    queueId: Q.SUPPORT,
    assigneeId: USR.NADIA,
    isExternal: true,
    contactId: CON.BEA,
    orgId: ORG.PARKWAY,
    source: 'portal',
    subformId: SF.BILLING_QUESTION,
    catalogItemId: CAT.I_BILLING,
    labels: ['billing', 'refund-requested'],
    cc: [USR.MICHAEL],
    comments: [
      { id: 'cmt-4803-1', authorId: CON.BEA, body: 'Statement screenshot attached. Please confirm the second charge will be reversed before our month-end close on the 20th.', internal: false, at: '2026-08-15T13:30:00' },
      { id: 'cmt-4803-2', authorId: USR.NADIA, body: 'Beatriz — I can see both charges on our side and the second one is a retry that should have been idempotent. I have asked Finance to raise the credit today. You will have confirmation well before the 20th.', internal: false, at: '2026-08-15T15:02:00' },
      { id: 'cmt-4803-3', authorId: USR.MICHAEL, body: 'Credit note drafted, needs the CFO signature which I will have Monday. Parking this on the customer until then so the clock is not running against Support.', internal: true, at: '2026-08-15T16:20:00' },
    ],
    links: [],
    slaPolicyId: SLA.BUSINESS,
    firstResponseAt: '2026-08-15T15:02:00',
    createdAt: '2026-08-15T13:30:00',
    updatedAt: '2026-08-15T16:20:00',
  },
  {
    id: 'tkt-4804',
    key: 'TKT-4804',
    title: 'API keys rotated — webhook deliveries now failing with 401',
    description:
      'We rotated our production API keys last night as part of a scheduled security review. '
      + 'Inbound calls work with the new key, but every outbound webhook you send us is being signed with the old secret '
      + 'and our gateway rejects it. Roughly 4,000 order events are queued behind this.',
    status: 'in_progress',
    priority: 'high',
    queueId: Q.ENGINEERING,
    assigneeId: USR.PRIYA,
    isExternal: true,
    contactId: CON.OWEN,
    orgId: ORG.VIREO,
    source: 'email',
    subformId: SF.INTEGRATION_HELP,
    catalogItemId: CAT.I_PAYMENTS,
    labels: ['vip', 'api', 'webhooks'],
    cc: [USR.LISA, CON.MEI],
    comments: [
      { id: 'cmt-4804-1', authorId: CON.OWEN, body: 'This is blocking our overnight reconciliation. We need either a resend or a way to force the signing secret to refresh.', internal: false, at: '2026-08-16T07:20:00' },
      { id: 'cmt-4804-2', authorId: USR.PRIYA, body: 'Owen — the signing secret is cached for up to 60 minutes on our side, which is the gap you are seeing. I have flushed the cache for your tenant manually; deliveries should start succeeding within two minutes. The queued events will replay automatically.', internal: false, at: '2026-08-16T07:55:00' },
      { id: 'cmt-4804-3', authorId: USR.PRIYA, body: 'The 60-minute cache is documented nowhere. Raising it on PRB-203 so the rotation guide gets updated rather than us hand-flushing for every enterprise rotation.', internal: true, at: '2026-08-16T08:02:00' },
    ],
    links: [
      { type: 'problem', id: 'prb-webhook-retry' },
      { type: 'ticket', id: 'tkt-4822' },
    ],
    slaPolicyId: SLA.ENTERPRISE,
    firstResponseAt: '2026-08-16T07:55:00',
    createdAt: '2026-08-16T07:20:00',
    updatedAt: '2026-08-16T08:02:00',
  },
  {
    id: 'tkt-4805',
    key: 'TKT-4805',
    title: 'Bulk catalog import stalls at 40% for files over 20,000 rows',
    description:
      'Our clinical supplies catalog is 31,000 SKUs. The import gets to about 40% and then sits there — no error, no progress. '
      + 'Splitting the file into three works, but we have to do this weekly and the manual split is not sustainable.',
    status: 'open',
    priority: 'medium',
    queueId: Q.SUPPORT,
    assigneeId: USR.SAM,
    isExternal: true,
    contactId: CON.MEI,
    orgId: ORG.VIREO,
    source: 'portal',
    subformId: SF.STOREFRONT_BUG,
    catalogItemId: CAT.I_STOREFRONT_SETUP,
    labels: ['import', 'enterprise'],
    cc: [USR.LISA],
    comments: [
      { id: 'cmt-4805-1', authorId: CON.MEI, body: 'Third time this month. Happy to jump on a call if it helps to see it live.', internal: false, at: '2026-08-16T08:40:00' },
      { id: 'cmt-4805-2', authorId: USR.LISA, body: 'Sam, this is a good first enterprise ticket for you — the import guide (Import your catalog) covers the row-count ceiling and Mei has already done the workaround. Read it before you reply.', internal: true, at: '2026-08-16T08:52:00' },
    ],
    links: [],
    slaPolicyId: SLA.ENTERPRISE,
    firstResponseAt: null,
    createdAt: '2026-08-16T08:40:00',
    updatedAt: '2026-08-16T08:52:00',
  },
  {
    id: 'tkt-4806',
    key: 'TKT-4806',
    title: 'How do I connect Stripe to my storefront?',
    description: 'Just signed up. I have a Stripe account already — where do I put the keys?',
    status: 'resolved',
    priority: 'low',
    queueId: Q.SUPPORT,
    assigneeId: USR.NADIA,
    isExternal: true,
    contactId: CON.COLE,
    orgId: ORG.FERNBROOK,
    source: 'chat',
    subformId: SF.INTEGRATION_HELP,
    catalogItemId: CAT.I_PAYMENTS,
    labels: ['self-serve', 'deflectable'],
    cc: [],
    comments: [
      { id: 'cmt-4806-1', authorId: CON.COLE, body: 'Just signed up. I have a Stripe account already — where do I put the keys?', internal: false, at: '2026-08-11T10:02:00' },
      { id: 'cmt-4806-2', authorId: USR.NADIA, body: 'Welcome aboard, Cole. Settings → Payments → Connect a provider, then paste your publishable and secret keys. The "Connect payments" guide walks it in six screens and takes about four minutes.', internal: false, at: '2026-08-11T11:15:00' },
      { id: 'cmt-4806-3', authorId: CON.COLE, body: 'Perfect, done. Thank you!', internal: false, at: '2026-08-11T11:41:00' },
      { id: 'cmt-4806-4', authorId: USR.NADIA, body: 'Tagging deflectable — the guide answers this exactly and it still arrived as a chat. Worth surfacing it higher in the Starter onboarding.', internal: true, at: '2026-08-11T11:44:00' },
    ],
    links: [],
    slaPolicyId: SLA.STARTER,
    firstResponseAt: '2026-08-11T11:15:00',
    createdAt: '2026-08-11T10:02:00',
    updatedAt: '2026-08-11T11:44:00',
  },
  {
    id: 'tkt-4807',
    key: 'TKT-4807',
    title: 'Feature request: scheduled export of order data to our S3 bucket',
    description:
      'We currently poll the orders API every fifteen minutes and write to S3 ourselves. '
      + 'A native scheduled export would remove about 200 lines of glue code and a pager rotation.',
    status: 'open',
    priority: 'low',
    queueId: Q.SUPPORT,
    assigneeId: USR.ADMIN,
    isExternal: true,
    contactId: CON.DANA,
    orgId: ORG.LUMEN,
    source: 'email',
    subformId: SF.FEATURE_REQUEST,
    catalogItemId: CAT.I_STOREFRONT_SETUP,
    labels: ['feature-request', 'enterprise'],
    cc: [USR.MIKE, USR.JEN],
    comments: [
      { id: 'cmt-4807-1', authorId: CON.DANA, body: 'Not urgent. Raising it because it comes up in every quarterly review and I would rather it be on a roadmap than in my notes.', internal: false, at: '2026-08-14T13:05:00' },
      { id: 'cmt-4807-2', authorId: USR.ADMIN, body: 'Logged and routed to Product with your name on it, Dana. I will bring an answer to the September QBR either way — including if the answer is no.', internal: false, at: '2026-08-14T14:20:00' },
      { id: 'cmt-4807-3', authorId: USR.JEN, body: 'Fourth enterprise account to ask. Adding it to the Q4 shaping list.', internal: true, at: '2026-08-15T09:15:00' },
    ],
    links: [],
    slaPolicyId: SLA.ENTERPRISE,
    firstResponseAt: '2026-08-14T14:20:00',
    createdAt: '2026-08-14T13:05:00',
    updatedAt: '2026-08-15T09:15:00',
  },
  {
    id: 'tkt-4808',
    key: 'TKT-4808',
    title: 'Shipment webhook retries exhausted — orders stuck in Awaiting Fulfilment',
    description:
      'Our warehouse endpoint was down for a 25-minute maintenance window last night. '
      + 'Your retries gave up before we came back, and 1,180 orders are now sitting in Awaiting Fulfilment with no way to force a redelivery.',
    status: 'in_progress',
    priority: 'urgent',
    queueId: Q.ENGINEERING,
    assigneeId: USR.MIKE,
    isExternal: true,
    contactId: CON.BEA,
    orgId: ORG.PARKWAY,
    source: 'phone',
    subformId: SF.INTEGRATION_HELP,
    catalogItemId: CAT.I_PAYMENTS,
    labels: ['sla-at-risk', 'webhooks', 'fulfilment'],
    cc: [USR.LISA, USR.DEVON],
    comments: [
      { id: 'cmt-4808-1', authorId: CON.BEA, body: 'This is holding up same-day dispatch for two distribution centres. We need those events replayed this morning.', internal: false, at: '2026-08-15T16:05:00' },
      { id: 'cmt-4808-2', authorId: USR.DEVON, body: 'Beatriz — understood, treating this as urgent. Engineering can replay from the event log; I am confirming the window now.', internal: false, at: '2026-08-15T16:48:00' },
      { id: 'cmt-4808-3', authorId: USR.MIKE, body: 'Replay script is ready but it is a manual run against production, so it needs a change record. Raised as an emergency change; will execute as soon as it is authorised.', internal: true, at: '2026-08-15T18:22:00' },
      { id: 'cmt-4808-4', authorId: USR.MIKE, body: 'Retry budget is five attempts over ten minutes, which is shorter than most maintenance windows. That is the real defect — PRB-203.', internal: true, at: '2026-08-16T08:10:00' },
    ],
    links: [
      { type: 'problem', id: 'prb-webhook-retry' },
      { type: 'change', id: 'chg-1044' },
    ],
    slaPolicyId: SLA.BUSINESS,
    firstResponseAt: '2026-08-15T16:48:00',
    createdAt: '2026-08-15T16:05:00',
    updatedAt: '2026-08-16T08:10:00',
  },
  {
    id: 'tkt-4809',
    key: 'TKT-4809',
    title: 'Quarterly access review export is missing deactivated users',
    description:
      'The compliance export we run each quarter only lists active users. Our auditors need deactivated accounts and their '
      + 'deactivation dates in the same file. We have been assembling it by hand for two quarters.',
    status: 'open',
    priority: 'medium',
    queueId: Q.SUPPORT,
    assigneeId: USR.ADMIN,
    isExternal: true,
    contactId: CON.OWEN,
    orgId: ORG.VIREO,
    source: 'portal',
    subformId: SF.STOREFRONT_BUG,
    catalogItemId: CAT.I_STOREFRONT_SETUP,
    labels: ['vip', 'compliance'],
    cc: [CON.MEI],
    comments: [
      { id: 'cmt-4809-1', authorId: CON.OWEN, body: 'Auditors are on site the first week of September, so a fix or a documented manual process by then would be fine.', internal: false, at: '2026-08-13T08:55:00' },
      { id: 'cmt-4809-2', authorId: USR.ADMIN, body: 'Owen — noted, and the September date is achievable. I will confirm which of the two it is by the end of this week.', internal: false, at: '2026-08-13T09:30:00' },
      { id: 'cmt-4809-3', authorId: USR.ADMIN, body: 'I owe Owen an answer and I have not chased Product. This one is on me — resolution target went past yesterday morning.', internal: true, at: '2026-08-16T08:30:00' },
    ],
    links: [],
    slaPolicyId: SLA.ENTERPRISE,
    firstResponseAt: '2026-08-13T09:30:00',
    createdAt: '2026-08-13T08:55:00',
    updatedAt: '2026-08-16T08:30:00',
  },
  {
    id: 'tkt-4810',
    key: 'TKT-4810',
    title: 'Trial ended but I was charged for 12 seats',
    description:
      'I only ever had 3 people in the account. The invoice says 12 seats at $29. I think the seat count picked up the '
      + 'invitations I sent that were never accepted.',
    status: 'open',
    priority: 'high',
    queueId: Q.SUPPORT,
    assigneeId: USR.ADMIN,
    isExternal: true,
    contactId: CON.COLE,
    orgId: ORG.FERNBROOK,
    source: 'email',
    subformId: SF.BILLING_QUESTION,
    catalogItemId: CAT.I_BILLING,
    labels: ['billing'],
    cc: [USR.MICHAEL],
    comments: [
      { id: 'cmt-4810-1', authorId: CON.COLE, body: 'Please can someone look at this before it renews next month.', internal: false, at: '2026-08-16T07:10:00' },
    ],
    links: [],
    slaPolicyId: SLA.STARTER,
    firstResponseAt: null,
    createdAt: '2026-08-16T07:10:00',
    updatedAt: '2026-08-16T07:10:00',
  },
  {
    id: 'tkt-4811',
    key: 'TKT-4811',
    title: 'Storefront admin session times out after five minutes on Safari',
    description:
      'Chrome is fine. On Safari 18 the admin console logs us out after about five minutes of activity, every time. '
      + 'Two of our merchandisers are Safari-only and are losing work.',
    status: 'resolved',
    priority: 'medium',
    queueId: Q.SUPPORT,
    assigneeId: USR.DEVON,
    isExternal: true,
    contactId: CON.RAVI,
    orgId: ORG.LUMEN,
    source: 'chat',
    subformId: SF.STOREFRONT_BUG,
    catalogItemId: CAT.I_STOREFRONT_SETUP,
    labels: ['enterprise', 'browser'],
    cc: [CON.DANA],
    comments: [
      { id: 'cmt-4811-1', authorId: CON.RAVI, body: 'Reproducible on two machines, both Safari 18.1, both on macOS 15.', internal: false, at: '2026-08-01T09:58:00' },
      { id: 'cmt-4811-2', authorId: USR.DEVON, body: 'Thanks Ravi — that is enough to go on. Safari intelligent tracking prevention is evicting our session cookie because it is set on a secondary domain. We have a fix in flight.', internal: false, at: '2026-08-01T10:20:00' },
      { id: 'cmt-4811-3', authorId: USR.DEVON, body: 'CHG-1043 shipped over the weekend and moved the cookie to partitioned first-party storage. Ravi has confirmed Safari now holds the session for a full day. Resolving.', internal: false, at: '2026-08-03T09:12:00' },
    ],
    links: [
      { type: 'problem', id: 'prb-safari-session' },
      { type: 'change', id: 'chg-1043' },
    ],
    slaPolicyId: SLA.ENTERPRISE,
    firstResponseAt: '2026-08-01T10:20:00',
    createdAt: '2026-08-01T09:58:00',
    updatedAt: '2026-08-03T09:12:00',
  },

  /* ---------------- internal: Northwind staff ---------------- */
  {
    id: 'tkt-4812',
    key: 'TKT-4812',
    title: 'Cannot sign in to the reporting console after MFA reset',
    description:
      'IT reset my MFA yesterday so I could move to the new phone. SSO works everywhere else, but the reporting console '
      + 'still bounces me back to the login screen with "authentication context expired".',
    status: 'in_progress',
    priority: 'high',
    queueId: Q.IT,
    assigneeId: USR.EMMA,
    isExternal: false,
    requesterId: USR.SARAH,
    orgId: null,
    source: 'portal',
    subformId: SF.MFA_RESET,
    catalogItemId: CAT.I_MFA,
    labels: ['access', 'mfa'],
    cc: [USR.DAVID],
    comments: [
      { id: 'cmt-4812-1', authorId: USR.SARAH, body: 'I have the campaign readout at 11:00 and the numbers live in that console, so this is a bit time-critical.', internal: false, at: '2026-08-16T07:52:00' },
      { id: 'cmt-4812-2', authorId: USR.EMMA, body: 'Sarah — on it. The reporting console caches the auth context for 24 hours and the reset invalidated it mid-session. I am clearing your context now; sign out fully and back in.', internal: false, at: '2026-08-16T08:20:00' },
      { id: 'cmt-4812-3', authorId: USR.EMMA, body: 'This is the fourth of these since we moved to the new MFA provider. Worth a knowledge article rather than four identical tickets.', internal: true, at: '2026-08-16T08:24:00' },
    ],
    links: [
      { type: 'ticket', id: 'tkt-4822' },
    ],
    slaPolicyId: SLA.INTERNAL,
    firstResponseAt: '2026-08-16T08:20:00',
    createdAt: '2026-08-16T07:52:00',
    updatedAt: '2026-08-16T08:24:00',
  },
  {
    id: 'tkt-4813',
    key: 'TKT-4813',
    title: 'MacBook Pro screen flickers when docked at the Chicago hot desks',
    description:
      'Any hot desk on the 12th floor. The external display flickers roughly once a second until I unplug and replug the dock. '
      + 'It does not happen at my home setup with the same laptop.',
    status: 'open',
    priority: 'medium',
    queueId: Q.IT,
    assigneeId: USR.EMMA,
    isExternal: false,
    requesterId: USR.TOM,
    orgId: null,
    source: 'portal',
    subformId: SF.LAPTOP_REPAIR,
    catalogItemId: CAT.I_LAPTOP_ISSUE,
    labels: ['hardware', 'chicago'],
    cc: [USR.LINDA],
    comments: [
      { id: 'cmt-4813-1', authorId: USR.TOM, body: 'Happens on desks 12-04 through 12-11 at least. Colleagues report the same.', internal: false, at: '2026-08-13T10:15:00' },
      { id: 'cmt-4813-2', authorId: USR.EMMA, body: 'Tom — known issue with the older DisplayLink docks on that floor. Workaround for now: set the external display to 60Hz rather than 75Hz, which stops the flicker. Replacements are on order.', internal: false, at: '2026-08-13T11:40:00' },
      { id: 'cmt-4813-3', authorId: USR.EMMA, body: 'Leaving this open against the dock replacement change rather than closing with a workaround — eleven desks are affected and closing it hides the size of the problem.', internal: true, at: '2026-08-14T09:05:00' },
    ],
    links: [
      { type: 'problem', id: 'prb-dock-flicker' },
      { type: 'change', id: 'chg-1049' },
    ],
    slaPolicyId: SLA.INTERNAL,
    firstResponseAt: '2026-08-13T11:40:00',
    createdAt: '2026-08-13T10:15:00',
    updatedAt: '2026-08-14T09:05:00',
  },
  {
    id: 'tkt-4814',
    key: 'TKT-4814',
    title: 'Request: 8 Figma Enterprise seats for the design systems work',
    description:
      'Design systems work starts in September and needs shared libraries and branching, which are Enterprise-only. '
      + 'Eight seats at $75/month on an annual commit is $6,400 for the year.',
    status: 'pending',
    priority: 'medium',
    queueId: Q.PROCUREMENT,
    assigneeId: USR.JAMES,
    isExternal: false,
    requesterId: USR.PRIYA,
    orgId: null,
    source: 'portal',
    subformId: SF.SOFTWARE_REQUEST,
    catalogItemId: CAT.I_SOFTWARE_REQ,
    labels: ['needs-finance-review', 'software'],
    cc: [USR.JEN, USR.MICHAEL, USR.MIKE],
    comments: [
      { id: 'cmt-4814-1', authorId: USR.PRIYA, body: 'Quote attached. The vendor holds this price until 31 August.', internal: false, at: '2026-08-15T14:00:00' },
      { id: 'cmt-4814-2', authorId: USR.JAMES, body: 'Priya — over $5,000 so it takes the three-stage approval: your manager, Finance, then a skip-level quorum. Jen has already signed off this morning; it is with Finance now.', internal: false, at: '2026-08-16T06:10:00' },
      { id: 'cmt-4814-3', authorId: USR.JAMES, body: 'Vendor price expiry is the 31st. If Finance sits on this past the 25th I will ask for an extension rather than let it lapse quietly.', internal: true, at: '2026-08-16T06:14:00' },
    ],
    links: [
      { type: 'approval', id: 'apr-2' },
    ],
    slaPolicyId: SLA.INTERNAL,
    firstResponseAt: '2026-08-16T06:10:00',
    createdAt: '2026-08-15T14:00:00',
    updatedAt: '2026-08-16T06:14:00',
  },
  {
    id: 'tkt-4815',
    key: 'TKT-4815',
    title: 'New hire: Aisha Rahman starts 1 September — full onboarding',
    description:
      'Product designer joining the design systems team, based in New York, reporting to Mike Chen. '
      + 'Needs the standard designer kit, Figma and Notion access, and a desk on the 4th floor.',
    status: 'pending',
    priority: 'high',
    queueId: Q.PEOPLE,
    assigneeId: USR.PATTI,
    isExternal: false,
    requesterId: USR.MIKE,
    orgId: null,
    source: 'portal',
    subformId: SF.NEW_HIRE,
    catalogItemId: null,
    labels: ['onboarding'],
    cc: [USR.JEN, USR.EMMA, USR.LINDA],
    comments: [
      { id: 'cmt-4815-1', authorId: USR.MIKE, body: 'Offer signed. Start date is firm at 1 September.', internal: false, at: '2026-08-11T08:30:00' },
      { id: 'cmt-4815-2', authorId: USR.PATTI, body: 'Thanks Mike — the chain is running. Manager confirmation, then IT provisioning, then Facilities. I will chase each stage.', internal: false, at: '2026-08-11T09:10:00' },
      { id: 'cmt-4815-3', authorId: USR.PATTI, body: 'Stage 1 has been sitting with Jen since the 11th and is past its 24-hour clock. Nudging her directly today before the escalation fires and it becomes a People Ops problem.', internal: true, at: '2026-08-16T08:15:00' },
    ],
    links: [
      { type: 'approval', id: 'apr-3' },
    ],
    slaPolicyId: SLA.INTERNAL,
    firstResponseAt: '2026-08-11T09:10:00',
    createdAt: '2026-08-11T08:30:00',
    updatedAt: '2026-08-16T08:15:00',
  },
  {
    id: 'tkt-4816',
    key: 'TKT-4816',
    title: 'Meeting room 4B projector shows no signal',
    description: 'HDMI and USB-C both show "no signal". Tried three laptops and two cables.',
    status: 'resolved',
    priority: 'low',
    queueId: Q.FACILITIES,
    assigneeId: USR.LINDA,
    isExternal: false,
    requesterId: USR.ROBERT,
    orgId: null,
    source: 'email',
    subformId: SF.FACILITIES_ISSUE,
    catalogItemId: null,
    labels: ['chicago', 'meeting-rooms'],
    cc: [],
    comments: [
      { id: 'cmt-4816-1', authorId: USR.ROBERT, body: 'Board meeting is in there on Thursday so it would be good to have it working before then.', internal: false, at: '2026-08-05T12:40:00' },
      { id: 'cmt-4816-2', authorId: USR.LINDA, body: 'Robert — the input switcher had lost its config after the power cut on Sunday. Reset and tested with two laptops, all four inputs working. Thursday is fine.', internal: false, at: '2026-08-05T13:20:00' },
    ],
    links: [],
    slaPolicyId: SLA.INTERNAL,
    firstResponseAt: '2026-08-05T13:20:00',
    createdAt: '2026-08-05T12:40:00',
    updatedAt: '2026-08-05T14:02:00',
  },
  {
    id: 'tkt-4817',
    key: 'TKT-4817',
    title: 'Adobe Creative Cloud renewal — 14 seats due 30 September',
    description:
      'The current term ends 30 September. We are paying for 14 seats and the usage report shows 9 active in the last 90 days. '
      + 'I would like to renew at 10 and keep one spare.',
    status: 'open',
    priority: 'medium',
    queueId: Q.PROCUREMENT,
    assigneeId: USR.JAMES,
    isExternal: false,
    requesterId: USR.JEN,
    orgId: null,
    source: 'portal',
    subformId: SF.LICENSE_RENEWAL,
    catalogItemId: CAT.I_SOFTWARE_REQ,
    labels: ['renewal', 'software', 'cost-saving'],
    cc: [USR.MICHAEL, USR.MIKE],
    comments: [
      { id: 'cmt-4817-1', authorId: USR.JEN, body: 'Usage export attached. Dropping four seats saves roughly $3,400 a year.', internal: false, at: '2026-08-16T07:30:00' },
      { id: 'cmt-4817-2', authorId: USR.JAMES, body: 'Jen — good catch, and the timing works. I will open the renewal conversation with the reseller this week and come back with a quote at 10 seats.', internal: false, at: '2026-08-16T08:05:00' },
    ],
    links: [],
    slaPolicyId: SLA.INTERNAL,
    firstResponseAt: '2026-08-16T08:05:00',
    createdAt: '2026-08-16T07:30:00',
    updatedAt: '2026-08-16T08:05:00',
  },
  {
    id: 'tkt-4818',
    key: 'TKT-4818',
    title: 'Second monitor for the Austin support pod',
    description:
      'The three new agents in Austin are on single screens. Working a ticket, the knowledge base and a customer call on one '
      + '13-inch display is genuinely slowing them down.',
    status: 'open',
    priority: 'low',
    queueId: Q.PROCUREMENT,
    assigneeId: null,
    isExternal: false,
    requesterId: USR.DEVON,
    orgId: null,
    source: 'portal',
    subformId: SF.NEW_HARDWARE,
    catalogItemId: CAT.I_NEW_LAPTOP,
    labels: ['hardware', 'austin'],
    cc: [USR.LISA],
    comments: [
      { id: 'cmt-4818-1', authorId: USR.DEVON, body: 'Three of the 27-inch models we already standardised on. Nothing exotic.', internal: false, at: '2026-08-15T18:30:00' },
    ],
    links: [],
    slaPolicyId: SLA.INTERNAL,
    firstResponseAt: null,
    createdAt: '2026-08-15T18:30:00',
    updatedAt: '2026-08-15T18:30:00',
  },
  {
    id: 'tkt-4819',
    key: 'TKT-4819',
    title: 'Where do I find the macro library for refund replies?',
    description: 'Lisa mentioned there is a saved set of replies for refunds. I cannot find it in the agent console.',
    status: 'resolved',
    priority: 'low',
    queueId: Q.GENERAL,
    assigneeId: USR.ADMIN,
    isExternal: false,
    requesterId: USR.SAM,
    orgId: null,
    source: 'chat',
    subformId: null,
    catalogItemId: null,
    labels: ['how-to', 'deflectable', 'unrouted'],
    cc: [],
    comments: [
      { id: 'cmt-4819-1', authorId: USR.SAM, body: 'Sorry if this is obvious — second week.', internal: false, at: '2026-08-07T13:50:00' },
      { id: 'cmt-4819-2', authorId: USR.ADMIN, body: 'Never obvious in week two, Sam. Agent console → the lightning icon in the reply box, or type two colons. The "Using macros" guide is four screens and worth doing once properly.', internal: false, at: '2026-08-07T14:05:00' },
      { id: 'cmt-4819-3', authorId: USR.ADMIN, body: 'This arrived through chat with no request form, so it landed in General. Third one this month from a new agent — the onboarding curriculum should cover macros in week one.', internal: true, at: '2026-08-07T14:09:00' },
    ],
    links: [],
    slaPolicyId: SLA.INTERNAL,
    firstResponseAt: '2026-08-07T14:05:00',
    createdAt: '2026-08-07T13:50:00',
    updatedAt: '2026-08-07T14:09:00',
  },
  {
    id: 'tkt-4820',
    key: 'TKT-4820',
    title: 'Offboarding: Marcus Bell, last working day 21 August',
    description:
      'Resigned Tuesday. Sales, Chicago, reports to Robert Smith. Needs access revoked at end of day on the 21st, '
      + 'laptop and badge collected, and his pipeline reassigned.',
    status: 'in_progress',
    priority: 'high',
    queueId: Q.PEOPLE,
    assigneeId: USR.PATTI,
    isExternal: false,
    requesterId: USR.ROBERT,
    orgId: null,
    source: 'portal',
    subformId: SF.OFFBOARDING,
    catalogItemId: null,
    labels: ['offboarding', 'access-review'],
    cc: [USR.EMMA, USR.LINDA, USR.ADMIN],
    comments: [
      { id: 'cmt-4820-1', authorId: USR.ROBERT, body: 'Amicable departure, going to a non-competing company. Standard process is fine.', internal: false, at: '2026-08-14T09:35:00' },
      { id: 'cmt-4820-2', authorId: USR.PATTI, body: 'Robert — the clearance chain has started. I will confirm the final date with you before IT revokes anything.', internal: false, at: '2026-08-14T10:00:00' },
      { id: 'cmt-4820-3', authorId: USR.EMMA, body: 'Privileged access list pulled: Salesforce admin, the reporting console and the shared sales drive. All three scheduled for 21 August 18:00.', internal: true, at: '2026-08-15T11:30:00' },
      { id: 'cmt-4820-4', authorId: USR.ADMIN, body: 'Resolution target went past on the 15th. It is not really late — the work is date-bound to the 21st — but the record says late, and I would rather fix the SLA policy for offboarding than quietly ignore the flag.', internal: true, at: '2026-08-16T08:40:00' },
    ],
    links: [],
    slaPolicyId: SLA.INTERNAL,
    firstResponseAt: '2026-08-14T10:00:00',
    createdAt: '2026-08-14T09:35:00',
    updatedAt: '2026-08-16T08:40:00',
  },
  {
    id: 'tkt-4821',
    key: 'TKT-4821',
    title: 'Sponsorship deposit for the Retail Ops Summit — $1,800',
    description: 'Deposit to hold the silver sponsorship slot at the Retail Ops Summit in October. Invoice attached.',
    status: 'resolved',
    priority: 'low',
    queueId: Q.FINANCE,
    assigneeId: USR.MICHAEL,
    isExternal: false,
    requesterId: USR.SARAH,
    orgId: null,
    source: 'portal',
    subformId: SF.EXPENSE_APPROVAL,
    catalogItemId: null,
    labels: ['spend', 'marketing'],
    cc: [USR.DAVID],
    comments: [
      { id: 'cmt-4821-1', authorId: USR.SARAH, body: 'The slot is held until the end of the week, so an answer by Friday would be ideal.', internal: false, at: '2026-08-06T09:15:00' },
      { id: 'cmt-4821-2', authorId: USR.MICHAEL, body: 'Sarah — David approved this morning and it is under the $5,000 threshold, so no further stages. Payment goes out on Friday.', internal: false, at: '2026-08-06T10:40:00' },
    ],
    links: [
      { type: 'approval', id: 'apr-5' },
    ],
    slaPolicyId: SLA.INTERNAL,
    firstResponseAt: '2026-08-06T10:40:00',
    createdAt: '2026-08-06T09:15:00',
    updatedAt: '2026-08-06T15:20:00',
  },
  {
    id: 'tkt-4822',
    key: 'TKT-4822',
    title: 'Request admin access to the Salesforce sandbox for the CRM migration',
    description:
      'I am doing the data mapping for the CRM migration and need admin rather than read on the sandbox so I can create '
      + 'custom objects. Read-only until the mapping is signed off would also work but slows the work considerably.',
    status: 'open',
    priority: 'medium',
    queueId: Q.IT,
    assigneeId: USR.EMMA,
    isExternal: false,
    requesterId: USR.TOM,
    orgId: null,
    source: 'portal',
    subformId: SF.REQUEST_ACCESS,
    catalogItemId: CAT.I_MFA,
    labels: ['access-review', 'crm-migration'],
    cc: [USR.ROBERT],
    comments: [
      { id: 'cmt-4822-1', authorId: USR.TOM, body: 'Happy to take a time-boxed grant if that is easier — two weeks would cover the mapping.', internal: false, at: '2026-08-15T08:50:00' },
      { id: 'cmt-4822-2', authorId: USR.EMMA, body: 'Tom — admin on the sandbox still carries production data, so this goes through the privileged access policy. Robert has approved; I have not, and I want to talk through the time-boxed option first.', internal: false, at: '2026-08-15T09:20:00' },
      { id: 'cmt-4822-3', authorId: USR.EMMA, body: 'Rejected the standing admin grant. Offering a two-week scoped role instead, which does what Tom actually needs. Reopening as a new request once he confirms.', internal: true, at: '2026-08-15T15:40:00' },
    ],
    links: [
      { type: 'approval', id: 'apr-4' },
      { type: 'ticket', id: 'tkt-4812' },
    ],
    slaPolicyId: SLA.INTERNAL,
    firstResponseAt: '2026-08-15T09:20:00',
    createdAt: '2026-08-15T08:50:00',
    updatedAt: '2026-08-15T15:40:00',
  },
];

/* ==================================================================== *
 * PROBLEMS
 *
 * A problem is the cause behind repeated incidents. The rule this seed
 * encodes: a problem in `known_error` MUST carry a workaround, because a known
 * error without one is just an open problem with a nicer label.
 * ==================================================================== */

export const PROBLEMS = [
  {
    id: 'prb-checkout-502',
    key: 'PRB-201',
    title: 'Checkout service returns 502 under sustained peak load',
    description:
      'Above roughly 3,000 requests per second the checkout connection pool saturates. The edge load balancer returns 502 '
      + 'rather than queueing, so the customer sees a hard failure instead of a slow page.',
    status: 'known_error',
    priority: 'urgent',
    ownerId: USR.PRIYA,
    queueId: Q.ENGINEERING,
    category: 'Performance',
    affectedServices: ['Northwind Storefront — Checkout API', 'Edge load balancer'],
    affectedLocationIds: [LOC.DC1],
    symptoms:
      'Intermittent 502s from /checkout during peak windows; error rate correlates with requests per second rather than with '
      + 'any single tenant. Orders API stays healthy throughout, which is why the first three incidents were misdiagnosed.',
    impact: 'Two enterprise accounts, an estimated $40k of abandoned baskets per affected peak window.',
    linkedTicketIds: ['tkt-4801'],
    workaround: {
      summary: 'Raise the checkout pool size by hand ahead of a known peak window.',
      steps: [
        'Confirm the peak is expected — retail Saturdays 20:00–23:00 CT and the first two days of a promotion.',
        'Scale the checkout pool from 128 to 320 connections in the edge config.',
        'Watch p99 latency for ten minutes; roll back if it climbs above 900ms.',
        'Return the pool to 128 within 24 hours, because the larger pool costs database headroom the reporting jobs need.',
      ],
      knowledgeId: KB.ESCALATION_PATHS,
      publishedToPortal: false,
    },
    rootCause:
      'The pool size was fixed at a value chosen in 2023 for a third of the current traffic, and the load balancer treats '
      + 'pool exhaustion as an upstream failure rather than applying backpressure.',
    rca: {
      technique: 'five_whys',
      statements: [
        'Customers saw 502 at checkout — because the edge returned 502.',
        'The edge returned 502 — because the checkout upstream refused new connections.',
        'The upstream refused connections — because its pool was exhausted at 128.',
        'The pool was exhausted — because the limit is static and was set for 2023 traffic.',
        'The limit is static — because nothing recalculates it and no alert fires before exhaustion.',
      ],
      contributingFactors: [
        'No alert on pool utilisation, only on error rate — so the first signal is customer-visible.',
        'Peak windows are predictable but not fed into capacity planning.',
      ],
    },
    resolvedByChangeId: 'chg-1047',
    labels: ['checkout', 'capacity'],
    identifiedAt: '2026-07-27T11:00:00',
    createdAt: '2026-07-27T11:00:00',
    updatedAt: '2026-08-16T08:05:00',
    resolvedAt: null,
  },
  {
    id: 'prb-sync-334',
    key: 'PRB-202',
    title: 'Register sync silently drops updates for tenants created before 2023',
    description:
      'After the 3.4 upgrade the inventory delta cursor stops advancing for older tenants. The sync job reports success with '
      + 'zero records, so nothing alerts and the store simply shows stale stock.',
    status: 'investigating',
    priority: 'high',
    ownerId: USR.PRIYA,
    queueId: Q.ENGINEERING,
    category: 'Data integrity',
    affectedServices: ['Inventory sync worker', 'Northwind Storefront — Admin API'],
    affectedLocationIds: [LOC.DC1],
    symptoms: 'Sync completes with "0 records" every cycle; stock counts drift by hours; only tenants provisioned before 2023 affected.',
    impact: 'Three enterprise tenants, roughly 640 retail locations showing stale stock to shoppers.',
    linkedTicketIds: ['tkt-4802'],
    workaround: null,
    rootCause: null,
    rca: {
      technique: 'timeline',
      statements: [
        '11 Aug 02:00 — 3.4 migration ran, adding a watermark column with no backfill for legacy rows.',
        '11 Aug 06:00 — first sync cycle after the migration reports 0 records for legacy tenants.',
        '14 Aug 09:40 — first customer report (TKT-4802). Three days of silent drift before anyone noticed.',
      ],
      contributingFactors: [
        'A "success with zero records" outcome is indistinguishable from "nothing changed" in the current logging.',
        'The migration was tested only against tenants created in the last 18 months.',
      ],
    },
    resolvedByChangeId: null,
    labels: ['release-3.4', 'sync'],
    identifiedAt: '2026-08-14T16:30:00',
    createdAt: '2026-08-14T16:30:00',
    updatedAt: '2026-08-15T11:02:00',
    resolvedAt: null,
  },
  {
    id: 'prb-webhook-retry',
    key: 'PRB-203',
    title: 'Webhook retry budget is shorter than a normal customer maintenance window',
    description:
      'Outbound webhooks retry five times over ten minutes and then drop the event permanently. Any customer maintenance '
      + 'window longer than ten minutes loses events with no way to replay them from the console.',
    status: 'known_error',
    priority: 'high',
    ownerId: USR.MIKE,
    queueId: Q.ENGINEERING,
    category: 'Integration',
    affectedServices: ['Webhook dispatcher', 'Event log'],
    affectedLocationIds: [LOC.DC1],
    symptoms: 'Events reported as delivered-failed after ten minutes; no replay control in the customer console; support has to run a script.',
    impact: 'Every integrated customer. Two incidents in the last month, 1,180 orders held in one of them.',
    linkedTicketIds: ['tkt-4808', 'tkt-4804'],
    workaround: {
      summary: 'Support-run replay from the event log, raised as an emergency change because it writes to production.',
      steps: [
        'Confirm the customer endpoint is healthy again before replaying anything.',
        'Raise an emergency change with the tenant id and the event window.',
        'Run the replay script with --dry-run first and share the event count with the customer.',
        'Execute, then confirm the delivered count matches the dry run.',
      ],
      knowledgeId: KB.WEBHOOK_SETUP,
      publishedToPortal: true,
    },
    rootCause:
      'The retry schedule was copied from an internal service-to-service default where a ten-minute budget is generous. '
      + 'For a customer-owned endpoint behind a maintenance window it is far too short, and the secret cache adds a second, '
      + 'undocumented sixty-minute failure mode after a key rotation.',
    rca: {
      technique: 'five_whys',
      statements: [
        'Customers lost order events — because the dispatcher gave up retrying.',
        'It gave up — because the budget is five attempts over ten minutes.',
        'The budget is ten minutes — because it was inherited from an internal default.',
        'The internal default was reused — because nobody owned the outbound contract separately.',
        'Nobody owned it — because webhooks shipped as a feature, not as a service with an SLO.',
      ],
      contributingFactors: [
        'No customer-facing replay control, so every recovery becomes a support ticket and a production script run.',
        'The sixty-minute signing-secret cache is not documented in the key rotation guide.',
      ],
    },
    resolvedByChangeId: null,
    labels: ['webhooks', 'integration'],
    identifiedAt: '2026-08-05T09:00:00',
    createdAt: '2026-08-05T09:00:00',
    updatedAt: '2026-08-16T08:10:00',
    resolvedAt: null,
  },
  {
    id: 'prb-safari-session',
    key: 'PRB-204',
    title: 'Safari tracking prevention evicts the admin session cookie',
    description:
      'The admin console session cookie was set on a secondary domain. Safari intelligent tracking prevention treats it as '
      + 'third-party and evicts it after roughly five minutes of activity, logging the user out mid-task.',
    status: 'resolved',
    priority: 'medium',
    ownerId: USR.PRIYA,
    queueId: Q.ENGINEERING,
    category: 'Browser compatibility',
    affectedServices: ['Northwind Storefront — Admin console'],
    affectedLocationIds: [],
    symptoms: 'Session lost after ~5 minutes on Safari only; Chrome, Edge and Firefox unaffected; unsaved work lost.',
    impact: 'Roughly 8% of admin users across all plans. Two enterprise accounts raised it formally.',
    linkedTicketIds: ['tkt-4811'],
    workaround: {
      summary: 'Use a Chromium browser for admin work until the fix ships.',
      steps: [
        'Open the admin console in Chrome or Edge.',
        'If Safari is mandatory, disable "Prevent cross-site tracking" for the console domain only.',
      ],
      knowledgeId: KB.SSO_EXPLAINED,
      publishedToPortal: true,
    },
    rootCause: 'Session cookie issued on a secondary domain rather than partitioned first-party storage on the console origin.',
    rca: {
      technique: 'five_whys',
      statements: [
        'Safari users were logged out — because the session cookie was evicted.',
        'It was evicted — because Safari classified it as third-party.',
        'It was third-party — because it was set on a secondary domain.',
        'It was set on a secondary domain — because the console was originally a separate product.',
        'The domain was never merged — because nothing had broken until Safari tightened its policy.',
      ],
      contributingFactors: ['No Safari coverage in the browser test matrix.'],
    },
    resolvedByChangeId: 'chg-1043',
    labels: ['browser', 'session'],
    identifiedAt: '2026-07-26T14:20:00',
    createdAt: '2026-07-26T14:20:00',
    updatedAt: '2026-08-03T09:12:00',
    resolvedAt: '2026-08-03T09:12:00',
  },
  {
    id: 'prb-dock-flicker',
    key: 'PRB-205',
    title: 'DisplayLink firmware causes display flicker on the Chicago hot-desk docks',
    description:
      'Eleven hot desks on the 12th floor in Chicago use an older DisplayLink dock whose firmware mishandles 75Hz refresh '
      + 'over USB-C. The external display flickers roughly once a second until the dock is replugged.',
    status: 'known_error',
    priority: 'medium',
    ownerId: USR.EMMA,
    queueId: Q.IT,
    category: 'Endpoint hardware',
    affectedServices: ['Chicago hot-desk docking stations'],
    affectedLocationIds: [LOC.CHI],
    symptoms: 'Once-per-second flicker on the external display when docked; resolves on replug; recurs within the hour.',
    impact: 'Eleven desks on the 12th floor, roughly 30 staff on a rotation.',
    linkedTicketIds: ['tkt-4813'],
    workaround: {
      summary: 'Set the external display to 60Hz rather than 75Hz.',
      steps: [
        'System Settings → Displays → select the external display.',
        'Hold Option and click "Scaled" to reveal refresh rates.',
        'Choose 60Hz. The flicker stops immediately and survives a replug.',
      ],
      knowledgeId: KB.SCREEN_FLICKER,
      publishedToPortal: false,
    },
    rootCause: 'Vendor firmware 3.11 mishandles 75Hz over USB-C on the DL-6950 chipset. The vendor has no fix planned; the units are end-of-life.',
    rca: {
      technique: 'five_whys',
      statements: [
        'Displays flicker at the hot desks — because the dock drops frames at 75Hz.',
        'It drops frames — because firmware 3.11 mishandles that mode on this chipset.',
        'The firmware is not fixed — because the vendor declared the unit end-of-life.',
        'We still run end-of-life docks — because they were bought outright and nothing had failed.',
        'Nothing prompted replacement — because docks are not in the asset refresh cycle.',
      ],
      contributingFactors: ['Docking stations were never added to the hardware refresh schedule.'],
    },
    resolvedByChangeId: 'chg-1049',
    labels: ['hardware', 'chicago'],
    identifiedAt: '2026-08-06T10:00:00',
    createdAt: '2026-08-06T10:00:00',
    updatedAt: '2026-08-14T09:05:00',
    resolvedAt: null,
  },
];

/* ==================================================================== *
 * CHANGES
 *
 * Three types (standard / normal / emergency) spread across the ITIL lifecycle.
 *
 * THE CONFLICT PAIR IS DELIBERATE: chg-1045 and chg-1047 both touch the
 * checkout API in the Elk Grove data centre and their windows overlap on the
 * night of 22 August. The calendar's conflict detector should find exactly that
 * pair — an overlapping window plus a shared affected service or location.
 *
 * `riskAnswers` uses the same eight keys on every record so a risk score can be
 * derived rather than typed in.
 * ==================================================================== */

export const CHANGES = [
  {
    id: 'chg-1041',
    key: 'CHG-1041',
    title: 'Quarterly TLS certificate rotation — storefront edge',
    description:
      'Rotate the wildcard certificate on the storefront edge and the admin console origin. Pre-staged, verified against '
      + 'the staging edge, executed with the standard runbook.',
    changeType: 'standard',
    status: 'closed',
    risk: 'low',
    riskScore: 3,
    affectsProduction: true,
    ownerId: USR.EMMA,
    implementerId: USR.PRIYA,
    queueId: Q.ENGINEERING,
    plannedStart: '2026-08-01T22:00:00',
    plannedEnd: '2026-08-02T02:00:00',
    actualStart: '2026-08-01T22:04:00',
    actualEnd: '2026-08-01T23:12:00',
    affectedServices: ['Northwind Storefront — Edge', 'Admin console origin'],
    affectedLocationIds: [LOC.DC1],
    affectedCatalogItemIds: [CAT.I_STOREFRONT_SETUP],
    linkedTicketIds: [],
    linkedProblemIds: [],
    approvalId: null,
    approvalPolicyId: null,
    implementationPlan:
      '1. Stage the new certificate on both edge nodes.\n'
      + '2. Reload node A, verify the chain with openssl, watch error rate for ten minutes.\n'
      + '3. Repeat on node B.\n'
      + '4. Confirm OCSP stapling and expiry on both.',
    backoutPlan: 'Reload the previous certificate from the staged bundle. Under two minutes per node, no restart required.',
    testPlan: 'openssl s_client chain verification, synthetic checkout from three regions, TLS grade check.',
    riskAnswers: {
      affectsProduction: true,
      customerFacing: true,
      hasBackout: true,
      testedInStaging: true,
      previouslyExecuted: true,
      requiresDowntime: false,
      peopleAffected: 'many',
      securityImpact: true,
    },
    pir: {
      completed: true,
      successful: true,
      notes: 'Executed 50 minutes inside the window. No error-rate movement. Fourth consecutive clean run of this runbook.',
      followUps: ['Move certificate rotation to the automation workspace so it stops consuming a change slot.'],
    },
    labels: ['security', 'routine'],
    createdAt: '2026-07-26T10:00:00',
    updatedAt: '2026-08-02T09:00:00',
  },
  {
    id: 'chg-1042',
    key: 'CHG-1042',
    title: 'Increase the Postgres connection pool on the orders cluster',
    description:
      'Raise max_connections and the PgBouncer pool on the orders cluster to give the reporting workload headroom without '
      + 'starving checkout. Prerequisite for the adaptive rate-limiting work.',
    changeType: 'normal',
    status: 'review',
    risk: 'moderate',
    riskScore: 11,
    affectsProduction: true,
    ownerId: USR.PRIYA,
    implementerId: USR.PRIYA,
    queueId: Q.ENGINEERING,
    plannedStart: '2026-08-09T23:00:00',
    plannedEnd: '2026-08-10T03:00:00',
    actualStart: '2026-08-09T23:02:00',
    actualEnd: '2026-08-10T01:47:00',
    affectedServices: ['Orders database cluster', 'Northwind Storefront — Checkout API'],
    affectedLocationIds: [LOC.DC1],
    affectedCatalogItemIds: [CAT.I_STOREFRONT_SETUP],
    linkedTicketIds: [],
    linkedProblemIds: ['prb-checkout-502'],
    approvalId: null,
    approvalPolicyId: POL.NORMAL_CHANGE,
    implementationPlan:
      '1. Take a base measurement of connection utilisation and p99 latency.\n'
      + '2. Raise PgBouncer default_pool_size 40 → 90 on the replica path first.\n'
      + '3. Restart PgBouncer node by node, thirty-second gap.\n'
      + '4. Raise max_connections on the primary and reload.\n'
      + '5. Hold for sixty minutes of observation before declaring done.',
    backoutPlan: 'Revert both config values and reload. Connections drain within one minute; no data risk.',
    testPlan: 'Replay a recorded peak trace against staging at 1.4x; verify no connection errors and p99 under 700ms.',
    riskAnswers: {
      affectsProduction: true,
      customerFacing: false,
      hasBackout: true,
      testedInStaging: true,
      previouslyExecuted: false,
      requiresDowntime: false,
      peopleAffected: 'some',
      securityImpact: false,
    },
    pir: {
      completed: false,
      successful: true,
      notes: 'Executed cleanly and inside the window. Post-implementation review scheduled for the CAB on 19 August.',
      followUps: [],
    },
    labels: ['database', 'capacity'],
    createdAt: '2026-08-03T14:00:00',
    updatedAt: '2026-08-10T09:30:00',
  },
  {
    id: 'chg-1043',
    key: 'CHG-1043',
    title: 'Move the admin session cookie to partitioned first-party storage',
    description:
      'Serve the admin console session cookie from the console origin with the Partitioned attribute so Safari intelligent '
      + 'tracking prevention no longer evicts it. Permanent fix for PRB-204.',
    changeType: 'normal',
    status: 'closed',
    risk: 'moderate',
    riskScore: 12,
    affectsProduction: true,
    ownerId: USR.PRIYA,
    implementerId: USR.MIKE,
    queueId: Q.ENGINEERING,
    plannedStart: '2026-08-02T21:00:00',
    plannedEnd: '2026-08-03T01:00:00',
    actualStart: '2026-08-02T21:05:00',
    actualEnd: '2026-08-02T23:40:00',
    affectedServices: ['Northwind Storefront — Admin console', 'Identity service'],
    affectedLocationIds: [LOC.DC1],
    affectedCatalogItemIds: [CAT.I_STOREFRONT_SETUP],
    linkedTicketIds: ['tkt-4811'],
    linkedProblemIds: ['prb-safari-session'],
    approvalId: null,
    approvalPolicyId: POL.NORMAL_CHANGE,
    implementationPlan:
      '1. Deploy the identity service build that issues the cookie on the console origin.\n'
      + '2. Enable the Partitioned attribute behind a flag for internal tenants.\n'
      + '3. Verify on Safari 18, Chrome and Firefox.\n'
      + '4. Roll the flag to 100% and force a re-authentication for all admin sessions.',
    backoutPlan: 'Disable the flag; the previous cookie path is still served in parallel for 72 hours.',
    testPlan: 'Session persistence test on Safari 18 with tracking prevention on, for 60 minutes of activity across three tabs.',
    riskAnswers: {
      affectsProduction: true,
      customerFacing: true,
      hasBackout: true,
      testedInStaging: true,
      previouslyExecuted: false,
      requiresDowntime: false,
      peopleAffected: 'some',
      securityImpact: true,
    },
    pir: {
      completed: true,
      successful: true,
      notes: 'Forced re-authentication generated eleven "why was I logged out" tickets that we had not warned anyone about. The fix worked; the comms did not.',
      followUps: [
        'Any change that forces re-authentication gets a portal notice 24 hours ahead.',
        'Add Safari with tracking prevention enabled to the standing browser test matrix.',
      ],
    },
    labels: ['browser', 'session'],
    createdAt: '2026-07-28T11:00:00',
    updatedAt: '2026-08-05T10:00:00',
  },
  {
    id: 'chg-1044',
    key: 'CHG-1044',
    title: 'Emergency: replay held shipment webhooks for Parkway Logistics',
    description:
      'Replay 1,180 shipment events from the event log to the Parkway warehouse endpoint after their maintenance window '
      + 'exhausted the retry budget. Manual script run against production, so it takes a change record.',
    changeType: 'emergency',
    status: 'authorize',
    risk: 'high',
    riskScore: 17,
    affectsProduction: true,
    ownerId: USR.MIKE,
    implementerId: USR.MIKE,
    queueId: Q.ENGINEERING,
    plannedStart: '2026-08-16T10:30:00',
    plannedEnd: '2026-08-16T12:00:00',
    actualStart: null,
    actualEnd: null,
    affectedServices: ['Webhook dispatcher', 'Event log'],
    affectedLocationIds: [LOC.DC1],
    affectedCatalogItemIds: [CAT.I_PAYMENTS],
    linkedTicketIds: ['tkt-4808'],
    linkedProblemIds: ['prb-webhook-retry'],
    approvalId: 'apr-6',
    approvalPolicyId: POL.EMERGENCY_CHANGE,
    implementationPlan:
      '1. Confirm the Parkway endpoint is healthy with a single synthetic event.\n'
      + '2. Run the replay script with --dry-run for the window 15 Aug 15:30 – 16:05 and share the count with the customer.\n'
      + '3. Execute at 200 events per minute so the customer endpoint is not the next thing to fall over.\n'
      + '4. Reconcile delivered count against the dry-run count and confirm with Beatriz.',
    backoutPlan:
      'There is no backout for a delivered event. Mitigation is the rate limit and the dry run — if duplicates appear, '
      + 'stop the script and hand the customer the event id list so they can de-duplicate on their side.',
    testPlan: 'Dry run against production event log (read-only), plus a full replay against the Parkway sandbox tenant.',
    riskAnswers: {
      affectsProduction: true,
      customerFacing: true,
      hasBackout: false,
      testedInStaging: true,
      previouslyExecuted: true,
      requiresDowntime: false,
      peopleAffected: 'few',
      securityImpact: false,
    },
    pir: null,
    labels: ['emergency-change', 'webhooks'],
    createdAt: '2026-08-15T18:22:00',
    updatedAt: '2026-08-16T08:30:00',
  },
  {
    id: 'chg-1045',
    key: 'CHG-1045',
    title: 'Northwind Storefront 3.5 release to production',
    description:
      'The 3.5 release train: the legacy-tenant watermark backfill, the seat-count fix, the deactivated-user export column, '
      + 'and eleven smaller fixes. Full release, all tenants, single window.',
    changeType: 'normal',
    status: 'authorize',
    risk: 'high',
    riskScore: 18,
    affectsProduction: true,
    ownerId: USR.PRIYA,
    implementerId: USR.PRIYA,
    queueId: Q.ENGINEERING,
    plannedStart: '2026-08-22T22:00:00',
    plannedEnd: '2026-08-23T04:00:00',
    actualStart: null,
    actualEnd: null,
    affectedServices: ['Northwind Storefront — Checkout API', 'Northwind Storefront — Admin console', 'Inventory sync worker'],
    affectedLocationIds: [LOC.DC1],
    affectedCatalogItemIds: [CAT.I_STOREFRONT_SETUP, CAT.I_PAYMENTS],
    linkedTicketIds: ['tkt-4802', 'tkt-4809', 'tkt-4810'],
    linkedProblemIds: ['prb-sync-334'],
    approvalId: 'apr-1',
    approvalPolicyId: POL.NORMAL_CHANGE,
    implementationPlan:
      '1. Freeze deploys at 20:00 CT.\n'
      + '2. Run the watermark backfill against legacy tenants (est. 40 minutes) and verify cursor advance on three samples.\n'
      + '3. Deploy the application train to canary (5% of tenants), hold thirty minutes.\n'
      + '4. Roll to 100%.\n'
      + '5. Smoke the checkout, admin console and import paths.',
    backoutPlan:
      'Application rollback to 3.4.2 is a single command and takes four minutes. The backfill is additive and does not need '
      + 'reverting — 3.4.2 ignores the column.',
    testPlan: 'Full regression on staging, peak trace replay at 1.4x, import of a 31,000-row catalog, and the Safari session matrix.',
    riskAnswers: {
      affectsProduction: true,
      customerFacing: true,
      hasBackout: true,
      testedInStaging: true,
      previouslyExecuted: false,
      requiresDowntime: false,
      peopleAffected: 'many',
      securityImpact: false,
    },
    pir: null,
    labels: ['release', 'storefront-3.5'],
    createdAt: '2026-08-10T09:00:00',
    updatedAt: '2026-08-14T16:00:00',
  },
  {
    id: 'chg-1046',
    key: 'CHG-1046',
    title: 'Add a read replica in us-east-2 for reporting queries',
    description:
      'Move the nightly reporting workload off the primary onto a dedicated replica in a second region. Reduces the pressure '
      + 'that made CHG-1042 necessary and gives us a warm standby.',
    changeType: 'normal',
    status: 'assess',
    risk: 'moderate',
    riskScore: 10,
    affectsProduction: true,
    ownerId: USR.PRIYA,
    implementerId: USR.PRIYA,
    queueId: Q.ENGINEERING,
    plannedStart: '2026-09-05T22:00:00',
    plannedEnd: '2026-09-06T02:00:00',
    actualStart: null,
    actualEnd: null,
    affectedServices: ['Orders database cluster', 'Reporting service'],
    affectedLocationIds: [LOC.DC1],
    affectedCatalogItemIds: [],
    linkedTicketIds: [],
    linkedProblemIds: ['prb-checkout-502'],
    approvalId: null,
    approvalPolicyId: POL.NORMAL_CHANGE,
    implementationPlan:
      '1. Provision the replica and let it catch up (est. 6 hours, done ahead of the window).\n'
      + '2. Point the reporting connection string at the replica behind a flag.\n'
      + '3. Run the nightly batch against the replica and compare row counts with the previous night.\n'
      + '4. Remove the flag once two consecutive nights match.',
    backoutPlan: 'Flip the flag back to the primary. The replica stays provisioned and keeps replicating.',
    testPlan: 'Two nights of shadow batch runs with row-count and checksum comparison against the primary.',
    riskAnswers: {
      affectsProduction: true,
      customerFacing: false,
      hasBackout: true,
      testedInStaging: false,
      previouslyExecuted: false,
      requiresDowntime: false,
      peopleAffected: 'few',
      securityImpact: false,
    },
    pir: null,
    labels: ['database', 'capacity'],
    createdAt: '2026-08-12T13:00:00',
    updatedAt: '2026-08-15T10:00:00',
  },
  {
    id: 'chg-1047',
    key: 'CHG-1047',
    title: 'Adaptive rate limiting on the checkout API',
    description:
      'Replace the static connection pool with adaptive rate limiting at the edge, so peak load produces a queue and a slow '
      + 'page rather than a 502. Permanent fix for PRB-201.',
    changeType: 'normal',
    status: 'scheduled',
    risk: 'moderate',
    riskScore: 13,
    affectsProduction: true,
    ownerId: USR.PRIYA,
    implementerId: USR.MIKE,
    queueId: Q.ENGINEERING,
    plannedStart: '2026-08-22T23:00:00',
    plannedEnd: '2026-08-23T02:00:00',
    actualStart: null,
    actualEnd: null,
    affectedServices: ['Northwind Storefront — Checkout API', 'Edge load balancer'],
    affectedLocationIds: [LOC.DC1],
    affectedCatalogItemIds: [CAT.I_STOREFRONT_SETUP],
    linkedTicketIds: ['tkt-4801'],
    linkedProblemIds: ['prb-checkout-502'],
    approvalId: null,
    approvalPolicyId: POL.NORMAL_CHANGE,
    implementationPlan:
      '1. Deploy the adaptive limiter in observe-only mode and collect two hours of decisions without enforcing.\n'
      + '2. Compare the would-be shed rate against the recorded peak trace.\n'
      + '3. Enable enforcement at 20% of traffic, hold thirty minutes.\n'
      + '4. Enable at 100% and remove the manual pool override.',
    backoutPlan: 'Return the limiter to observe-only and restore the manual pool size of 320. One config push, under two minutes.',
    testPlan: 'Peak trace replay at 1.0x, 1.4x and 2.0x against staging; verify queueing rather than 502 at every level.',
    riskAnswers: {
      affectsProduction: true,
      customerFacing: true,
      hasBackout: true,
      testedInStaging: true,
      previouslyExecuted: false,
      requiresDowntime: false,
      peopleAffected: 'many',
      securityImpact: false,
    },
    pir: null,
    labels: ['checkout', 'capacity'],
    createdAt: '2026-08-04T11:00:00',
    updatedAt: '2026-08-14T15:00:00',
  },
  {
    id: 'chg-1048',
    key: 'CHG-1048',
    title: 'Monthly endpoint patch ring rollout — August',
    description:
      'Standard monthly OS and browser patch rollout across the three rings. Cancelled for August: the vendor pulled the '
      + 'August bundle after a kernel panic report and republished on the 21st, which lands outside this window.',
    changeType: 'standard',
    status: 'cancelled',
    risk: 'low',
    riskScore: 4,
    affectsProduction: false,
    ownerId: USR.EMMA,
    implementerId: USR.EMMA,
    queueId: Q.IT,
    plannedStart: '2026-08-19T18:00:00',
    plannedEnd: '2026-08-20T02:00:00',
    actualStart: null,
    actualEnd: null,
    affectedServices: ['Staff endpoints — all rings'],
    affectedLocationIds: [LOC.CHI, LOC.NYC, LOC.AUS, LOC.REMOTE],
    affectedCatalogItemIds: [CAT.I_LAPTOP_ISSUE],
    linkedTicketIds: [],
    linkedProblemIds: [],
    approvalId: null,
    approvalPolicyId: null,
    implementationPlan:
      '1. Ring 0 (IT, 12 devices) on day one.\n'
      + '2. Ring 1 (early adopters, 60 devices) after 24 clean hours.\n'
      + '3. Ring 2 (everyone else) after 72 clean hours.',
    backoutPlan: 'Patch rollback via the endpoint manager, ring by ring. Ring 0 acts as the canary.',
    testPlan: 'Ring 0 soak for 24 hours with crash reporting enabled.',
    riskAnswers: {
      affectsProduction: false,
      customerFacing: false,
      hasBackout: true,
      testedInStaging: true,
      previouslyExecuted: true,
      requiresDowntime: false,
      peopleAffected: 'many',
      securityImpact: true,
    },
    pir: null,
    cancelReason: 'Vendor withdrew the August bundle on 14 August after kernel panic reports. Rescheduling once the republished bundle has soaked for a week.',
    labels: ['endpoints', 'routine'],
    createdAt: '2026-08-01T09:00:00',
    updatedAt: '2026-08-14T11:20:00',
  },
  {
    id: 'chg-1049',
    key: 'CHG-1049',
    title: 'Replace the DisplayLink docks in the Chicago hot-desk pool',
    description:
      'Swap eleven end-of-life DL-6950 docks on the 12th floor for the current standard model. Permanent fix for PRB-205; '
      + 'the 60Hz workaround goes away with them.',
    changeType: 'standard',
    status: 'implement',
    risk: 'low',
    riskScore: 5,
    affectsProduction: false,
    ownerId: USR.EMMA,
    implementerId: USR.LINDA,
    queueId: Q.IT,
    plannedStart: '2026-08-17T09:00:00',
    plannedEnd: '2026-08-18T17:00:00',
    actualStart: '2026-08-17T09:10:00',
    actualEnd: null,
    affectedServices: ['Chicago hot-desk docking stations'],
    affectedLocationIds: [LOC.CHI],
    affectedCatalogItemIds: [CAT.I_LAPTOP_ISSUE],
    linkedTicketIds: ['tkt-4813'],
    linkedProblemIds: ['prb-dock-flicker'],
    approvalId: null,
    approvalPolicyId: null,
    implementationPlan:
      '1. Stage eleven replacement docks in the 12th floor store room.\n'
      + '2. Swap desks 12-04 to 12-11 outside core hours, four per morning.\n'
      + '3. Test each desk with a loaner laptop at 75Hz before signing it off.\n'
      + '4. Tag the old units for disposal and update the asset register.',
    backoutPlan: 'Old docks are retained for one week. A failed desk goes back to the previous unit and the 60Hz workaround.',
    testPlan: 'Per-desk test at 75Hz for ten minutes with a loaner laptop before the desk is returned to the pool.',
    riskAnswers: {
      affectsProduction: false,
      customerFacing: false,
      hasBackout: true,
      testedInStaging: false,
      previouslyExecuted: true,
      requiresDowntime: false,
      peopleAffected: 'some',
      securityImpact: false,
    },
    pir: null,
    labels: ['hardware', 'chicago'],
    createdAt: '2026-08-08T10:00:00',
    updatedAt: '2026-08-16T07:00:00',
  },
];

/* ==================================================================== *
 * APPROVALS
 *
 * Running ApprovalRequests, built to the model documented in
 * src/lib/approvals.js. Approvers are RESOLVED and frozen onto the request at
 * creation — that is why every stage carries a literal `approverIds` array
 * rather than the spec that produced it. The specs are kept alongside so the
 * ladder can explain *why* a person is being asked.
 *
 * Two of these (apr-1, apr-2) are decidable by Alex Rivera, the demo user, so
 * the Approvals inbox has something to click on load.
 * ==================================================================== */

export const APPROVALS = [
  {
    id: 'apr-1',
    policyId: POL.NORMAL_CHANGE,
    policyName: 'Normal change — CAB',
    subject: 'CHG-1045 · Northwind Storefront 3.5 release to production',
    targetType: 'change',
    targetId: 'chg-1045',
    requesterId: USR.PRIYA,
    onReject: 'stop',
    context: {
      requesterId: USR.PRIYA,
      changeId: 'chg-1045',
      change: { changeType: 'normal', risk: 'high', affectsProduction: true },
    },
    stages: [
      {
        id: 'stg-cab',
        index: 0,
        name: 'Change Advisory Board',
        approvers: [
          { kind: 'user', userId: USR.ADMIN },
          { kind: 'user', userId: USR.EMMA },
          { kind: 'user', userId: USR.PRIYA },
          { kind: 'user', userId: USR.JEN },
          { kind: 'user', userId: USR.MICHAEL },
        ],
        approverIds: [USR.ADMIN, USR.EMMA, USR.PRIYA, USR.JEN, USR.MICHAEL],
        unresolved: false,
        rule: 'quorum',
        quorum: 3,
        dueInHours: 72,
        onTimeout: 'escalate',
        escalateTo: { kind: 'role', role: 'admin' },
        decisions: [
          { approverId: USR.EMMA, verdict: 'approved', comment: 'Backout is a single command and the backfill is additive. Comfortable.', at: '2026-08-14T17:20:00' },
          { approverId: USR.JEN, verdict: 'approved', comment: 'Three customer-visible fixes in this train that we have promised by name. Yes.', at: '2026-08-15T10:05:00' },
        ],
        state: 'awaiting',
        startedAt: '2026-08-14T16:00:00',
        dueAt: '2026-08-17T16:00:00',
      },
    ],
    currentStage: 0,
    state: 'awaiting',
    createdAt: '2026-08-14T16:00:00',
    resolvedAt: null,
  },
  {
    id: 'apr-2',
    policyId: POL.SPEND_OVER_5000,
    policyName: 'Spend over $5,000',
    subject: 'TKT-4814 · Figma Enterprise — 8 seats, $6,400 annual',
    targetType: 'ticket',
    targetId: 'tkt-4814',
    requesterId: USR.PRIYA,
    onReject: 'stop',
    context: {
      requesterId: USR.PRIYA,
      ticketId: 'tkt-4814',
      answers: { amount: 6400, vendor: 'Figma', term: 'annual', seats: 8 },
    },
    stages: [
      {
        id: 'stg-5000-manager',
        index: 0,
        name: 'Manager sign-off',
        approvers: [{ kind: 'manager' }],
        approverIds: [USR.JEN],
        unresolved: false,
        rule: 'all',
        quorum: 1,
        dueInHours: 24,
        onTimeout: 'escalate',
        escalateTo: { kind: 'manager_of_manager' },
        decisions: [
          { approverId: USR.JEN, verdict: 'approved', comment: 'Budgeted in the design systems line. Approved.', at: '2026-08-16T06:00:00' },
        ],
        state: 'approved',
        startedAt: '2026-08-15T14:00:00',
        dueAt: '2026-08-16T14:00:00',
        resolvedAt: '2026-08-16T06:00:00',
      },
      {
        id: 'stg-5000-finance',
        index: 1,
        name: 'Finance review',
        approvers: [{ kind: 'queue', queueId: Q.FINANCE }],
        approverIds: [USR.MICHAEL, USR.ADMIN],
        unresolved: false,
        rule: 'any',
        quorum: 1,
        dueInHours: 12,
        onTimeout: 'escalate',
        escalateTo: { kind: 'user', userId: USR.MICHAEL },
        decisions: [],
        state: 'awaiting',
        startedAt: '2026-08-16T06:00:00',
        dueAt: '2026-08-16T18:00:00',
      },
      {
        id: 'stg-5000-skip',
        index: 2,
        name: 'Skip-level authorisation',
        approvers: [{ kind: 'manager_of_manager' }, { kind: 'role', role: 'manager' }],
        approverIds: [USR.ROBERT, USR.DAVID, USR.JEN],
        unresolved: false,
        rule: 'quorum',
        quorum: 2,
        dueInHours: 48,
        onTimeout: 'wait',
        escalateTo: null,
        decisions: [],
        state: 'pending',
        startedAt: null,
        dueAt: null,
      },
    ],
    currentStage: 1,
    state: 'awaiting',
    createdAt: '2026-08-15T14:00:00',
    resolvedAt: null,
  },
  {
    id: 'apr-3',
    policyId: POL.NEW_HIRE,
    policyName: 'New hire onboarding',
    subject: 'TKT-4815 · New hire onboarding — Aisha Rahman, start 1 September',
    targetType: 'ticket',
    targetId: 'tkt-4815',
    requesterId: USR.MIKE,
    onReject: 'stop',
    context: {
      requesterId: USR.MIKE,
      ticketId: 'tkt-4815',
      answers: { startDate: '2026-09-01', role: 'Product Designer', location: 'New York' },
    },
    stages: [
      {
        id: 'stg-hire-manager',
        index: 0,
        name: 'Hiring manager confirms the offer',
        approvers: [{ kind: 'manager' }],
        approverIds: [USR.JEN],
        unresolved: false,
        rule: 'all',
        quorum: 1,
        dueInHours: 24,
        onTimeout: 'escalate',
        escalateTo: { kind: 'department_head', department: 'People' },
        decisions: [],
        state: 'awaiting',
        startedAt: '2026-08-11T08:35:00',
        dueAt: '2026-08-12T08:35:00',
      },
      {
        id: 'stg-hire-it',
        index: 1,
        name: 'IT provisioning',
        approvers: [{ kind: 'queue', queueId: Q.IT }],
        approverIds: [USR.EMMA, USR.ADMIN, USR.DEVON],
        unresolved: false,
        rule: 'any',
        quorum: 1,
        dueInHours: 48,
        onTimeout: 'escalate',
        escalateTo: { kind: 'user', userId: USR.EMMA },
        decisions: [],
        state: 'pending',
        startedAt: null,
        dueAt: null,
      },
      {
        id: 'stg-hire-facilities',
        index: 2,
        name: 'Desk, badge and building access',
        approvers: [{ kind: 'queue', queueId: Q.FACILITIES }],
        approverIds: [USR.LINDA, USR.JAMES],
        unresolved: false,
        rule: 'any',
        quorum: 1,
        dueInHours: 72,
        onTimeout: 'wait',
        escalateTo: null,
        decisions: [],
        state: 'pending',
        startedAt: null,
        dueAt: null,
      },
    ],
    currentStage: 0,
    state: 'awaiting',
    createdAt: '2026-08-11T08:35:00',
    resolvedAt: null,
  },
  {
    id: 'apr-4',
    policyId: POL.ACCESS_GRANT,
    policyName: 'Privileged access grant',
    subject: 'TKT-4822 · Salesforce sandbox admin access for Tom Alvarez',
    targetType: 'ticket',
    targetId: 'tkt-4822',
    requesterId: USR.TOM,
    onReject: 'stop',
    context: {
      requesterId: USR.TOM,
      ticketId: 'tkt-4822',
      answers: { accessLevel: 'admin', system: 'Salesforce sandbox', duration: 'standing' },
    },
    stages: [
      {
        id: 'stg-access-owner',
        index: 0,
        name: 'System owner and manager',
        approvers: [{ kind: 'user', userId: USR.EMMA }, { kind: 'manager' }],
        approverIds: [USR.EMMA, USR.ROBERT],
        unresolved: false,
        rule: 'all',
        quorum: 2,
        dueInHours: 8,
        onTimeout: 'escalate',
        escalateTo: { kind: 'queue', queueId: Q.IT },
        decisions: [
          { approverId: USR.ROBERT, verdict: 'approved', comment: 'Tom needs this to finish the mapping. Fine by me.', at: '2026-08-15T10:05:00' },
          { approverId: USR.EMMA, verdict: 'rejected', comment: 'Standing admin on a sandbox holding production data is an audit finding waiting to happen. Rejecting this one and offering a two-week scoped role instead — same outcome, bounded blast radius.', at: '2026-08-15T15:40:00' },
        ],
        state: 'rejected',
        startedAt: '2026-08-15T08:55:00',
        dueAt: '2026-08-15T16:55:00',
        resolvedAt: '2026-08-15T15:40:00',
      },
    ],
    currentStage: 0,
    state: 'rejected',
    createdAt: '2026-08-15T08:55:00',
    resolvedAt: '2026-08-15T15:40:00',
  },
  {
    id: 'apr-5',
    policyId: POL.SPEND_OVER_500,
    policyName: 'Spend over $500',
    subject: 'TKT-4821 · Retail Ops Summit sponsorship deposit, $1,800',
    targetType: 'ticket',
    targetId: 'tkt-4821',
    requesterId: USR.SARAH,
    onReject: 'stop',
    context: {
      requesterId: USR.SARAH,
      ticketId: 'tkt-4821',
      answers: { amount: 1800, vendor: 'Retail Ops Summit', term: 'one-off' },
    },
    stages: [
      {
        id: 'stg-500-manager',
        index: 0,
        name: 'Manager sign-off',
        approvers: [{ kind: 'manager' }],
        approverIds: [USR.DAVID],
        unresolved: false,
        rule: 'all',
        quorum: 1,
        dueInHours: 24,
        onTimeout: 'escalate',
        escalateTo: { kind: 'manager_of_manager' },
        decisions: [
          { approverId: USR.DAVID, verdict: 'approved', comment: 'Same slot as last year and it paid for itself. Approved.', at: '2026-08-06T10:12:00' },
        ],
        state: 'approved',
        startedAt: '2026-08-06T09:20:00',
        dueAt: '2026-08-07T09:20:00',
        resolvedAt: '2026-08-06T10:12:00',
      },
    ],
    currentStage: 0,
    state: 'approved',
    createdAt: '2026-08-06T09:20:00',
    resolvedAt: '2026-08-06T10:12:00',
  },
  {
    id: 'apr-6',
    policyId: POL.EMERGENCY_CHANGE,
    policyName: 'Emergency change — on-call',
    subject: 'CHG-1044 · Replay held shipment webhooks for Parkway Logistics',
    targetType: 'change',
    targetId: 'chg-1044',
    requesterId: USR.MIKE,
    onReject: 'stop',
    context: {
      requesterId: USR.MIKE,
      changeId: 'chg-1044',
      change: { changeType: 'emergency', risk: 'high', affectsProduction: true },
    },
    stages: [
      {
        id: 'stg-emergency-oncall',
        index: 0,
        name: 'On-call authorisation',
        approvers: [{ kind: 'queue', queueId: Q.ENGINEERING }, { kind: 'user', userId: USR.EMMA }],
        approverIds: [USR.PRIYA, USR.JEN, USR.MIKE, USR.EMMA],
        unresolved: false,
        rule: 'any',
        quorum: 1,
        dueInHours: 2,
        onTimeout: 'escalate',
        escalateTo: { kind: 'user', userId: USR.ADMIN },
        decisions: [],
        state: 'awaiting',
        startedAt: '2026-08-16T08:30:00',
        dueAt: '2026-08-16T10:30:00',
      },
    ],
    currentStage: 0,
    state: 'awaiting',
    createdAt: '2026-08-16T08:30:00',
    resolvedAt: null,
  },
];
