// Generates src/ds/accents.js — the literal Tailwind class map for every accent hue.
//
// WHY THIS IS GENERATED: Tailwind resolves classes by scanning source text. A class
// built at runtime (`bg-${hue}-500`) is invisible to the scanner and silently renders
// unstyled. The v1 prototype had exactly this bug (`focus:border-${type}-500`). Emitting
// every combination as a literal string makes all of them scannable and impossible to
// get wrong. Regenerate with: bun scripts/gen-accents.js
//
// One-pass regeneration, never hand-patch the output.

const HUES = [
  'slate', 'gray', 'red', 'rose', 'pink', 'fuchsia', 'purple', 'violet',
  'indigo', 'blue', 'sky', 'cyan', 'teal', 'emerald', 'green', 'lime',
  'amber', 'orange',
];

/** Roles every accent must answer for, in both light and dark. */
const role = (h) => ({
  // Foreground text/icon on a neutral surface.
  fg:        { light: `text-${h}-600`,  dark: `text-${h}-400` },
  // Foreground on a *soft* surface of the same hue (needs more contrast in light).
  fgOnSoft:  { light: `text-${h}-700`,  dark: `text-${h}-300` },
  // Soft tinted surface — the workhorse for chips, icon tiles, selected rows.
  soft:      { light: `bg-${h}-50`,     dark: `bg-${h}-500/15` },
  softStrong:{ light: `bg-${h}-100`,    dark: `bg-${h}-500/25` },
  softHover: { light: `hover:bg-${h}-100`, dark: `hover:bg-${h}-500/25` },
  // Borders.
  border:    { light: `border-${h}-200`, dark: `border-${h}-500/30` },
  borderStrong: { light: `border-${h}-400`, dark: `border-${h}-500/60` },
  // Solid fill — primary buttons, active pills.
  solid:     { light: `bg-${h}-600`,    dark: `bg-${h}-500` },
  solidHover:{ light: `hover:bg-${h}-700`, dark: `hover:bg-${h}-600` },
  // Small status dot — same in both modes so lists stay scannable.
  dot:       { light: `bg-${h}-500`,    dark: `bg-${h}-500` },
  // Focus ring / active outline.
  ring:      { light: `focus:border-${h}-500`, dark: `focus:border-${h}-500` },
  // Left rail accent bar used on dense list rows.
  rail:      { light: `bg-${h}-400`,    dark: `bg-${h}-500/60` },
});

const lines = [];
lines.push('// GENERATED by scripts/gen-accents.js — do not edit by hand.');
lines.push('// Regenerate: bun scripts/gen-accents.js');
lines.push('//');
lines.push('// Every Tailwind class below is a literal string so the Tailwind scanner can see it.');
lines.push('// Never build an accent class with template interpolation — it will not compile.');
lines.push('');
lines.push('export const ACCENT_HUES = ' + JSON.stringify(HUES) + ';');
lines.push('');
lines.push('export const ACCENTS = {');
for (const h of HUES) {
  const r = role(h);
  lines.push(`  ${h}: {`);
  for (const [k, v] of Object.entries(r)) {
    lines.push(`    ${k}: { light: '${v.light}', dark: '${v.dark}' },`);
  }
  lines.push('  },');
}
lines.push('};');
lines.push('');
lines.push(`/**
 * Resolve one accent role to a class string.
 * @param {string} hue   an ACCENT_HUES member
 * @param {string} roleName  a key of ACCENTS[hue]
 * @param {boolean} dark
 */
export function accent(hue, roleName, dark) {
  const a = ACCENTS[hue] || ACCENTS.gray;
  const r = a[roleName] || ACCENTS.gray[roleName];
  return dark ? r.dark : r.light;
}

/** Resolve a whole accent into a flat {role: class} object for one mode. */
export function accentSet(hue, dark) {
  const a = ACCENTS[hue] || ACCENTS.gray;
  const out = {};
  for (const k of Object.keys(a)) out[k] = dark ? a[k].dark : a[k].light;
  return out;
}
`);

await Bun.write(new URL('../src/ds/accents.js', import.meta.url), lines.join('\n'));
console.log(`wrote src/ds/accents.js — ${HUES.length} hues x ${Object.keys(role('gray')).length} roles`);
